### ISSUE TITLE
Translation to ru_RU and uk_UA

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#114]
- [x] Russian full translation

- [x] Ukrainian full translation

 - [x] Configuration system (Ask user's language)

**Comment by sTiKyt** [comment]
Assign me to this one @usama7628674 @An0nUD4Y

**Comment by usama7628674** [comment]
I assigned it.

**Comment by sTiKyt** [comment]
@usama7628674 thanks

**Comment by sTiKyt** [comment]
Working version will be finished soon :D

**Comment by sTiKyt** [comment]
@usama7628674 @An0nUD4Y Sorry for long waiting! I GOT HOW IT WORKS XD

There example of Russian translation: 
![image](https://user-images.githubusercontent.com/35602029/48720342-2d709500-ec28-11e8-96d1-4a1b39446119.png)

**Comment by usama7628674** [comment]
@sTiKyt What about ukrainian language?

**Comment by sTiKyt** [comment]
That can be done in 10 minutes, I don't have enough time this week (that why I don't contribute) xD
