### ISSUE TITLE
SocialFish - outdated name

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#117]
Everyone knows SocialFish as old, outdated phishing app by UndeadSec
Repositories like Black Arch and Kali Linux already added old, outdated SocialFish, so, this version never replace old one.

But if we rename it, this will become not just fork, but another app!
Maybe we must discuss about new name and change for it?
I'll do all boring works like replacing name in code, creating new video, new screenshots, etc.
So, community, what about new name?

**Comment by sTiKyt** [comment]
And, probably, after renaming we must move this Repository into organization, to make somethng like:

NewSocialFishName/NewSocialFishName instead of An0nUD4Y/NewSocialFishName

**Comment by An0nUD4Y** [comment]
@sTiKyt  Make Sure if you can update it on regular basis.
You can Do everything You want.

**Comment by sTiKyt** [comment]
> @sTiKyt Make Sure if you can update it on regular basis.
> You can Do everything You want.

Only you can move repo to organization , https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by An0nUD4Y** [comment]
@sTiKyt  I think this repo should be renamed and should have a new look. Work on it if you can.??

**Comment by sTiKyt** [comment]
> @sTiKyt I think this repo should be renamed and should have a new look. Work on it if you can.??

I can create organization, and imagine new look

**Comment by An0nUD4Y** [comment]
Ok i'll do it , But What should it be named..?

**Comment by sTiKyt** [comment]
> Ok i'll do it , But What should it be named..?

That why we have this discussion

**Comment by An0nUD4Y** [comment]
Any name ?

**Comment by usama7628674** [comment]
@sTiKyt @An0nUD4Y maybe cleverfish

**Comment by usama7628674** [comment]
hiddeneye

**Comment by sTiKyt** [comment]
> @sTiKyt @An0nUD4Y maybe cleverfish

Maybe SatFish? (Sat -  inteligency  in Latin)

**Comment by An0nUD4Y** [comment]
HACKBYPHISH ?

**Comment by usama7628674** [comment]
@sTiKyt @An0nUD4Y I think hiddeneye is best

**Comment by An0nUD4Y** [comment]
HIDDENEYE ?    done

**Comment by sTiKyt** [comment]
> @sTiKyt @An0nUD4Y I think hiddeneye is best

yep, maybe hiddeneye, i'll create organization

**Comment by usama7628674** [comment]
@An0nUD4Y Okay change it now since you'e the owner of this repo

**Comment by sTiKyt** [comment]
> > @sTiKyt @An0nUD4Y I think hiddeneye is best
> 
> yep, maybe hiddeneye, i'll create organization

Or we'll use ANitel?

**Comment by usama7628674** [comment]
okay

**Comment by An0nUD4Y** [comment]
oK But @sTiKyt  Organisation name should be renamed

**Comment by sTiKyt** [comment]
> oK But @sTiKyt Organisation name should be renamed

ok

**Comment by sTiKyt** [comment]
> > oK But @sTiKyt Organisation name should be renamed
> 
> ok

So, any ideas about arganization name?

**Comment by usama7628674** [comment]
opensea I guess

**Comment by An0nUD4Y** [comment]
I think all Customizations should be made here .

**Comment by sTiKyt** [comment]
> oK But @sTiKyt Organisation name should be renamed

I'll rename anitel to anything we want

**Comment by sTiKyt** [comment]
Organization more good, cause we will be available to create other projects, not only this one

**Comment by usama7628674** [comment]
opensea - name of organization

**Comment by sTiKyt** [comment]
> opensea - name of organization

Why this one? xD

**Comment by usama7628674** [comment]
just a random name

**Comment by sTiKyt** [comment]
hmm maybe just
"Darkness"

**Comment by sTiKyt** [comment]
I very like darkness xD

**Comment by An0nUD4Y** [comment]
DARKSEC ? It should be

**Comment by usama7628674** [comment]
Yes DARKSEC done
so hiddeneye name and DARKSEC organization

**Comment by sTiKyt** [comment]
> DARKSEC ? It should be

What SEC means?

**Comment by An0nUD4Y** [comment]
Security (SEC)

**Comment by sTiKyt** [comment]
Maybe DarknessSec?

**Comment by sTiKyt** [comment]
Or dark?

**Comment by usama7628674** [comment]
@sTiKyt I think DARKSEC is good

**Comment by sTiKyt** [comment]
> @sTiKyt I think DARKSEC is good

ok, this must be named like CAPS or DarkSec?

**Comment by usama7628674** [comment]
yes it should be

**Comment by sTiKyt** [comment]
> yes it should be

CAPS?

**Comment by usama7628674** [comment]
DarkSec for organization and hiddeneye for name

**Comment by An0nUD4Y** [comment]
OK @usama7628674  @sTiKyt  Please ReCustomize Repo Here If you have time.
Organisation Name : DarkSec 
REPO NAME : HIDDENEYE

**Comment by usama7628674** [comment]
I can't since only owner can do this.

**Comment by An0nUD4Y** [comment]
Ok I know but You can customize here?

**Comment by sTiKyt** [comment]
Ok, i'll recustomize, you should move repo to this organization https://github.com/DarkSecDevelopers

Guide how to move right here: 
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by usama7628674** [comment]
@An0nUD4Y Go to main page of this repo and then click settings there you'll find every setting to change name and transferring the repo to organization.

**Comment by sTiKyt** [comment]
@An0nUD4Y @usama7628674 
i invited you like Owners to organization
Just visit this link: https://github.com/DarkSecDevelopers

**Comment by usama7628674** [comment]
@sTiKyt accepted your invitation

**Comment by sTiKyt** [comment]
And don't invite other guys like owners please :3

**Comment by sTiKyt** [comment]
@An0nUD4Y it's guide for you if need: 
![image](https://user-images.githubusercontent.com/35602029/47612167-69776680-da7d-11e8-9ba7-9873c5ce2bcb.png)

**Comment by sTiKyt** [comment]
Name of the new owner shoud be DarkSecDevelopers @An0nUD4Y @An0nUD4Y @An0nUD4Y 
that important

**Comment by usama7628674** [comment]
It's done
