### ISSUE TITLE
Organization and HiddenEye logo

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#118]
What do you think? I can do anything in my Vector graphic editor, i just need ideas

|HiddenEye|DarkSec|
|-|-|
|<img src="https://user-images.githubusercontent.com/35602029/47612319-025bb100-da81-11e8-8769-fed19eec183d.png" alt="HiddenEye" width ="512">|<img src="https://user-images.githubusercontent.com/35602029/47757618-e38f3180-dcaf-11e8-9081-9b38ee3225a7.png" alt="DarkSec" width="512">|

**Comment by An0nUD4Y** [comment]
I''ll come back at 2:30 PM . Please make changes.

**Comment by sTiKyt** [comment]
> I''ll come back at 2:30 PM . Please make changes.

Idk your timeline xD

**Comment by usama7628674** [comment]
maybe black and white eye

**Comment by usama7628674** [comment]
The name should resemble with the repo

**Comment by sTiKyt** [comment]
> maybe black and white eye

Any references please. designers always works with references :D

**Comment by usama7628674** [comment]
![image](https://user-images.githubusercontent.com/29252277/47612213-aa7c7480-da97-11e8-8e2c-87b609435f4b.png)

**Comment by sTiKyt** [comment]
> The name should resemble with the repo

Organization name - just name of team. Or what about you?

**Comment by sTiKyt** [comment]
I can do something like this in 1 minute
but what about original ideas? xxD

**Comment by sTiKyt** [comment]
> I can do something like this in 1 minute
> but what about original ideas? xxD

i thank i can do something, i'll post example here in a 5 minutes

**Comment by usama7628674** [comment]
okay

**Comment by sTiKyt** [comment]
@usama7628674 what about this one? 
![image](https://user-images.githubusercontent.com/35602029/47612263-e9063500-da7f-11e8-812d-78f72e996e6b.png)

**Comment by usama7628674** [comment]
yes it's good

**Comment by sTiKyt** [comment]
@usama7628674 or this one 
![image](https://user-images.githubusercontent.com/35602029/47612290-6631aa00-da80-11e8-8784-61e06e69bc3f.png)

**Comment by sTiKyt** [comment]
What do u think? @usama7628674 First or Second?

**Comment by usama7628674** [comment]
second is good

**Comment by sTiKyt** [comment]
> second is good

Ok, i'll make organization logo later, now i'll redesign page

**Comment by sTiKyt** [comment]
@An0nUD4Y @usama7628674 WOW chek this cool autogenerated thing! https://darksecdevelopers.github.io/HiddenEye/
Now we have website, we just must learn how to edit it xD

**Comment by usama7628674** [comment]
please change SocialFish image from readme.md

**Comment by sTiKyt** [comment]
@usama7628674 don't worry about things like this, I told, I'll do all boring things today

**Comment by An0nUD4Y** [comment]
@sTiKyt  Dude Its great..

GREAT TO BE WITH YOU..!

**Comment by An0nUD4Y** [comment]
Ok now it comes to Script , Please Customize That !

**Comment by An0nUD4Y** [comment]
@sTiKyt I think its time to make changes .,,,, So apply the New Look... I am waiting.????

**Comment by sTiKyt** [comment]
Seems ok? 
![image](https://user-images.githubusercontent.com/35602029/47619347-58167480-dae6-11e8-8dbb-9f15a1e71a4e.png)

**Comment by sTiKyt** [comment]
@usama7628674 
![image](https://user-images.githubusercontent.com/35602029/47619565-b8a6b100-dae8-11e8-823c-ca61f41388c2.png)

**Comment by darkmidus** [comment]
Wow you guys have been on top of things

**Comment by sTiKyt** [comment]
> Wow you guys have been on top of things

Hi

**Comment by darkmidus** [comment]
Hey

**Comment by sTiKyt** [comment]
> Wow you guys have been on top of things

Let's contribute here? Now this not just fork :D

**Comment by darkmidus** [comment]
Great, Can I help.

**Comment by sTiKyt** [comment]
> Great, Can I help.

If you can, please update some web-pages to new version.

**Comment by darkmidus** [comment]
Any ones in particular I should start with

**Comment by sTiKyt** [comment]
> Any ones in particular I should start with

Try Maybe Steam can be first? You just must fix fonts

**Comment by darkmidus** [comment]
Ok, I got it

**Comment by darkmidus** [comment]
I'm in the car, when I get home I'll fix some webpages

**Comment by sTiKyt** [comment]
> I'm in the car, when I get home I'll fix some webpages

nice

**Comment by An0nUD4Y** [comment]
@sTiKyt  Please apply the themes in script.... I am waiting..

**Comment by sTiKyt** [comment]
@An0nUD4Y what about you?

**Comment by sTiKyt** [comment]
@darkmidus hi, what's up? Waiting for your contribution :D

**Comment by darkmidus** [comment]
My bad, I've had stuff to do lately. I may do it in the morning. In my area it is late.

**Comment by sTiKyt** [comment]
@darkmidus I'm my area It's 3:36AM xD

**Comment by darkmidus** [comment]
XD

**Comment by usama7628674** [comment]
Here 6:43AM xD

**Comment by sTiKyt** [comment]
@usama7628674 good morning xD

**Comment by darkmidus** [comment]
Good night XD what country do y'all live in

**Comment by sTiKyt** [comment]
@darkmidus I'm live on Earth, and you, also, can find my Facebook if really wanna know 😁

**Comment by darkmidus** [comment]
Wow I didn't expect you to live on Earth

**Comment by usama7628674** [comment]
We all live on earth.

**Comment by darkmidus** [comment]
Thanks for clarifying usama

**Comment by sTiKyt** [comment]
I'll create discord server for you, guys xD

**Comment by darkmidus** [comment]
You probably shouldn't should

**Comment by Micrafast** [comment]
Nice logo! I like it 😊

**Comment by usama7628674** [comment]
@Micrafast We should add you as member  since you've contributed significantly.

**Comment by usama7628674** [comment]
@Micrafast You can join here https://github.com/DarkSecDevelopers

**Comment by sTiKyt** [comment]
@usama7628674 seems like him already joined.

**Comment by usama7628674** [comment]
@sTiKyt Yes he did.

**Comment by sTiKyt** [comment]
Heyo, i have new logo for DarkSec , i hope you'll like it xD @usama7628674 @An0nUD4Y

**Comment by usama7628674** [comment]
@sTiKyt I do like it

**Comment by An0nUD4Y** [comment]
@sTiKyt  I thought You have another one also...!

**Comment by An0nUD4Y** [comment]
@sTiKyt  Dude, Its Ultimate, I really appreciate Your Contribution.??

**Comment by usama7628674** [comment]
This thread has done its job closing now.
