### ISSUE TITLE
Program works when i'm offline

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#129]
checkConnection() always seems like true.
Please fix it in Checks.py

**Comment by sTiKyt** [comment]
@usama7628674

**Comment by usama7628674** [comment]
I'll look into it.I'm going to university now.

**Comment by usama7628674** [comment]
@sTiKyt Fixed

**Comment by sTiKyt** [comment]
Yep, fixed :D

**Comment by usama7628674** [comment]
@sTiKyt Please be careful with indentation next time.

**Comment by sTiKyt** [comment]
> be careful with indentation next time

Sorry, this my FIRST programming project ever xD I'm noob as programmer here, but can organize and make art xD

**Comment by usama7628674** [comment]
no problem
