### ISSUE TITLE
Merge Dev Branch !

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#130]
@sTiKyt  I think You should merge the Dev branch with Master.
Because till now we don't have a valid script as the name. 
So if you have made sufficient changes & tested them , Then The codes Should be Here.!

**Comment by sTiKyt** [comment]
I'll merge it after we fix main bugs

**Comment by usama7628674** [comment]
Will check once I get back home.

**Comment by sTiKyt** [comment]
Merged.
