### ISSUE TITLE
New Insta Web page with login with facebook button

### ISSUE THREAD

**Issue by 0verd0se** [DarkSecDevelopers/HiddenEye#131]
I have a instagram page with the login with fb button you can add it to this rep https://github.com/0verd0se/SocialFish

**Comment by sTiKyt** [comment]
I'll check it very soon, thank you!

**Comment by sTiKyt** [comment]
Maybe you want to contribute it yourself? @0verd0se

**Comment by 0verd0se** [comment]
I have my exams on November will be free from December that's why just gave an idea xD

**Comment by sTiKyt** [comment]
@0verd0se oh, OK I'll try to do it myself. I hope I'll be able to mark you as co-contributor

**Comment by sTiKyt** [comment]
@0verd0se i don't have enough experience to do it right, so, maybe someone else will add your page into project.

**Comment by usama7628674** [comment]
@0verd0se @sTiKyt I can do it

**Comment by usama7628674** [comment]
@0verd0se The fb page does not resemble with what instagram dumps on the screen.Closing now.I'll change that later when I've free time.
