### ISSUE TITLE
Where can i contribute logos?

### ISSUE THREAD

**Issue by 0verd0se** [DarkSecDevelopers/HiddenEye#132]
![darkeye1](https://user-images.githubusercontent.com/43747211/47699063-b2731a80-dc37-11e8-9b94-97a6f0021ebf.png)

**Comment by sTiKyt** [comment]
That core from Naruto? @0verd0se

**Comment by sTiKyt** [comment]
https://fanparty.ru/fanclubs/uzumaki/articles/121327/119930_tribune_uzumaki.jpg

**Comment by sTiKyt** [comment]
I can't accept this one :D

**Comment by 0verd0se** [comment]
![eye2](https://user-images.githubusercontent.com/43747211/47699217-34fbda00-dc38-11e8-88c3-052b31789130.png)

**Comment by 0verd0se** [comment]
yeah i like naruto lol xD

**Comment by sTiKyt** [comment]
But you can't steal art

**Comment by sTiKyt** [comment]
All must be made by your hands

**Comment by 0verd0se** [comment]
ooh well sorry

**Comment by sTiKyt** [comment]
Wait, I'll create directory for art, probably this will be named "presskit"

**Comment by sTiKyt** [comment]
You will be able to do pull requests with art and I'll check it
