### ISSUE TITLE
Integrating spear phishing in HiddenEye

### ISSUE THREAD

**Issue by 0verd0se** [DarkSecDevelopers/HiddenEye#134]
It would be awesome if https://github.com/WeebSec/PhishX gets added to HiddenEye.

**Comment by usama7628674** [comment]
You can use it.What's the point of adding other tool in hiddeneye since it'll work the same as it's working now.

**Comment by An0nUD4Y** [comment]
I think its a good idea.  I will work on that.

**Comment by An0nUD4Y** [comment]
Sorry Dude, I have Checked it's not gonna to be useful.? 
But Thanks for Giving time..
