### ISSUE TITLE
The ascii picture can't display correctly in Termux

### ISSUE THREAD

**Issue by Micrafast** [DarkSecDevelopers/HiddenEye#141]
The terminal width is not enough for the ascii picture.

**Comment by Micrafast** [comment]
Hmmmm... I didn't have possibility to send a screenshot on my phone,please forgive me!

**Comment by An0nUD4Y** [comment]
@Micrafast  Please Try to capture a screenshot..?

**Comment by usama7628674** [comment]
@Micrafast Well the screnshot from my lg g3 device works perfectly.
https://www.sendspace.com/file/tkgvzl

**Comment by Micrafast** [comment]
Sorry, I don't have time to use computer until tomorrow afternoon,I will send the screenshot on tomorrow afternoon if i remember to send screenshot.

**Comment by Micrafast** [comment]
![image](https://user-images.githubusercontent.com/13199993/47920099-26d5e400-deec-11e8-9776-ba00175a15fb.png)
@An0nUD4Y @usama7628674 Just like this

**Comment by usama7628674** [comment]
Maybe due to the small width of your device.

**Comment by usama7628674** [comment]
@Micrafast Try to zoom-in and zoom-out and check again.

**Comment by Micrafast** [comment]
@usama7628674 It works. Thanks.
