### ISSUE TITLE
Ngrok images bug

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#142]
![image](https://user-images.githubusercontent.com/35602029/48572197-68fe1d00-e911-11e8-8f28-19f81b1a3c3b.png)

**Comment by usama7628674** [comment]
@sTiKyt Reload the page.Sometimes page does not load properly.

**Comment by usama7628674** [comment]
@bosci works fine.

**Comment by sTiKyt** [comment]
I'm still have this bug, reloading don't helps

**Comment by usama7628674** [comment]
Check with serveo

**Comment by usama7628674** [comment]
try on firefox-esr.

**Comment by usama7628674** [comment]
@sTiKyt It's working fine on firefox and chromium.

**Comment by sTiKyt** [comment]
See, if it don't works on my, how can i be sure about it on targets pc?

**Comment by sTiKyt** [comment]
That must work in any browser where works all popular web pages..

**Comment by sTiKyt** [comment]
I don't have any issues with any web pages.. Instead of fake ones..

**Comment by usama7628674** [comment]
What can I say about it?It must've been a problem on your side.I loaded instagram page on firefox and chromium and it's fine on either of these browsers.

**Comment by An0nUD4Y** [comment]
@sTiKyt  Have you Tried to open real website. Does all the content of that is properly loading in your browser. And Wait sometime, i will create a new instagram page ...

**Comment by An0nUD4Y** [comment]
I Think it's not a Bug .
