### ISSUE TITLE
Fb standard phishing page 

### ISSUE THREAD

**Issue by sms72** [DarkSecDevelopers/HiddenEye#145]
In fb standard phishing page when we click on login button after enter id password nothing will happen and it's doesn't send the victim's information.

**Comment by An0nUD4Y** [comment]
ok ,, But which device ??? you are using.

**Comment by sms72** [comment]
Bro I am using Redmi Note 5

**Comment by sTiKyt** [comment]
@sms72 we will check it.

**Comment by sms72** [comment]
Okk @sTiKyt please check it as soon as possible.

**Comment by usama7628674** [comment]
@sms72 Make sure you've cloned `master` branch,stable one.

**Comment by sms72** [comment]
@usama7628674 what bro??? 
What is master branch???

**Comment by usama7628674** [comment]
@sms72 I mean the `HEAD` should be on master branch as the branch is stable one.

**Comment by sms72** [comment]
🤔 don't understand.😔

**Comment by usama7628674** [comment]
@sms72 It's working fine.I just checked it.Closing now.

**Comment by sms72** [comment]
No bro it's also not working give your whatsapp number I will show you.

**Comment by usama7628674** [comment]
@sms72 It does work on my LG-G3.Could've been a problem on your device.You need to figure it out yourself.

**Comment by usama7628674** [comment]
Post the picture here.Just drag and drop it here.
