### ISSUE TITLE
Instructions on readme about lang.

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#147]
Add the proper instructions on read me file about the language ... ???

**Comment by lordcharlx** [comment]
![screenshot_20181129-233155](https://user-images.githubusercontent.com/5570136/49256669-0be58980-f430-11e8-8187-6713fdc1ea56.png)
Error on termux

**Comment by sTiKyt** [comment]
@lordcharlx please create new issue.

**Comment by sTiKyt** [comment]
@An0nUD4Y i'll create -h (--help)
