### ISSUE TITLE
This showing on termux

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#148]

**Comment by lordcharlx** [comment]
![screenshot_20181129-233155](https://user-images.githubusercontent.com/5570136/49256998-2409d880-f431-11e8-844a-009342442e8a.png)

**Comment by sTiKyt** [comment]
@lordcharlx are you sure that latest version of HiddenEye?

**Comment by lordcharlx** [comment]
@sTiKyt yes everything working fine until I delete and cloned today  update

**Comment by sTiKyt** [comment]
@lordcharlx wait a little, i'll check and fix it just right now! Just a minute. Thank you for feedback.

**Comment by lordcharlx** [comment]
Thanks in advance !

**Comment by sTiKyt** [comment]
@lordcharlx please check, this problem was solved. If problem fixed - close this issue. Thank you.

**Comment by sTiKyt** [comment]
@lordcharlx probably solved, i need your approvement to close issue.

**Comment by sTiKyt** [comment]
@lordcharlx Now i'm creating Discord server for DarkSec, you can chat here: https://discord.gg/Ugxfw5c
