### ISSUE TITLE
HiddeEye is a copy from ShellPhish/Blackeye

### ISSUE THREAD

**Issue by thelinuxchoice** [DarkSecDevelopers/HiddenEye#151]
It uses the same engine: Ngrok, Serveo, TinyURL, Location.

Some parts of the code is the same, is like a port to python.

Give me the credits man! 

[https://github.com/thelinuxchoice/shellphish](https://github.com/thelinuxchoice/shellphish)
[https://github.com/thelinuxchoice/blackeye](https://github.com/thelinuxchoice/blackeye)

**Comment by sTiKyt** [comment]
@thelinuxchoice all code here was created by our team, you can't slave all phishing genre because of your tool. You used bash - we python. See any problems? You can report.

**Comment by sTiKyt** [comment]
@thelinuxchoice o my god, Opera,Chrome,Firefox,Brave, Tor seems like similar browsers!!! Report! REPORT!

**Comment by usama7628674** [comment]
@sTiKyt That's why I blocked him
