### ISSUE TITLE
Advanced Method Ranking facebook bug

### ISSUE THREAD

**Issue by Cyb3rG0D7** [DarkSecDevelopers/HiddenEye#152]
143/5000
When using the ranking link, and when capturing the credentials HIddenEye closes and does not show the credentials, an error comes out, use Parrotsec 4.4.

**Comment by usama7628674** [comment]
@Colocho7 Please upload screenshot here.It's very hard to debug it form here.

**Comment by Colocho7** [comment]
![logoerror](https://user-images.githubusercontent.com/35184132/49335035-d7e6a180-f5b2-11e8-86af-bd5513a9047f.png)
The logo no look at start.

**Comment by Colocho7** [comment]
![captura de pantalla -2018-12-01 21-50-49](https://user-images.githubusercontent.com/35184132/49335047-327ffd80-f5b3-11e8-9cfc-16f4cfc2bb7d.png)
After using the option 2 of facebook, when entering the credentials that, in version 0.1.0 works well.

**Comment by usama7628674** [comment]
@Cyb3rG0D7 It's fixed now.Reclone the tool again or do `git pull`

**Comment by sTiKyt** [comment]
Don't close issue that you don't sure you fixed.
