### ISSUE TITLE
New phish

### ISSUE THREAD

**Issue by Sara123984** [DarkSecDevelopers/HiddenEye#155]
Can you please make a page for testing amazon with OTP

**Comment by usama7628674** [comment]
@Sara123984 What is OTP ?

**Comment by An0nUD4Y** [comment]
its one time passwors .

**Comment by An0nUD4Y** [comment]
@usama7628674  i think its about 2-factor authenication , bypassing ????

**Comment by An0nUD4Y** [comment]
@Sara123984  Thnks to Be here , I hope you found your answer. Now you can close the issue. If still any query please recomment.

**Comment by sTiKyt** [comment]
@Sara123984 we wanna help but now we don't have enough contributors to add new cool features like fake 2 factor auth.

**Comment by sTiKyt** [comment]
@Sara123984 if you are interested in future of HiddenEye you can post your opinion about it in any social network. Thank you for your choice, HiddenEye always will grow and evolve!
