### ISSUE TITLE
Serveo

### ISSUE THREAD

**Issue by greyxhood** [DarkSecDevelopers/HiddenEye#156]
This tool would be awesome if you can host with a custom sub-domain to Serveo!!
like how they did with this phishing tool : https://github.com/M4cs/BlackEye-Python

**Comment by usama7628674** [comment]
@greyxhood Custom subdomain added. @sTiKyt Please translate the english in UK and RU in this commit
https://github.com/DarkSecDevelopers/HiddenEye/commit/803604b8920809c33bd57adcc35fa80739592816

**Comment by greyxhood** [comment]
nice job on the update! But can you also make it so that the custom subdomain can include a .com (example: facebook.com.12345678.serveo.net)? When I enter a subdomain like that I get:

Traceback (most recent call last):
  File "/root/HiddenEye/Defs/Actions.py", line 110, in runServeo
    output = check_output("grep -o 'https://[_0-9a-z]*\.serveo.net' link.url",shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'grep -o 'https://[_0-9a-z]*\.serveo.net' link.url' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "HiddenEye.py", line 29, in <module>
    selectServer()
  File "/root/HiddenEye/Defs/Actions.py", line 85, in selectServer
    runServeo()
  File "/root/HiddenEye/Defs/Actions.py", line 119, in runServeo
    except subprocess.CalledProcessError:
NameError: name 'subprocess' is not defined

I was able to achieve these types of sub domains with the BlackEye-Python tool but HiddenEye is better. Thanks!!!!

**Comment by usama7628674** [comment]
@greyxhood I'll add this as well.

**Comment by usama7628674** [comment]
@greyxhood It's done.Now your custom subdomain will work properly.Grab latest commit and try again.
