### ISSUE TITLE
usama WHAT A F*CK?

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#157]
Why you just removed all my translation system? Wtf man? WHY YOU EDITED MAIN BRANCH?WHY WE HAVE F*CKING DEV BRANCH?!! WHAT A F*CK? My work was destroyed...

**Comment by sTiKyt** [comment]
Sorry for agression :3

**Comment by sTiKyt** [comment]
And please, google "Python gettext translation"..And edit dev branch only!!

**Comment by usama7628674** [comment]
@sTiKyt I fixed it.

**Comment by usama7628674** [comment]
@sTiKyt Logo is not working

**Comment by usama7628674** [comment]
@sTiKyt Now that is out of the way could you please help me to create ascii logo by going here
https://github.com/DarkSecDevelopers/Keylogger/issues/1 
I've added you as collaborator just check your mail.
