### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by Edu4rdSHL** [DarkSecDevelopers/HiddenEye#158]
Hello, 

I'm packaging it tool for BlackArch but in the latest release I'm getting:

```
edu4rdshl@blackarch ~/Scripts/HiddenEye -> hidden-eye 
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/opt/hidden-eye/Defs/Checks.py", line 23, in <module>
    print (_('''{1}
NameError: name '_' is not defined
```
It was fixed in one latest commit.

Regards.

**Comment by sTiKyt** [comment]
@Edu4rdSHL oh, you making only BlackArch package? Can you make AUR package please? :3 I don't have enough time to learn how PKGBUILD works...

And yep, just a moment, release will be soon!

**Comment by Edu4rdSHL** [comment]
@sTiKyt I'm developer of BlackArch and don't have enought time also... but i will just copy/paste the PKGBUILD to AUR. Still waiting for the release.

**Comment by sTiKyt** [comment]
@Edu4rdSHL thanks. Just a moment

**Comment by sTiKyt** [comment]
@Edu4rdSHL sorry for waiting!

**Comment by Edu4rdSHL** [comment]
@sTiKyt and @usama7628674 thank you, the tool was added to BlackArch in https://github.com/BlackArch/blackarch/commit/566de5dc4588ee6db8025d986bd4a40e8fab03ca
