### ISSUE TITLE
HiddenEye GUI

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#159]
I think our software can be newbie-friendly, right? So, this will be Qt based UI. (Because new Gtk have compatibility problems)

How can you **help me** to create interface? You can:
- Give interface suggestions
- Explain how works our web part of code. (I know only python, idk how fake-pages built)

**Comment by usama7628674** [comment]
@sTiKyt Please not to use new version of `PyQt5`.You can also use `tkinter` or `GTK3`.

**Comment by usama7628674** [comment]
@sTiKyt `PyQt5` is advanced so I think `tkinter` is the way to go

**Comment by sTiKyt** [comment]
@usama7628674 PyQt5 have app named Qt Designer - visual editor for interface. This will help i think

**Comment by usama7628674** [comment]
@sTiKyt Yes I know and used it on windows.This will make work a lot easier.

**Comment by usama7628674** [comment]
@sTiKyt What about Termux users?GUI won't work on termux.

**Comment by Franchium** [comment]
I think thats a bad idea for blackarch users where most of the tools in it run on terminal not gui

**Comment by usama7628674** [comment]
@Franchium It'll work if you've PyQt5 module installed for python.

**Comment by sTiKyt** [comment]
@usama7628674 gui will be just addition to console version, why not?

**Comment by usama7628674** [comment]
@sTiKyt What about termux users GUI won't work?

**Comment by sTiKyt** [comment]
@usama7628674 they still will be able to use console.. I'll update GUI with console version, parallel..

**Comment by usama7628674** [comment]
@sTiKyt So you choose GTK+ any reason why?

**Comment by usama7628674** [comment]
@sTiKyt Thank you very much.I'll also join in for GUI development.

**Comment by sTiKyt** [comment]
> @sTiKyt Thank you very much.I'll also join in for GUI development.

cool

**Comment by sTiKyt** [comment]
@usama7628674 seems like GTK have problems with stability... For example app for Gtk 3.0 can't be opened with Gtk 3.20.. We made bad choice.. I think this will be Qt

**Comment by usama7628674** [comment]
@sTiKyt Okay

**Comment by sTiKyt** [comment]
No time to do it

**Comment by rootroota1** [comment]
I have tried it but it fails again
