### ISSUE TITLE
Loading string always in English

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#160]
**HiddenEye is Opening. Please Wait...%%** always shown in English.

Russian | Ukrainian | English
-- | -- | --
![image](https://user-images.githubusercontent.com/35602029/49488633-177de980-f850-11e8-972b-85875a637a1c.png)| ![image](https://user-images.githubusercontent.com/35602029/49488648-311f3100-f850-11e8-892c-5cd19f641e2e.png)| ![image](https://user-images.githubusercontent.com/35602029/49488660-45632e00-f850-11e8-9627-2e647f81e5bd.png)

**Comment by sTiKyt** [comment]
@usama7628674 lol, we always have problems with this line only xD

**Comment by usama7628674** [comment]
@sTiKyt I'll look into it.Currently busy preparing for exam.

**Comment by sTiKyt** [comment]
@usama7628674 ok

**Comment by usama7628674** [comment]
@sTiKyt I fixed it.Please check again and let me know if it's working for you.
