### ISSUE TITLE
Mobile fb Phising page not working on mobile phone

### ISSUE THREAD

**Issue by Franchium** [DarkSecDevelopers/HiddenEye#161]
After i click the login button, nothing happen but when im login with using a pc it did work. I think there's a problem for mobile device. 

I did also try with another phone and network and its just same

![img_20181205_132406-1](https://user-images.githubusercontent.com/41231953/49494109-69297280-f856-11e8-98b4-94998aa7082f.png)

**Comment by usama7628674** [comment]
@Franchium It'll be fixed soon.

**Comment by usama7628674** [comment]
@Franchium Fixed.Download the tool again

**Comment by Franchium** [comment]
I tried to run pacman -Sy hidden-eye but there is no newest update available.

**Comment by Franchium** [comment]
Its need to get in to the directory to of the folder to run and not installed on the systems i think

**Comment by usama7628674** [comment]
@Franchium The recent commits would not be in latest release cuz the latest release is 2 days ago.

**Comment by Franchium** [comment]
Hufft, i will just wait till the new version

**Comment by usama7628674** [comment]
@Franchium Why don't you git clone this repo and use it?

**Comment by usama7628674** [comment]
@Franchium No need for next release
