### ISSUE TITLE
Need Help To clone webpage.

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#163]
@usama7628674  @sTiKyt  Guys, Can you help me to CLONE this page properly , I need that for further insta phishing attack scenario.

https://www.instagram.com/instagram/

It has already taken a lot of my time, but still not working. 
I am uploading my work .

http://www.mediafire.com/file/l45t5mwusb6l0c4/www.instagram.com.rar/file
 
I hope you will help,

**Comment by usama7628674** [comment]
@An0nUD4Y Could you describe what are trying to achieve here.Why do you need official instagram page?Did you clone the above site and by which tool.

**Comment by An0nUD4Y** [comment]
@usama7628674  i used httrack to clone the required files and html, 

I want to make a page that can trick user to click on follow button which will make a prompt to login first. 
In most of scenario this will work perfectly.

I hope, it will be a nice idea. Afterall , This script is about advanced phishing .....

**Comment by usama7628674** [comment]
@An0nUD4Y First of all you can't clone instagram with httrack or any other tool.Just save the above page then using javascript to route victim to fake instagram login site when he clicks follow.This is very easy for me to do it.

**Comment by sTiKyt** [comment]
@An0nUD4Y i recomment you to use wget, very nice for sites..

**Comment by usama7628674** [comment]
@sTiKyt Nope won't work for instagram.You can't just clone clone sites that have javascript at the backend.
I'll add this phishing method when I've free time.

**Comment by sms72** [comment]
@An0nUD4Y bro plss check your instagram inbox I want some help..

**Comment by An0nUD4Y** [comment]
@usama7628674  bro you shuould check the files, i have worked on them. Please give a try to these file, Please compare that webpage with the fake instagram  we have  made ???

**Comment by usama7628674** [comment]
@An0nUD4Y Here's what I see when I tried to host your page locally using xampp

![image](https://user-images.githubusercontent.com/29252277/49648113-7b6a0300-fa46-11e8-81b9-47a60f4f5dbe.png)

I know what are trying to achieve here.I'll work on it next week.

**Comment by usama7628674** [comment]
@An0nUD4Y I've done what you're trying to achieve.Take a look at [here](http://www.mediafire.com/file/avaj45lzfezcg4c/instagram.rar/file) and report back.Click follow button and the page will redirect to fake login page.

**Comment by An0nUD4Y** [comment]
@usama7628674 Its working perfectly, Can i know ,what was the issue in my edited codes.

**Comment by usama7628674** [comment]
@An0nUD4Y Just save the webpage(complete)  then open the html page then change **follow** button link to fake login page.

**Comment by usama7628674** [comment]
@An0nUD4Y So should I make a pull request if you want to add this feature in instagram?

**Comment by An0nUD4Y** [comment]
Wait i am adding ??
