### ISSUE TITLE
Blank Page [Ubuntu]

### ISSUE THREAD

**Issue by HAKRSINGH** [DarkSecDevelopers/HiddenEye#167]
I'm getting a blank page on Instagram and other sites. Like the website opens properly for 1-2 times but after that blank pages start coming up. I use Ubuntu 18.04 and installed all the required packages. I have 20+ Mbps internet if you guys were wondering.

**Comment by HAKRSINGH** [comment]
Nevermind updating the packages seem to have resolved this!

**Comment by HAKRSINGH** [comment]
Still having this issue. Please help

**Comment by usama7628674** [comment]
Try with ngrok

**Comment by usama7628674** [comment]
@HAKRSINGH Which page are you using?
1. Instagram_web
2.Instagram_autoliker
3.Instagram_advanced_attack

**Comment by sTiKyt** [comment]
abandoned by user
