### ISSUE TITLE
Serveo Network Error

### ISSUE THREAD

**Issue by RattlingAmigo** [DarkSecDevelopers/HiddenEye#168]
I have good speed of Internet. But 'Serveo' isn't generating link. 
Everytime it ends with saying network error.
![issue](https://user-images.githubusercontent.com/33193838/50338896-aa4ca280-0537-11e9-8f1b-7624be7b57a9.PNG)

**Comment by An0nUD4Y** [comment]
Looks like serveo.net is Down Currently. 
Check if you can browse https://serveo.net/ 
OR 
Use ngrok .

**Comment by RattlingAmigo** [comment]
@An0nUD4Y 
Obviously, i can visit that. And, i've used ngrok, cool!
But i wanna use serveo.

Any help?

**Comment by An0nUD4Y** [comment]
Try to use serveo manually.. `ssh -R 80:localhost:3000 serveo.net`
If works please let us know.

**Comment by usama7628674** [comment]
Don't use dots cuz serveo dumps error that's why you can't see any link.

**Comment by usama7628674** [comment]
@An0nUD4Y Yes change it.

**Comment by RattlingAmigo** [comment]
It would be loved if you guys give an relate example like:
https://example.serveo.net   ?

**Comment by usama7628674** [comment]
@RattlingAmigo Try https://facebook.serveo.net

**Comment by RattlingAmigo** [comment]
@usama7628674 Yeah!, thanks buddy ;).
