### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RattlingAmigo** [DarkSecDevelopers/HiddenEye#169]
How about when someone clicks on the link, and we get his location and also get informed that the victim has clicked on the link <Just by now>?

Maybe this helps a lot.

**Comment by An0nUD4Y** [comment]
@RattlingAmigo its easy to be done. Even it was present in old version. But later removed.
But I will add this feature.

**Comment by RattlingAmigo** [comment]
@An0nUD4Y 
Yeah, thanks.
