### ISSUE TITLE
error message need help please

### ISSUE THREAD

**Issue by souriens253** [DarkSecDevelopers/HiddenEye#172]
i received this message what i need to do to solve it thanks you
Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by Micrafast** [comment]
Run this:
pip3 install wget

**Comment by souriens253** [comment]
thank but i did it i think is install i get this answer
```
### sudo apt-get install wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wget is already the newest version (1.19.5-1).
0 upgraded, 0 newly installed, 0 to remove and 228 not upgraded.
```
i try to lunch again same error message

**Comment by usama7628674** [comment]
@souriens253 I think you're installing it for python2.
`pip3 install wget`
This will install for python3

**Comment by souriens253** [comment]
thanks you i update it

**Comment by An0nUD4Y** [comment]
@souriens253 if fixed, Don't forget to close the issue.

**Comment by fadiking456** [comment]
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
ModuleNotFoundError: No module named 'Defs'

**Comment by D-E-F-E-A-T** [comment]
I am using `pip3 install wget` It says requirement already satisfied but when I run the program I am still getting no module wget error. What can it be? I am using virtual env and I have checked issues like it's active and all.
