### ISSUE TITLE
 NGROK Connection Failed & Phishing Pages Detected By Chrome

### ISSUE THREAD

**Issue by CyberTheReape** [DarkSecDevelopers/HiddenEye#174]
First of all thank you for this beautiful project.but after several attempts with ngrok, ngrok warns you have tried many times..Please upgrade your ngrok account if you want to use more ..

later I tried to do with the servero.but google gives red page alert.this site is not trusted. What do you think?

ip address writing options need to be. ngrok and servero are distressed

**Comment by An0nUD4Y** [comment]
@CyberTheReape  , For a effective attack, we are using  a lot of back connections such as keylogger , ip , UA , and many web page css,images. These are require a lot of requests at a time. So basically, at the time we are using a free connection of ngrok. This causes the trouble & occuring such error. 

**Solution**
- Try to manually less these connection by inspecting them, you can edit server files at server/www location in hiddeneye folder.

PLEASE GIVE A SCREENSHOT OF SERVEO ISSUE. THIS WILL HELP ME MORE BETTER TO RESOLVE .

**Comment by CyberTheReape** [comment]
![1](https://user-images.githubusercontent.com/42475284/50540508-0650a000-0ba4-11e9-81bc-d79eba3f2b82.png)

**Comment by An0nUD4Y** [comment]
@CyberTheReape  , This is due to the Chrome has detected the Phishing attack.
You can Simply continue to the page, click on _Advanced_ Then Click on _Proceed to Website_
PLEASE TELL? WHICH ATTACK YOU ARE USING ? 
So that we can make it undetectable. 
**OR (worst case)**
It may happen that, chrome had blocked the serveo[.]net certificate.

**Comment by usama7628674** [comment]
@CyberTheReape The only solution is to host the page on custom domain and use different certificate.

**Comment by usama7628674** [comment]
@CyberTheReape just type serveo on google search and at the top you'll see 
`This site may harm your computer.`

**Comment by CyberTheReape** [comment]
I tried openport program today. openport is working on the external network..

I previously shared a video about the openport program in my youtube channel.

https://www.youtube.com/watch?v=2dvc03P6jXM

this program is nice from ngrok and servero... Set the hiddeneye program to work with the openport program..

**Comment by An0nUD4Y** [comment]
@CyberTheReape , Thanks To be Here ! && You can help us to do more, By creating a Tutorial on Your Channel.

**Comment by CyberTheReape** [comment]
I'm thinking about sharing this program on my youtube channel but this way many people will have problems..

It would be better if it worked with the openport program.cancel the servero program.add openport instead

**Comment by An0nUD4Y** [comment]
@CyberTheReape , It may be added later. Currently i don't have enough time to do so.

**Comment by usama7628674** [comment]
@sTiKyt Yes that will also be another possibility.

**Comment by sTiKyt** [comment]
@usama7628674 isn't this solved?

**Comment by usama7628674** [comment]
@CyberTheReape @sTiKyt @An0nUD4Y Google is drunk recently.They lift the malware tag from serveo.I just checked.It's working fine now on all browsers.

**Comment by sTiKyt** [comment]
@CyberTheReape seems like this works fine now.

**Comment by CyberTheReape** [comment]
I haven't tried it yet..Do you plan to use the openport program? alternative to openport ngrok or servero
@sTiKyt

**Comment by usama7628674** [comment]
@CyberTheReape Problem is openport won't let you to choose your own subdomain and serveo is now working fine so you should use serveo.

**Comment by sTiKyt** [comment]
@CyberTheReape so, problem solved ;D Thank you for using our software!

**Comment by An0nUD4Y** [comment]
@Phoenix1112 , Thanks For The advise ,
I will Add Openport & Pagekite As alternatives till next week.

Join our telegram channel to know more about updates.
http://t.me/darksecdev
