### ISSUE TITLE
Network error. Verify your connection.

### ISSUE THREAD

**Issue by UnknownBean** [DarkSecDevelopers/HiddenEye#175]
Upon launching the program with "python3 HiddenEye.py" It immediately exits with the error "Network error. Verify your connection.". I've tried running it as root and everything but it just keeps exiting with the same error before it even tries to load.

**Comment by An0nUD4Y** [comment]
@unknownBean , please verify if you have a working internet connection ?

**Comment by UnknownBean** [comment]
How would I have posted this if I didn't have a working internet connection? But yes I have verified it by deleting hidden eye and redownloading it. I can assure you it works.

**Comment by UnknownBean** [comment]
Pulled latest commit and still same error "Network error. Verify your connection."

**Comment by UnknownBean** [comment]
No, and neither is duckduckgo, its my default search engine. I've tried numerous commits and running with and without root.

**Comment by UnknownBean** [comment]
Yeah I've been pretty confused about it as well, it just doesn't add up to me.

**Comment by sTiKyt** [comment]
@usama7628674 i think better will be to check both, Google and Duckduckgo..And if one of these reachable - accept connetion.

**Comment by sTiKyt** [comment]
@UnknownBean problem on your side :(

**Comment by usama7628674** [comment]
@UnknownBean Unfortunately we can't help you cuz it's very hard to debug from here.You've to try on your own.
