### ISSUE TITLE
Google phishing pass bug

### ISSUE THREAD

**Issue by Phoenix1112** [DarkSecDevelopers/HiddenEye#176]
hello. I was experimenting with google phishing. I wrote eight 1 for the password.
but the incoming password = 111111118

Why is it write 8 at the end of the password?

![1](https://user-images.githubusercontent.com/42475284/50607910-f60a2f00-0edb-11e9-8545-018c759f22c9.png)
![2](https://user-images.githubusercontent.com/42475284/50607921-fa364c80-0edb-11e9-8977-47242b210c47.png)
![3](https://user-images.githubusercontent.com/42475284/50607927-fe626a00-0edb-11e9-9578-e96ea23604e7.png)

**Comment by sTiKyt** [comment]
I'm sorry but there no problem, i tried it myself
I can't reproduce this bug, all works fine
Thank you for using our software @CyberTheReape

**Comment by usama7628674** [comment]
@CyberTheReape Yes you're right.It does happen at the end of the password.8 gets printed at the end.I'll look into it later.Thanks for pointing that out.

**Comment by deadfishhackers** [comment]
Ngrok and Serveo detect these kinda phishing attacks, try on a free web hosting service?

**Comment by deadfishhackers** [comment]
ive tested it, and it surely does add a number 8 at the end,

this won't stop you from getting the password :D

**Comment by sTiKyt** [comment]
Yep, that's true

**Comment by KnightSec-Official** [comment]
the php is buggy... maybe you should add a limit of creds to put in the pass.... javascript or idk

**Comment by usama7628674** [comment]
@Phoenix1112 @deadfishhackers @sTiKyt Fixed. please try again.
