### ISSUE TITLE
Doesn't work on Android 9

### ISSUE THREAD

**Issue by Palmus84** [DarkSecDevelopers/HiddenEye#177]
Android 9 detect ph1sh1ng and doesn't give any username and any pass.

**Comment by usama7628674** [comment]
@Palmus84 Which browser gives a warning message?Is it chrome?

**Comment by sTiKyt** [comment]
@Palmus84 i used it on Android 9 by myself, i'm sure that there chance that you tried to use Google Chrome and Servero on your phone... #174

**Comment by usama7628674** [comment]
@Palmus84 see #174

**Comment by sTiKyt** [comment]
@usama7628674 i told same thing.. xD

**Comment by Palmus84** [comment]
Ok I've read #174 just few minutes ago. Thanks!
