### ISSUE TITLE
Wget module error

### ISSUE THREAD

**Issue by ironpatro** [DarkSecDevelopers/HiddenEye#178]
![screenshot from 2019-01-03 22-58-08](https://user-images.githubusercontent.com/44530586/50652188-b579e680-0fab-11e9-985e-26e2a1f4c703.png)

**Comment by sTiKyt** [comment]
@ironpatro instead of using "pip install wget" please try "pip3 install wget"

**Comment by sTiKyt** [comment]
Duplicate #172
