### ISSUE TITLE
Official documentаtion

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#179]
We need to write documentаtion.

**Comment by sTiKyt** [comment]
@usama7628674 right

**Comment by usama7628674** [comment]
Okay go ahead and make one.

**Comment by sTiKyt** [comment]
@usama7628674 my keyboard broken, i told you, are'nt i?

**Comment by usama7628674** [comment]
Ok after getting a new keyboard then jump on and make an official wiki page.

**Comment by sTiKyt** [comment]
@usama7628674 i'll try but there must be someone who will fix grammar errors after me xD

**Comment by usama7628674** [comment]
@sTiKyt I got you covered

**Comment by An0nUD4Y** [comment]
@sTiKyt  Don't worry about that.

**Comment by DopeWiz** [comment]
what are we here for??
we can!!
