### ISSUE TITLE
Permission checking at startup in termux, causing trouble.

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#182]
Guys, The initial  checking for root permission in termux causing trouble for those who doesn't have sudo as command
OUTPUT LOOK LIKE 
_

_> Traceback (most recent call last):
>   File "HiddenEye.py", line 15, in <module>
>     checkPermissions()
>   File "/home/udy/Desktop/HiddenEye-master/Defs/Checks.py", line 59, in checkPermissions
>     raise PermissionError("{0}Permissions denied! Please run as '{1}sudo{0}'".format(RED, GREEN))
> PermissionError: Permissions denied! Please run as 'sudo'_

_
--

**Comment by sTiKyt** [comment]
@An0nUD4Y undo latest commit

**Comment by sTiKyt** [comment]
@An0nUD4Y this isn't error at all, you must use administrator rights to run correctly

**Comment by An0nUD4Y** [comment]
@sTiKyt , I know , its not an error ,you should read the title carefully.

**Comment by An0nUD4Y** [comment]
@sTiKyt , Now their is only one way remained , that is all the termux users have to install sudo in termux.
I found a repo on GitLab to achieve this. https://gitlab.com/st42/termux-sudo

**Comment by An0nUD4Y** [comment]
@sTiKyt , I This we should add instructions in _instructions.md_

**Comment by lordcharlx** [comment]
@sTiKyt  i have a project that will interest the whole house in here https://github.com/lordcharlx/curiosus_api

**Comment by An0nUD4Y** [comment]
@lordcharlx ,  move that project on darksec & join us. I think this will be the best project to be work on.
You should join now.

**Comment by An0nUD4Y** [comment]
@sTiKyt I think ,installing sudo from the gitlab repo mention above will be tough to get because it required rooted device. 
We have to find other way.

**Comment by An0nUD4Y** [comment]
@sTiKyt , we have to find a way for termux support.

**Comment by Henrybluesky** [comment]
I ran Tools as your guide but somehow I used "Fishing Facebook" to go to "[RANDOM LOCALXPOSE URL] !!"  then it cannot load Url, hope you support, thank you!

**Comment by Sahraoui1** [comment]
Permissions denied! Please run as 'sudo'
The solution please

**Comment by darkmidus** [comment]
@Sahraoui1 Unless you are running termux just make sure to run with sudo. Do the command:

> sudo python HiddenEye.py

**Comment by Sahraoui1** [comment]
No superuser binary detected.
Are you rooted?
What is missing?

**Comment by Sahraoui1** [comment]
@darkmidus 
No superuser binary detected.
Are you rooted?

**Comment by Sahraoui1** [comment]
I use the command (sudo python HiddenEye.py ) but it show : no superuser
binary detected. are you rooted?
