### ISSUE TITLE
Interesting project [Not HiddenEye]

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#183]
@sTiKyt  i have a project that will interest the whole house in here https://github.com/lordcharlx/curiosus_api

_Originally posted by @lordcharlx in https://github.com/DarkSecDevelopers/HiddenEye/issues/182#issuecomment-453751300_

**Comment by lordcharlx** [comment]
in here @Pouriyahe     https://github.com/lordcharlx/curiosus_api

**Comment by usama7628674** [comment]
@lordcharlx Could you explain what your is about?

**Comment by sTiKyt** [comment]
@lordcharlx Explain me what is it xD all screenshots got broken, so, we can't see wtf is it xD

**Comment by sTiKyt** [comment]
also i tried to google what is C&C....
![image](https://user-images.githubusercontent.com/35602029/51080710-88cf7880-16e9-11e9-8690-965fcfc9705c.png)

**Comment by sTiKyt** [comment]
@lordcharlx Command &Control? Cool, i always wanted to have botnet xD

**Comment by usama7628674** [comment]
@sTiKyt I tried to run it but it's not working.
![screenshot from 2019-01-13 07-46-31](https://user-images.githubusercontent.com/29252277/51080999-72d0b080-1707-11e9-9ffb-d3b8dc1aa82a.png)

**Comment by sTiKyt** [comment]
@usama7628674 they told there some bugs to fix

**Comment by usama7628674** [comment]
@sTiKyt Yes there are some problems in modules but I managed to fix it but still not working.

**Comment by sTiKyt** [comment]
@usama7628674 i think we can write C&C АPI from blank but use some of "curiosus_api" code xD

**Comment by usama7628674** [comment]
@sTiKyt Wait let @lordcharlx explain about the project and screenshots in running form.

**Comment by sTiKyt** [comment]
@usama7628674 i found screenshots in "screenshots" folder xD

**Comment by Pouriyahe** [comment]
I think the app can be found here : 
https://github.com/Kopites/curiosus

**Comment by sTiKyt** [comment]
@Pouriyahe mobile app

**Comment by usama7628674** [comment]
@Pouriyahe Yes it an android app mainly for rooted phones

**Comment by lordcharlx** [comment]
It's a command and control server for an android phone but I want to hybridise it so iOS can be included

**Comment by usama7628674** [comment]
@lordcharlx For iOS you need to code app in swift and objective-c cuz java is only for android platform.

**Comment by usama7628674** [comment]
@lordcharlx But then again advanced features won't like like getting whatsapp messages without rooted phone.

**Comment by lordcharlx** [comment]
I need to get the web app running first !

**Comment by lordcharlx** [comment]
For those looking for c and c I have a some fully armed but not as cool as this in an share if you want

**Comment by sTiKyt** [comment]
@lordcharlx i hate Whatsapp, what about **Discord**? https://discord.gg/ZTsEre
I started new **Discord** server specially for **DarkSecDevelopers**

**Comment by sTiKyt** [comment]
@lordcharlx i was banned(flaged) for a while -_-

**Comment by sTiKyt** [comment]
@lordcharlx how?Idk.
Why?Because of little spam :D
By?GitHub anti-spam bots

GitHub support fortunately unbanned me when i requested, so..I'll never spam again xD

**Comment by lordcharlx** [comment]
lols

**Comment by usama7628674** [comment]
@lordcharlx app.py is missing in curiosus_api repo.

**Comment by lordcharlx** [comment]
@usama7628674   cant figure that out

**Comment by lordcharlx** [comment]
@usama7628674   cant figure that out

**Comment by sTiKyt** [comment]
@lordcharlx we can speak about this project at Discord, i'm clossing issue cause of off-topic
