### ISSUE TITLE
Issues in Kali

### ISSUE THREAD

**Issue by daredevil12345** [DarkSecDevelopers/HiddenEye#188]
root@kali:~/HiddenEye# python HiddenEye.py 
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/HiddenEye/Defs/Checks.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request

**Comment by daredevil12345** [comment]
i tried all old same solutions with socialfish but updating PIP and wget others didnt worked out yet

**Comment by usama7628674** [comment]
@daredevil12345 Read [here](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md)
