### ISSUE TITLE
Termux sudo warning

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#192]
Just gonna make it to show something like "You're using Termux, please install HiddenEye from Termux branch" if user on Termux

**Comment by An0nUD4Y** [comment]
@sTiKyt  I didn't get your point. Please make it clear.

**Comment by sTiKyt** [comment]
@An0nUD4Y don't worry, i gonna do it :D
I assigned myself to it and you'll see pull what i mean at pull request

**Comment by An0nUD4Y** [comment]
@sTikyt , Do it dude, but currently I am closing it... Feel free to reopen.
