### ISSUE TITLE
Add Custom Template

### ISSUE THREAD

**Issue by jepunband** [DarkSecDevelopers/HiddenEye#194]
--add custom template like from -- https://github.com/jeretc/cfp

**Comment by usama7628674** [comment]
@jepunband I'll add this but captive portal is useful in mitm attack like spawning a fake AP then redirect victim to fake portal page to capture creds.I'll still add this just to extend the functionality of the tool.

**Comment by sTiKyt** [comment]
@An0nUD4Y next time when you gonna release something please use "pre-release" tag

**Comment by An0nUD4Y** [comment]
Too old ... Not respond....
Suggestions not applied...
Open Again if Have any quory..
