### ISSUE TITLE
wget

### ISSUE THREAD

**Issue by KingMhamad** [DarkSecDevelopers/HiddenEye#196]
./HiddenEye.py
Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'
______________________
i have wget installed.

**Comment by sTiKyt** [comment]
#178 #189 #186 #172 
Check these ones...
Probably you just need to install Python3 wget..I think you have wget for python 2.
And please, next time search closed issues with your problem.

**Comment by KingMhamad** [comment]
$ pip3 install wget
No command 'pip3' found, did you mean:
 Command 'pico' from package 'alpine'
 Command 'php' from package 'php'
 Command 'pick' from package 'pick'
 Command 'pil' from package 'picolisp'
 Command 'zip' from package 'zip'
 Command 'ip' from package 'termux-tools'
 Command 'ping' from package 'termux-tools'
$
_______________
i am on termux pip3 doesnt work and i cant download python3

**Comment by sTiKyt** [comment]
@KingMhamad install python-pip3 package...

**Comment by KingMhamad** [comment]
$ apt install python-pip3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-pip3
$ pkg install python-pip3
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:3 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Hit:3 https://dl.bintray.com/xeffyr/x11-packages x11 Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-pip3
$
____________________
doesnt work 😢

**Comment by KingMhamad** [comment]
i guess nothing works then :(

**Comment by sTiKyt** [comment]
@KingMhamad Linux repository... I mean
Arch linux, Ubuntu, Kali Linux, Manjaro, Linux Mint or what?

**Comment by KingMhamad** [comment]
i am on termux i didnt change anything i just clone scripts and tools and testing them and try to learn the python language by looking inside the file and try to learn somthing

**Comment by KingMhamad** [comment]
About the linux repo i guess it is kali linux or something linux. lol

**Comment by sTiKyt** [comment]
... I'm very sorry man but can you please delete linux and install Windows? This just not for you..
Sorry again @KingMhamad

**Comment by tokiijnr** [comment]
pls i have the same issue with 

$ apt install python-pip3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-pip3

**Comment by tokiijnr** [comment]
i am using kali linux rolling

**Comment by sTiKyt** [comment]
@tokiijnr i used Kali only once in my life but, can't it be `apt-get install python-pip3`?

**Comment by usama7628674** [comment]
@tokiijnr It's `apt install python3-pip`
