### ISSUE TITLE
Facebook`s websites seems broken

### ISSUE THREAD

**Issue by Bartixxx32** [DarkSecDevelopers/HiddenEye#198]

**Comment by sTiKyt** [comment]
#99 #27

**Comment by jepunband** [comment]
facebook page & facebook messenger is broken.

**Comment by usama7628674** [comment]
@jepunband I'll update pages starting from tomorrow.

**Comment by darkmidus** [comment]
Is there any webpages that need to be updated

**Comment by Ldog8315** [comment]
darkmidus I can help you with that tomorrow after we get home

**Comment by usama7628674** [comment]
@darkmidus @Ldog8315 Are you two brothers?

**Comment by darkmidus** [comment]
@usama7628674 No, we're just good friend's of each other

**Comment by usama7628674** [comment]
@darkmidus So you two live close to each other.

**Comment by Ldog8315** [comment]
@usama7628674 yeah we go to the same school

**Comment by Ldog8315** [comment]
Sorry this is kinda random but we should make an irc channel to talk through ik its ancient, but its pretty secure XD

**Comment by usama7628674** [comment]
@sTiKyt @jepunband @Bartixxx32 Fixed.Pull latest commit and try again.

**Comment by jepunband** [comment]
Ok thanks. Will try again.

**Comment by jepunband** [comment]
hey guys fb messenger & fb page are good. Only the loopback option "Leave Blank To Loop The Phishing Page" does not work..

thanks.
