### ISSUE TITLE
Ngrok Syntax Error

### ISSUE THREAD

**Issue by jepunband** [DarkSecDevelopers/HiddenEye#202]
hi after selecting ngrok and choosing custom domain i get this error..
![screenshot at 2019-02-05 23-29-28](https://user-images.githubusercontent.com/46950575/52284270-0c098480-299f-11e9-82a5-68b26d6cdbef.png)

./Server/ngrok: 1: ./Server/ngrok: Syntax error: "(" unexpected

**Comment by An0nUD4Y** [comment]
@jepunband  , I am Unable to reproduce this error, Can You Give Me More Info...  OR Try again with the instructions.md command guide.

**Comment by deepufeliz** [comment]
ngrok  won't create any link. how to fix this issue ?

**Comment by jepunband** [comment]
OK got it to work by doing "chmod 755 ngrok" in the HiddenEye/Server folder.
