### ISSUE TITLE
SSH ERROR: Broken pipe...

### ISSUE THREAD

**Issue by ilija02** [DarkSecDevelopers/HiddenEye#203]
Whenever i try to use serveo as my host i get the following error
![untitled](https://user-images.githubusercontent.com/45182003/52424601-a3371f00-2afa-11e9-8550-b644108d7059.png)
I provided a good redirect url : www.instagram.com and whatever i use for the custom subdomain the error still proceeds to show

**Comment by An0nUD4Y** [comment]
@ilija02  , Let me know what are you using as custom subdomain...

**Comment by ilija02** [comment]
![untitled](https://user-images.githubusercontent.com/45182003/52427266-ee9ffc00-2aff-11e9-87b2-aaa2120866c5.png)
I also tried using just exampledomain123 (wihout the serveo.net domain) but i get the same error.
Also when i try to connect to serveo manually via ssh with this command ssh -R **exampledomain123.serveo.net:80:localhost:8888 serveo.net** i get the follwing error packet_write_wait: Connection to 159.89.214.31 port 22: Broken pipe

**Comment by An0nUD4Y** [comment]
@ilija02 , Try It Without , Custom URL.. 
Use this command..
`ssh -R 80:localhost:1111 serveo.net`

**Comment by An0nUD4Y** [comment]
@ilija02  CHECK IF THESE ANSWERS CAN HELP YOU TO RESOLVE THE ISSUE.
[CHECK HERE](https://unix.stackexchange.com/questions/2010/what-does-the-broken-pipe-message-mean-in-an-ssh-session)
OR
[CHECK HERE](https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection) 
Try To Find The Solution On various Forums , Some Have Mentioned Above.

**Comment by ilija02** [comment]
I can't seem to fix the problem, maybe it happens because I'm on a VM. I'll try bridged mode on my network adapter for my virtual machine.

**Comment by ilija02** [comment]
I solved the problem. Solution is to change the network adapter from NAT to bridged mode, because ssh will not work if two devices share the local ip.
