### ISSUE TITLE
NAmeError: name 'log' is not defined

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#204]
![image](https://user-images.githubusercontent.com/35602029/52477251-ec927780-2ba9-11e9-9be5-27a7cf355342.png)

**Comment by sTiKyt** [comment]
Seems like "sudo" fixed this problem...

**Comment by m0caa** [comment]
so how, where, and when do we put sudo?

**Comment by usama7628674** [comment]
@m0caa sudo python3 HiddenEye.py
