### ISSUE TITLE
No such file: server/www/index.html

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#205]
![screenshot from 2019-02-08 20-23-06](https://user-images.githubusercontent.com/5570136/52504202-9d673980-2bdf-11e9-88f8-fb3601cad54f.png)
    why this error

**Comment by sTiKyt** [comment]
@lordcharlx what page you tried to use?

**Comment by An0nUD4Y** [comment]
@lordcharlx  plz check  #195 ....
Always Check For Previous Closed Issues, To Find If Your issue were already solved or not.

**Comment by lordcharlx** [comment]
gmail

**Comment by jepunband** [comment]
> gmail

This is already working..
