### ISSUE TITLE
Serveo is Not Working

### ISSUE THREAD

**Issue by unknwn404** [DarkSecDevelopers/HiddenEye#206]
Serveo Is Not Working.

Script Stoped Automaticaly

Give This Out Put
Insert a custom subdomain for serveo

CUSTOM Subdomain>>> rabbyyyy

FAILED !!!...FAILED !!!..FAILED !!!

[!] Please Make Sure:
 1)~ If You are still connected to the Internet.
 2)~ If You Have Chosen A Valid Custom URL.
     As Serveo Implemented More Security To Stop misuse of the service.
 3)~ You Can Give another Try.

SCRIPT STOPPED !!

**Comment by lordcharlx** [comment]
try another sub domain!

**Comment by Knowledge-Wisdom-Understanding** [comment]
What is the proper syntax for the CUSTOM Subdomain for serveo?
https://examplesite.com OR www.example.com OR example OR examplesite.serveo.net
I can't get Serveo to work. Do we have to register the subdomain first or can it be anything that we make up? I haven't used Serveo very much. Any advice would be much appreciated.
Ngrok works perfectly though.

**Comment by CptJoker** [comment]
same issue with me i tired all subdomains still now working please help 

Thanks in Advance :)
