### ISSUE TITLE
Cannot install pip3

### ISSUE THREAD

**Issue by Ldog8315** [DarkSecDevelopers/HiddenEye#209]
Whenever I put in sudo apt install python3-pip I get the error

E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by usama7628674** [comment]
@Ldog8315 Go to task manager of your linux and kill packagekitd
