### ISSUE TITLE
--help base

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#210]
I'll use Argparse to make help system.

**Comment by usama7628674** [comment]
Remember argparse is used mostly for tools that use flags to run not for ui style scripts.

**Comment by sTiKyt** [comment]
@usama7628674 now i'm not sure about UI, we really need it?
I mean, there nothing hard that must have UI to be user-friendly.

**Comment by usama7628674** [comment]
@sTiKyt The tools that run only if flags are given as arguments not for this tool cuz it's streamline and more of a UI style.What would you put as argument cuz it's not a tool that just you can run by giving arguments for example `python Hiddeneye.py here you assin argument as a flag like --help`.

**Comment by sTiKyt** [comment]
Done
