### ISSUE TITLE
How to fix expired ngrok link?

### ISSUE THREAD

**Issue by krblood00** [DarkSecDevelopers/HiddenEye#211]
![screenshot at 2019-02-16 21-58-24](https://user-images.githubusercontent.com/47693145/52900998-565cf200-3238-11e9-9e6d-c61867cba706.png)
It was working yesterday but now I have no idea how to fix this problem. Can you help me?
For future users whom will encounter this error as well.

long live darksec

**Comment by usama7628674** [comment]
Ngrok won't work continuously for hours you've to generate or run hiddeneye again after some hours.I think serveo will work for longer period of time.

**Comment by krblood00** [comment]
Oh, but still I don't know what to do . Even if I do generate a new one; it gives me the same link thus this will appear.

**Comment by krblood00** [comment]
i think the problem is my HiddenEye stopped generating new links(Probably)?. I never touched the files tho

**Comment by sTiKyt** [comment]
@krblood00 just wait, we'll help you as soon as possible!

**Comment by krblood00** [comment]
will do sir thank you for the response.

**Comment by Crewxx** [comment]
Having same issue as well, and am finding it difficult setting up serveo to work properly. Please help

**Comment by Mokruy** [comment]
same problem

**Comment by sTiKyt** [comment]
This not a problem, just restriction of free version of Ngrok.
Sorry :\

**Comment by dhananjay1438** [comment]
Then how to get rid of it?
