### ISSUE TITLE
Fix 11 Compatibility issues in WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#227]
[CodeFactor](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/overview/master) found multiple issues:

#### The property -moz-appearance is compatible with -webkit-appearance and should be included as well.
[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:139
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L139)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:166
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L166)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:173
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L173)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:2605
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L2605)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:5868
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L5868)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:7190
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L7190)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:7332
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L7332)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:7407
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L7407)
#### The property -ms-transform is compatible with -webkit-transform and should be included as well.
[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:6269
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L6269)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:6275
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L6275)[WebPages\Instagram_autoliker\assets\css\cssv2\bootstrap.css:6282
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/WebPages/Instagram_autoliker/assets/css/cssv2/bootstrap.css#L6282)

**Comment by sTiKyt** [comment]
@An0nUD4Y i don't know how to use css and html dude, i'm only python beginner

**Comment by usama7628674** [comment]
not a problem just using css property for mozilla and microsoft browsers.Closing
