### ISSUE TITLE
Server Ngrok Syntax Error 

### ISSUE THREAD

**Issue by abigail24** [DarkSecDevelopers/HiddenEye#249]
hi guys,
followed the installation as per instructions. Installation was successful. During the choosing of the servers ;
1.ngrok
2. serveo

on choosing ngrok i get this error:

./Server/ngrok: 1: ./Server/ngrok: Syntax error: "(" unexpected

I also followed a closed solution here #202 which did not work. 

I'm using Kali Linux - 3.4.0 - Nethunter

**Comment by An0nUD4Y** [comment]
@abigail24  Please try again with new commits , clone again..

**Comment by An0nUD4Y** [comment]
No Response .... So closing here.
