### ISSUE TITLE
Github Page not Proper.

### ISSUE THREAD

**Issue by arghyadipchak** [DarkSecDevelopers/HiddenEye#250]
The Github Page appearing in the Attack is not ok.
Please change the index.html file in the /WebPages/Github
I have already done it in the file below.
Please replace it if you like.

[index.zip](https://github.com/DarkSecDevelopers/HiddenEye/files/2888890/index.zip)

**Comment by usama7628674** [comment]
I'll fix it.

**Comment by usama7628674** [comment]
@arghyadipchak Resolved.
