### ISSUE TITLE
Service Not Available Error!!

### ISSUE THREAD

**Issue by voldemort1912** [DarkSecDevelopers/HiddenEye#251]
**Describe the bug**

**To Reproduce**
1. Followed the Installation Steps
2. Instagram Phishing
3. Selected yes to IPLogger
4. Selected Serveo as Domain added subdomain etc...
5. Eroor

**Expected behavior**
Expected the Program to execute successfully, Give me a subdomain and well...do it's jon

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 8.0 Oreo
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 5 SM N9208
 - OS: Android 8.0 Ported from SM N935
 - Browser N/A
 - Version N/A

**Comment by usama7628674** [comment]
Please attach screenshot

**Comment by sTiKyt** [comment]
@voldemort1912 Describe the bug please...

**Comment by voldemort1912** [comment]
![screenshot_20190222-151735_termux](https://user-images.githubusercontent.com/47709143/53271843-a3980280-3715-11e9-8563-000d0c31f339.jpg)
@usama7628674 @sTiKyt

**Comment by voldemort1912** [comment]
P.S. ngrok works fine though!! But I need to use Serveo as it allows me to have a custom Subdomain

**Comment by An0nUD4Y** [comment]
Solved clone It Again...

**Comment by actooalizame** [comment]
This issue isn't resolved yet.

Cloned the latest version and still got the error on the attached screen capture.

![cap-bug-hiddeneye](https://user-images.githubusercontent.com/11241403/53375102-4fb13780-3928-11e9-9092-4d8d6fa0ced3.png)

**Comment by jepunband** [comment]
Yeah this issue happens with serveo after generating the link. I opened this issue b3fore but it was closed by @sTiKyt

**Comment by usama7628674** [comment]
I'll peep into it later.

**Comment by An0nUD4Y** [comment]
@actooalizame , @voldemort1912 , Please Clone with latest commits... I have removed The tinyurl , But Later It will be added...???

**Comment by actooalizame** [comment]
@An0nUD4Y OK fixed now!

Clone + git commit 392a970  solved Serveo issue.

Thank you!
