### ISSUE TITLE
Ngrok is not downloading

### ISSUE THREAD

**Issue by llegall924** [DarkSecDevelopers/HiddenEye#255]
Used both versions, for termux and not, same error. Tried to delete `checkNgrok()` and moved nrok file to Server and Defs folders. Root is working also
![error](https://user-images.githubusercontent.com/48101408/53588251-b186d100-3bb6-11e9-8a5d-07e311f26390.JPG)

**Comment by An0nUD4Y** [comment]
@llegall924 I will check for it... wait sometime

**Comment by An0nUD4Y** [comment]
@llegall924 you have cloned the master branch , for termux their is another branch available , please clone that branch.
[TERMUX BRANCH HERE](https://github.com/DarkSecDevelopers/HiddenEye/tree/Termux-Support-Branch)

**Comment by ioi2908** [comment]
still experiencing the same problem in ubuntu 18.04
