### ISSUE TITLE
NEED HELP !! NEW TEMPLATE

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#257]
@sTiKyt @usama7628674 
Check this blog, https://blog.trendmicro.com/trendlabs-security-intelligence/how-a-hacking-group-is-stealing-popular-instagram-profiles/

This is the currently active phishing campaign, 
Lets add this template to our tool, 
Here is the currently active phishing link
https://instagrambluetick[.]ml

I have uploaded the template script , but as i don't have enough time , i can't configure them to use ...
 I am uploading these template to my drive , Hope You guys will add the
Uploaded Zip Here : -> https://drive.google.com/open?id=15c_YGb6t1IqPQUHD_8WUunO5EF7dETpv

I hope you guys will add it...

**Comment by An0nUD4Y** [comment]
Check This Active Phishing Campaign : https://instagrambluetick.ml
I am waiting for Reply...

**Comment by An0nUD4Y** [comment]
OK Guys I have Added this..

**Comment by usama7628674** [comment]
@An0nUD4Y Where did you add it I can't see any new commit?
