### ISSUE TITLE
doesnt accept any subdomains

### ISSUE THREAD

**Issue by root1825** [DarkSecDevelopers/HiddenEye#260]
maybe something has gone wrong on the installation or i dont know why this tool isnt acceptting  any url

![screenshot from 2019-03-05 18-25-13](https://user-images.githubusercontent.com/26313436/53805453-61bc5700-3f74-11e9-8f69-28295f6d6d41.png)
![screenshot from 2019-03-05 18-25-31](https://user-images.githubusercontent.com/26313436/53805455-61bc5700-3f74-11e9-91f4-f08d9525ee52.png)
![screenshot from 2019-03-05 18-25-13](https://user-images.githubusercontent.com/26313436/53805473-6c76ec00-3f74-11e9-8bf7-cc4b8d0d6529.png)

**Comment by sTiKyt** [comment]
Try without serveo.net...
