### ISSUE TITLE
servers failure and options not working

### ISSUE THREAD

**Issue by ashu021** [DarkSecDevelopers/HiddenEye#261]
**Describe the bug**
I tested the script for two - three days,A great idea but is having some issues that i found,Firstly the servers is a big failure in this,I read many issues related to servers errors,In my opinion you should be adding an option of self choosing of server.Secondly you can add the options of fake mails,So that the  link  generated by the script  and servers to become more sophisticated and by this it look more real,and become easy for users to work around.And also found errors related to file management,I have attached the screenshots as well.

**To Reproduce**
1. In my case i specifically used Instagram option  ''
2. I entered the options provided for Instagram.
3. you can see how the servers responds.

**Expected behavior**
The servers should open the phishing page approximately with the same time  as of original sites to look real,and when I tried with my device I was not able to login in there , if I am forwarding this link to anyone then as a user ,I want that the person should able to login only then i will be able to get the keystrokes from the keylogger that what i understood.

**Screenshots**
![screenshot from 2019-03-06 07-37-38](https://user-images.githubusercontent.com/30325189/53852801-3fb0ec00-3fe9-11e9-92f2-17de0b2894b1.png)
![screenshot from 2019-03-06 07-16-12](https://user-images.githubusercontent.com/30325189/53852823-50f9f880-3fe9-11e9-9525-97f45eda9282.png)

**Desktop ():**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [52.9.0]

**Smartphone ():**
 - Device: [Oneplus 5]
 - OS: [android 9]
 - Browser [stock browser,chrome]
 - Version [71]

**Comment by sTiKyt** [comment]
@ashu021 thanks for your feedback! We'll analyze and fix problems soon.

**Comment by usama7628674** [comment]
@ashu021 You aren't using https are you?

**Comment by ashu021** [comment]
@usama7628674 yeah i am using https.

**Comment by ashu021** [comment]
@sTiKyt yeah thank you,looking forward for your reply.

**Comment by An0nUD4Y** [comment]
@ashu021  Check the latest updates...

**Comment by ashu021** [comment]
@An0nUD4Y i will check the update for sure.

**Comment by sTiKyt** [comment]
@An0nUD4Y Please release simmilary with me, you make mistakes
