### ISSUE TITLE
Fix 1 Security, 1 Maintainability issues in Defs\Actions.py

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#262]
[CodeFactor](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye) found multiple issues last seen at 7b0ef39a601ec8efd3f24c1c5ad2f4f663c85a28:

#### subprocess call with shell=True seems safe, but may be changed in the future, consider rewriting without shell
[Defs\Actions.py:179
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/Defs/Actions.py#L179)
#### Unnecessary pass statement
[Defs\Actions.py:354
](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye/source/master/Defs/Actions.py#L354)

**Comment by sTiKyt** [comment]
@An0nUD4Y

**Comment by ashu021** [comment]
@sTiKyt @An0nUD4Y the bug is still not resolved
![screenshot from 2019-03-08 10-34-24](https://user-images.githubusercontent.com/30325189/54008717-e930e280-418d-11e9-9579-d55fc449f4b6.png)

**Comment by ashu021** [comment]
@sTiKyt there is also a permission error for the log.

**Comment by An0nUD4Y** [comment]
@sTiKyt , Please give some time to manage the errors and bugs, I am currently a lot busy with my schedule... PLEASE TAKE A LOOK ... I will be thankfull to you.

**Comment by sTiKyt** [comment]
@ashu021 i told you what to do, try to use SUDO

**Comment by An0nUD4Y** [comment]
Closing issue, as latest version v.0.2.6 has got fixed these issues...
Reopen if still have any doubts...
