### ISSUE TITLE
permission and log file error

### ISSUE THREAD

**Issue by ashu021** [DarkSecDevelopers/HiddenEye#263]
![screenshot from 2019-03-08 10-43-02](https://user-images.githubusercontent.com/30325189/54009002-20ec5a00-418f-11e9-82a2-a92b79823fba.png)

**Comment by An0nUD4Y** [comment]
@ashu021 , Please use sudo to run.. Check [instructions](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md)

**Comment by An0nUD4Y** [comment]
@sTiKyt , Please take a look here, i am currently busy..

**Comment by sTiKyt** [comment]
I'm not sure, probably we can't create this file cause app were used without sudo?

**Comment by sTiKyt** [comment]
@ashu021 please try to use "sudo python3 HiddenEye.py"
if problem solved - please close this issue.

**Comment by sTiKyt** [comment]
Also your app may be outdated, please update it to latest release.

**Comment by An0nUD4Y** [comment]
No response ... Closing. You can reopen anytime.
