### ISSUE TITLE
Help with HiddenEye

### ISSUE THREAD

**Issue by BrokeTerror69** [DarkSecDevelopers/HiddenEye#264]
When I try to run python3 HiddenEye.py, I get a traceback error saying that wget is not installed when it is. I have found that it is in python2.7 and not python3. When I try to do sudo apt install python3-pip, I get another error saying python3-pip cannot be located. Any help would be greatly appreciated.

**Comment by Crewxx** [comment]
Learn how to make simple install before loging complaint. Use python3.7 as command and if error persist then check your python installation properly

**Comment by tchach0** [comment]
hi bro
I try all step one by one 
but in finally link of scama not run or show to me 
can you help me plz

**Comment by BrokeTerror69** [comment]
As I wrote this when I was extremely tired, I am closing the issue and opening a new, more descriptive one.

**Comment by tchach0** [comment]
sorry I have taken all the steps I have taken but at the final stage to get the sites sent to the victim I do not see

**Comment by tchach0** [comment]
Keep the blank-free black links not showing I have only a black screen

**Comment by sTiKyt** [comment]
@tchach0 create issue...
