### ISSUE TITLE
ngrok and serveo don't work

### ISSUE THREAD

**Issue by k3rn3l-p4n1c1** [DarkSecDevelopers/HiddenEye#267]
Hey,

at first thanks for offering this nice project.

The main problem I'm facing is, that neither ngrok or serveo service are working.

Are you working on a fix?

Thank You!

**Comment by k3rn3l-p4n1c1** [comment]
Seems like serveo.net is offline, no wonder why this service isnt working. But ngrok doenst work as well.

**Comment by sTiKyt** [comment]
@k3rn3l-p4n1c1 can you please fill issue using template?

**Comment by usama7628674** [comment]
@k3rn3l-p4n1c1 Serveo is now online and ngrok is also working.
