### ISSUE TITLE
Blank screen after selecting proxy service

### ISSUE THREAD

**Issue by NEXUS2345** [DarkSecDevelopers/HiddenEye#273]
When attempting to run the application, once you select the proxy service you wish to use, you are greeted by a blank terminal screen.

1. Run script and proceed through as normal till proxy selection
2. Select proxy
3. Blank terminal screen

I expected to be given a link to be able to access my local instance of HiddenEye via the proxy service selected.

Screenshots: https://imgur.com/a/Tbel3lL

**Desktop (please complete the following information):**
 - OS: Parrot Rolling 64 bit in VMWare Workstation Pro 15
 - Browser: Firefox
 - Version [e.g. 22]: Latest commit (cloned direct) and release 0.2.5

**Comment by astr0naut421** [comment]
I have the same problem. Helppppp!

**Comment by k3rn3l-p4n1c1** [comment]
Same problem here, use Serveo instead of ngrok, should fix the problem temporary.

**Comment by sTiKyt** [comment]
@NEXUS2345 we'll fix it as soon as possible! As you can see this just pre-release, we not released stable version yet.

**Comment by vishalpc2018** [comment]
same problem.please fix it as soon as possible.

**Comment by An0nUD4Y** [comment]
Will be fixed in next release.. Thank you.. Wait for version 0.2.6 to be released..
