### ISSUE TITLE
Localized version of Facebook Standard Page

### ISSUE THREAD

**Issue by k3rn3l-p4n1c1** [DarkSecDevelopers/HiddenEye#274]
**Describe the solution you'd like**
Instead of the english localized Facebook standard page, I liked to have a way to choose different languages.

Maybe it is possible to swap the linked content in the index.html to change the language of the webpage?

Thanks a lot for all your efforts.

**Comment by sTiKyt** [comment]
Sounds good but we don't have enough employees to do cool things like this
We have people to keep app in stable status but we add other features really slow
