### ISSUE TITLE
dear thank for the project but it not work with me it give a blank page 

### ISSUE THREAD

**Issue by pretech86** [DarkSecDevelopers/HiddenEye#277]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sTiKyt** [comment]
@pretech86 why you posted bug as feature request? -_-
We know about this bug, everyone have this problem now because of ngrok and serveo problems.
We will fix it as soon as possible.

**Comment by sTiKyt** [comment]
#273
