### ISSUE TITLE
HIDDENEYE

### ISSUE THREAD

**Issue by rootroota1** [DarkSecDevelopers/HiddenEye#278]
Hi guys 
After I cloned HiddenEye in my Linux, I tried to run “python3 HiddenEye.py” but it pops an error in network. It shows exactly like “network error; confirme your connection”
Help

**Comment by An0nUD4Y** [comment]
@rootroota , check closed issues... And please don't be lazy , it's what it is saying... Check your internet connection.

**Comment by rootroota1** [comment]
![2F1882BC-32F7-4A80-8D0D-9F2A285074B4](https://user-images.githubusercontent.com/45772333/54745063-b220ef00-4bd9-11e9-9125-b46e04cc4734.jpeg)

**Comment by sTiKyt** [comment]
@rootroota1 probably you don't have internet connection or not able to reach google.com

**Comment by kreiter200** [comment]
Same issue :/

**Comment by Duplic8e** [comment]
same issue but my internet is working fine

**Comment by sithuna** [comment]
How to do this error. help me someone. I'm start useing termux
Traceback (most recent call last):
  File "HiddenEye.py", line 20, in <module>
    checkPermissions()
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 60, in checkPermissions
    raise PermissionError("{0}Permissions denied! Please run as '{1}sudo{0}'".format(RED, GREEN))
PermissionError: Permissions denied! Please run as 'sudo'

**Comment by sTiKyt** [comment]
@sithuna create new issue please.
