### ISSUE TITLE
Any Kalilinux Phising tools currently not worked

### ISSUE THREAD

**Issue by vishalpc2018** [DarkSecDevelopers/HiddenEye#280]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootroota1** [comment]
Shellphis works form me

**Comment by An0nUD4Y** [comment]
@rootroota1 , it's better if you let us know the issues you are facing.

**Comment by Alien-Virus** [comment]
Is Theresa any problema with Linux O.S's? Neither Kali nor Parrot or Termux pentesting os working. Ngrok doesn't run green. Can't use blackeye, hiddeneye nor socialfish. Help me...

**Comment by rootroota1** [comment]
Use Shellphish,  it's working

**Comment by Alien-Virus** [comment]
Why my ngrok doesn't run green on termux. What's wrong with my phone?
Please Help me.


A segunda, 1/04/2019, 00:07, Roota <notifications@github.com> escreveu:

> Use Shellphish, it's working
>

**Comment by sTiKyt** [comment]
@Alien-Virus seems like Ngrok problem, we'll fix it as soon as possible

**Comment by sTiKyt** [comment]
#273

**Comment by Alien-Virus** [comment]
Termux is asking to run HiddenEye sudo but when i do ir doesn't workshop.

I've already tried the following cores:
sudo ./HiddenEye.py
tsudo ./HiddenEye.py
tsu ./HiddenEye.py.

What more shall i do?

**Comment by sTiKyt** [comment]
@Alien-Virus you should install TERMUX EDITION, please read README.md
