### ISSUE TITLE
Ngrok or server dont work

### ISSUE THREAD

**Issue by uran86** [DarkSecDevelopers/HiddenEye#281]
When choosing ngrok or server nothing happens.
Everything else work, but it does not create any links.

I removed it and installed it again, still the same thing.

![Skärmbild från 2019-03-23 17-30-22](https://user-images.githubusercontent.com/11734119/54871365-32398700-4d89-11e9-9be7-678b06ec6b0b.png)

Any idés why?

**Comment by An0nUD4Y** [comment]
#273 .. its a bug, we will resolve it as soon as possible.

**Comment by uran86** [comment]
How is it going bro, with fixing the bug?

**Comment by sTiKyt** [comment]
#273
