### ISSUE TITLE
git clone https://github.com/DarkSecDevelopers/HiddenEye fatal: destination path 'HiddenEye' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by panime** [DarkSecDevelopers/HiddenEye#282]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by An0nUD4Y** [comment]
@panime , Try to clone in other directory. Or delete the old cloned before cloning new.
