### ISSUE TITLE
Serveo link down after one try, and Ngrok is not generating link 

### ISSUE THREAD

**Issue by mimou1340** [DarkSecDevelopers/HiddenEye#283]
Serveo link die after one try ..
Please fix it to be stable .
Thanks am loving the tool so far.. Especially the ability to custom links and redirects..
The only problem is that the link die quickly..

**Comment by An0nUD4Y** [comment]
@mimou1340 ,
I will fix it as soon as possible.

**Comment by S1lkys** [comment]
I have the Problem too, it creates serveo links but they dont work like they dont show anything. Ngrok does not even generates a link

**Comment by An0nUD4Y** [comment]
I am working hard to get fix these issues...

**Comment by amroytb** [comment]
Hey bro @An0nUD4Y thankyou for your hard work, i still can't generate link with ngrok or serveo server. 
I select **instagram** phishing and then i follow your steps to type this command _"(./Server/ngrok http 1111)"_ but, i have 502 Bad Gateway on my ngrok server. Can you help me to fix my problem ?

**Comment by An0nUD4Y** [comment]
Guys try this latest Released v.0.2.6 ,
I have fixed most of link down issues, 
Closing Now , Feel free to Reopen whenever need ....
