### ISSUE TITLE
HiddenEye doesn't start

### ISSUE THREAD

**Issue by SomeRandomPigeon** [DarkSecDevelopers/HiddenEye#284]
Basically when i want to start up HiddenEye it only gives me a traceback, even though i installed the requirements. I start HiddenEye with python3, as i should. Please help!

**Comment by usama7628674** [comment]
@SomeRandomPigeon How did you install requirements with pip or pip3?

**Comment by SomeRandomPigeon** [comment]
Hey there!, i tried with both installation

Usama Abdul Sattar <notifications@github.com> ezt írta (időpont: 2019. ápr.
1., H, 4:01):

**Comment by usama7628674** [comment]
@SomeRandomPigeon Please post screenshot of error here.It's very hard to debug without any info.

**Comment by strejfz** [comment]
PermissionError: Permissions denied! Please run as 'sudo'
 What i need to doo?

**Comment by usama7628674** [comment]
@strejfz Are you using termux on android?If you're then please clone termux branch or head over [here](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md#running-for-android-users-in-termux) for complete installation of Hiddeneye on termux.

**Comment by strejfz** [comment]
@usama7628674  can you add me on ig strafe.exe im going to send you ss

**Comment by An0nUD4Y** [comment]
@strejfz , please share screenshot here ,

**Comment by An0nUD4Y** [comment]
Please , clone again the script...
Open again if still found these issues.. 
As we have solved them in latest release v.0.2.6

**Comment by rootroota1** [comment]
Hey guys help me on this as well...  Am I missing something?

**Comment by ash1271999** [comment]
i get error of permission denied please use sudo what should i do

**Comment by sTiKyt** [comment]
You should install Special Termux-dedicated branch!

**Comment by ash1271999** [comment]
what can you send me a link of some video or something so i am clear

**Comment by usama7628674** [comment]
@ash1271999 Please read here https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md#2-installing-in-termux-app

**Comment by Nikhil-ls** [comment]
Permissions denied! Please run as sudo next
