### ISSUE TITLE
ngrok.url

### ISSUE THREAD

**Issue by craziestsaint** [DarkSecDevelopers/HiddenEye#285]
I'm a windows user, after managing to setup the ngrok and other stuff.on getting to the end i get a message ngrok.url not found how can i fix this.
![ngrok](https://user-images.githubusercontent.com/49193217/55397966-3f2e4700-54fc-11e9-9fdf-8865621afb0b.PNG)

**Comment by usama7628674** [comment]
@craziestsaint It is not for windows.

**Comment by craziestsaint** [comment]
Can I run it on cygwin ?

**Comment by usama7628674** [comment]
@craziestsaint Maybe try it out.

**Comment by sTiKyt** [comment]
@craziestsaint just try

**Comment by sTiKyt** [comment]
@usama7628674 Lol, same message -_-
