### ISSUE TITLE
Suggestions to make this tool even better

### ISSUE THREAD

**Issue by AbitathaRoy** [DarkSecDevelopers/HiddenEye#286]
Dear Developers,
It's Abitatha Roy, a computer enthusiast.
I have tested many phishing tools and came up with the issue which prevails over all tools. Suppose, when we create our own local server using the ngrok tool, the link remains active unless it is manually terminated or our computer is shut down.
However, for tools like this one, the links are active for a very short time after which they terminate automatically. The link also terminates when one node or computer has already accessed and used the link.
Why does this happen only in case of phishing tools? I do not have any knowledge regarding this, so if anyone of you from the developers side can pick me up and explain this to me, then it's going to be very useful.
Finally, could you, the developers do something to fix this drawback of the tool? I hope for the best. And I wish I would hear back from you, for all I want at this moment is to learn.
Thank You.
[Note: Link terminates only on Xubuntu XFCE, not on Kali Linux KDE. In addition to this, ngrok is not working.]

**Comment by An0nUD4Y** [comment]
Hey abitatha, thanks to share your views about this tool, we will make it more realistic , wait few weeks..

**Comment by YInMn-xPL01T** [comment]
Not sure if you want suggestions here. But more options such as PlayStation or other gaming platforms would make this application 100x much better. Once I saw it had secure links I fell in love. Great build. Hope to see big updates soon!

**Comment by An0nUD4Y** [comment]
@YInMn-xPL01T , Always Ready to listen suggestions, Updates are comming soon... I will also try to add playstation or some gaming platform phishing... just give me the names of those websites..

**Comment by An0nUD4Y** [comment]
Closing it to get consider some other important issues
 Open it again whenever you want

**Comment by pretech86** [comment]
@AbitathaRoy can you tell me please whish phishing tool you used because i searched more and more finding only hieddin eye the most proffessional one >> 
thanks a lot and sorry to interrupt you
