### ISSUE TITLE
IP address 'bogon' issues.

### ISSUE THREAD

**Issue by KnightSec-Official** [DarkSecDevelopers/HiddenEye#290]
**Describe the bug**
Everything works but when i put the creds into the page it gets me this error...

**To Reproduce**
1. Start the tool
2. Instagram
3. take ngrok link and acces it
4. Type username and password(for test) and error occurs

**Expected behavior**
Expected to work perfectly... When i remove the IP scripts from credget() it works fine

**Screenshots**
I send via phone
**Desktop (please complete the following information):**
 - OS: MAC OS High Sierra
 - Browser: Safari
 - Version: last

**Additional context**
I think its from me but idk

**Comment by An0nUD4Y** [comment]
I will try to reproduce & fix it , Thanks to share,,,

**Comment by deadfishhackers** [comment]
why dont u wanna close it @An0nUD4Y ?

<img src="https://pasteboard.co/IfAPmwN.png">

**Comment by sTiKyt** [comment]
@deadfishhackers maybe because we don't close issues until they are not solved?!

**Comment by KnightSec-Official** [comment]
i found it.... it happens because somehow i copyed a part of the tool wrong.... on the get ip module and get creds... i reversed them... for me it would get ip after the creds.... and after the creds... the txt file with the ip would be deleted.... so i solve it.... thank you for the patience
