### ISSUE TITLE
linked page not working well 

### ISSUE THREAD

**Issue by pretech86** [DarkSecDevelopers/HiddenEye#295]
.thanks for your efforts but i face this problem the linkedin page not working well 
![hiddeneye error](https://user-images.githubusercontent.com/46816468/56459559-f4d31400-639d-11e9-85fe-9e529761ff82.jpg)

**Comment by usama7628674** [comment]
@pretech86 It'll be fixed in coming days.

**Comment by pretech86** [comment]
Really thanks for your interest and your efforts also please try to fix facebook problem it not working also .. i think millions of people wait you 
Thanks a lot

**Comment by johnny21212** [comment]
hey my computer can't open sudo, so i don't know how to download Hidden Eye

**Comment by tokiijnr** [comment]
hey the icloud page is also not displaying correctly

**Comment by sTiKyt** [comment]
@johnny21212 @tokiijnr please create detailed issues, don't reply here or i'll block conversation as offtopic.
P.s. Thank you :3

**Comment by deadfishhackers** [comment]
> hey my computer can't open sudo, so i don't know how to download Hidden Eye

@johnny21212 

Are u running the script on termux?

**Comment by sTiKyt** [comment]
@deadfishhackers @johnny21212 please create NEW ISSUE if you want to talk about it.

**Comment by An0nUD4Y** [comment]
#569
