### ISSUE TITLE
Failed to listen on 127.0.0.1:1111

### ISSUE THREAD

**Issue by S1lkys** [DarkSecDevelopers/HiddenEye#298]
**Describe the bug**
When ngrok or serveo tries to get a url it fails and it displays:" Failed to listen on 127.0.0.1:7650 (reason: Address already in use). I tried to change the port and killed all services but after restarting HiddeEye it displays it again. It generates links but these have no content/ displa

y nothing"

**To Reproduce**
1. Start Hiddeneye
2. Select one Option
3. Add no Keylogger
4. insert costum url
5. select Ngrok or serveo

**Expected behavior**
Phishing Page gets displayed

**Screenshots**
NGROK:
![Bildschirmfoto von 2019-04-21 17-48-59](https://user-images.githubusercontent.com/40408435/56472355-e1877d80-645d-11e9-89aa-18e302303566.png)

SERVEO:
![Bildschirmfoto von 2019-04-21 17-52-37](https://user-images.githubusercontent.com/40408435/56472387-4216ba80-645e-11e9-9b92-bcda246f328d.png)

**Desktop (please complete the following information):**
 - OS: Linux kali 4.19.0-kali4-amd64
 - Browser Firefox

**Comment by An0nUD4Y** [comment]
@S1lkys , Try to kill port 1111 on localhost, use this command .
' fuser -k 1111/TCP '

**Comment by S1lkys** [comment]
@An0nUD4Y nope nothing it says the Specified filename 1111/ TCP does not exist.

**Comment by S1lkys** [comment]
you can close it if you want i had to edit my host file to 127.0.0.1 localhost
in kali 127.0.0.1 points to kali @ default. thx for taking time for me anyway :)

**Comment by pretech86** [comment]
@S1lkys can you tell me how you edit your localhost to 127.0.0.1 only to silve this problem 
thanks a lot

**Comment by S1lkys** [comment]
In kali: 
nano /etc/hosts

127.0.01 localhost

**Comment by evanotone** [comment]
@S1lkys can you solve the error?
