### ISSUE TITLE
credential color 

### ISSUE THREAD

**Issue by pretech86** [DarkSecDevelopers/HiddenEye#300]
thanks for this tool 
can you make the color of the credential green instead of red .. thanks a lot 

also can i use the tool 2 sites or more than 2 at same time ? 

best regards

**Comment by An0nUD4Y** [comment]
@pretech86 , ok i will change the colour for credentials..
Off course you can use two attacks simultaneously, but for that you have to make some changes in script ...
1)- Make another copy of Hiddeneye ,
2)- In the copied Hiddeneye goto defs folder you will find actions.py file their .. 
3)- Just change all 1111 values with any other value like 4321 or 1234 or 4444 anything you like, it will just change the port to be used, as 1111 port is default port which is currently currently running in first attack , So you have to need a different port for that , by doing this you can run multiple attacks simultaneously , but you can only use serveo , as ngrok does provide multiple connections at once for free.. so use serveo instead.


Hope it will help you.
Let us know if it doesn't works, may be if I forget something...

**Comment by pretech86** [comment]
thanks for your kindly interest
