### ISSUE TITLE
instagram is not still working even your updated vesrsion

### ISSUE THREAD

**Issue by 8755245756** [DarkSecDevelopers/HiddenEye#302]
i am still getting tunnel not starting error while hoating instagram phising page and also get a new issue that your local host is already running on this 127.0..0.1:1111 ...
please chceck the issue and provide some solution

**Comment by 8755245756** [comment]
i will be very thankfull to you if you fixed that issue as soon posiible

**Comment by An0nUD4Y** [comment]
@8755245756 , As I have already mentioned in solved issues that Ngrok do not allows multiple requests at once and stops connection, try serveo instead..
As Instagram page built to be not detected by browsers so it uses its own files to host , So need a multiple requests at once to completely load the page which is not possible with Ngrok..


And the second issue is a bug. I  don't have enough time to fix that...
I will try to fix this as fast as possible... Thanks to put your issues here.

I am closing ...
You can reopen it anytime...

**Comment by An0nUD4Y** [comment]
Please check #305 for issue "localhost already running"

**Comment by 8755245756** [comment]
thankss for answering but in my internet isp provider may blocked serveo.net
:( :( syd lyf
