### ISSUE TITLE
work as a real page 

### ISSUE THREAD

**Issue by pretech86** [DarkSecDevelopers/HiddenEye#303]
when the victim enered any user name and any password and also when the victim hit login without write any usename or password he can go direct to the redirect redirect page 

is there any method to force him enter the correct user name or password ? i mean , we not let him entered to the redirect page until put his username and password correctly > isit possible ?

thanks for your efforts

**Comment by usama7628674** [comment]
We can check both field if they are empty the page won' t redirect untill both fields are filled.I've did that for snapchat page

**Comment by pretech86** [comment]
How we can make this ?

**Comment by usama7628674** [comment]
@pretech86  [Here](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/WebPages/Snapchat_web/login.php) it is for snapchat.I haven't yet implemented for other webpages.

**Comment by An0nUD4Y** [comment]
@pretech86 i think it should work, 
Just add ( required  )
In any web page where the input boxes are available 
Like below example from instagram verified badge attack, 
As here we put a tag " required " , so now the user cannot leave it empty before submitting..


name="password" type="password" value="" required></div>

**Comment by usama7628674** [comment]
@pretech86 Like @An0nUD4Y said it can also be done by just putting required in input tag however there are various ways you can also write javascript or php script to achieve that.

**Comment by pretech86** [comment]
Sorry , i just a beginner what i understand i shall edit the web page in hidden eye and put required .... can you explain more please by steps .. sorry to interrupt you 

Also can you add it to the tool code directly ? 
Thanks for your efforts with us

**Comment by An0nUD4Y** [comment]
@pretech86 , Just goto Hiddeneye folder and then webpages folder and search for the template you want to use...
Then just edit the index.html file on that template , 
Just put " required " tag at appropriate places as mentioned above .. and save it .. then launch Hiddeneye and select the attack you have modified.. 
And all done , may be now it's clear to you...

**Comment by pretech86** [comment]
Thanks a lot it clear now
