### ISSUE TITLE
No internet connection?

### ISSUE THREAD

**Issue by argtje99** [DarkSecDevelopers/HiddenEye#304]
HiddenEye shows me this error after i run python3 HiddenEye.py

_  _ . ___  ___  ___ _  _  ___ _  _ ___                     |__| | ]  | ]  | |__ |\ |  |__ \__/ |__                     |  | | ]__| ]__| |__ | \|  |__  ||  |__                       [!] ^Network error^. Verify your Internet connection.                                                         root@kali:~/HiddenEye# 

I tried on 4G and on WiFi. Same error

**Comment by usama7628674** [comment]
I'll fix it.This is a known issue.

**Comment by An0nUD4Y** [comment]
@usama7628674 
Please mention the bug here , I m unable to get it.

**Comment by usama7628674** [comment]
@An0nUD4Y There's no bug here we just need to come up with a more feasible method to check for internet.I'll make necessary changes.

**Comment by usama7628674** [comment]
@argtje99 Please do `git pull` or reclone the tool again.

**Comment by usama7628674** [comment]
@argtje99 Please do `git pull` or reclone the tool again.

**Comment by argtje99** [comment]
Still the same error ! @usama7628674

**Comment by usama7628674** [comment]
@argtje99 Are you using the tool on termux?

**Comment by argtje99** [comment]
Google is not blocked in my region (Netherlands). I use HiddenEye on Kali Nethunter

**Comment by usama7628674** [comment]
Well it's working here for me in pakistan.Wai t I'll take a look tomorrow.

**Comment by An0nUD4Y** [comment]
@argtje99 try to ping https://google.com

**Comment by argtje99** [comment]
@An0nUD4Y ping works fine.

**Comment by An0nUD4Y** [comment]
@argtje99 , until we figure it out .
You can use script by modifying Defs/checks.py file...
Or just put some other domain their like remove www.google.com and put www.duckduckgo.com or any other domain.

But it's not important that the script will generate link as serveo or Ngrok needs to be get connected to internet.

**Comment by An0nUD4Y** [comment]
@argtje99 Please upload the screenshots..

**Comment by argtje99** [comment]
@An0nUD4Y I tried the change from google to duckduck. Same error.

**Comment by argtje99** [comment]
@An0nUD4Y I bypassed the check connection. Now I get this error ![](https://i.imgur.com/kYI4Yjx.png)
![](https://i.imgur.com/JbY5OKQ.png)

**Comment by argtje99** [comment]
@An0nUD4Y bypassed the check connection. Now this error occurs

![](https://i.imgur.com/GJ91wJX.png)![](https://i.imgur.com/NAbGlLf.png)

**Comment by An0nUD4Y** [comment]
@argtje99 Try to install Termux again , I think Their is some network configuration issues.

**Comment by argtje99** [comment]
@An0nUD4Y I have nethunter installed in chroot. I reinstalled it 3 times. Still same error

**Comment by usama7628674** [comment]
@argtje99 Do you have resolvconf installed.Navigate to /etc and check for resolv.conf file.Install `apt install net-tools` then use `ifconfig` to check for ip and see if you're connected to internet.

**Comment by argtje99** [comment]
@usama7628674 I will install another version of Nethunter. I was using the nightly version which always worked fine. I try a stable version now.

**Comment by argtje99** [comment]
Its a error in SSL certificate. I will try to find the problem and report it here.

**Comment by argtje99** [comment]
@usama7628674 @An0nUD4Y Downgraded. Now it works like a charm without any issues. The SSL certification error has to do with Python2.7.

**Comment by tokiijnr** [comment]
i have the same issue:

        _  _ . ___  ___  ___ _  _  ___ _  _ ___
        |__| | ]  | ]  | |__ |\ |  |__ \__/ |__
        |  | | ]__| ]__| |__ | \|  |__  ||  |__

          [!] ^Network error^. Verify your Internet connection.


root@kali:~/Downloads/HiddenEye#

**Comment by tokiijnr** [comment]
google is not blocked in my region

**Comment by argtje99** [comment]
@tokijnr what device do you use?

**Comment by argtje99** [comment]
This error shows up because the ssl certificates cant be verified. That's why HiddenEye shows up no connection. Its an Python error

**Comment by tokiijnr** [comment]
i use kali linux
but ive been able to fix that then i get a new issue saying:

HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "HiddenEye.py", line 10, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'

**Comment by tokiijnr** [comment]
> This error shows up because the ssl certificates cant be verified. That's why HiddenEye shows up no connection. Its an Python error

i just recloned it fom git

**Comment by sTiKyt** [comment]
@tokiijnr just remove Settings.ini

**Comment by tokiijnr** [comment]
thanks so much it worked

**Comment by sTiKyt** [comment]
@tokiijnr you're welcome! That was my bug -_-
