### ISSUE TITLE
Failed to listen on 127.0.0.1:1111 (reason: Address already in use)

### ISSUE THREAD

**Issue by cahyosh** [DarkSecDevelopers/HiddenEye#305]
Failed to listen on 127.0.0.1:1111 (reason: Address already in use)

How to resolve this problem?

**Comment by An0nUD4Y** [comment]
@cahyosh , This is a known bug,
 You can resolve it by these steps..
(1) After completing the Script  (Do not close) . Open another terminal & Follow these commands.
(2) fuser -k 1111/tcp    (This will kill the port 1111 which is running)
(3) Goto the HiddenEye/Server/www location in cloned folder.Follow below command.
(4) cd HiddenEye/Server/www
(5) Now run php server from here with port 1111. Follow below command.
(6) php -S 127.0.0.1:1111 > /dev/null &
(7) Now you have done , Just recheck the Serveo link in browser , it should work..

Let us know if it works or not....

**Comment by usama7628674** [comment]
@cahyosh It's fixed do `git pull` or reclone it again.

**Comment by cahyosh** [comment]
Thank you for your help, i will try, i hope it can resolve this problem. Thank you master @An0nUD4Y

**Comment by 8755245756** [comment]
thankss for answering but in my internet isp provider may blocked serveo.net
:( :( syd lyf
