### ISSUE TITLE
Great UPDATE

### ISSUE THREAD

**Issue by cahyosh** [DarkSecDevelopers/HiddenEye#306]
Great i love you udy.
I just type git pull on HiddenEye directory. And its working well.

**Comment by usama7628674** [comment]
@cahyosh Thanks for letting us know.

**Comment by An0nUD4Y** [comment]
@cahyosh , Thank you buddy..
Its all Here because I got a little time to spend for my joy..

**Comment by cahyosh** [comment]
Good luck for everything bro
