### ISSUE TITLE
Link not being generated.

### ISSUE THREAD

**Issue by ZULFICHUPPZ** [DarkSecDevelopers/HiddenEye#307]
HiddenEye doesnt give the phishing page link after the last update

Commands i use
./HiddenEye.py
1  facebook (error occur everywhere)
Redirect link : www.facebook.com
Subdomain : www.facebok.com
2 Serveo
Shows an empty screen *Error*

I have all these pkg installed (dont mind if not necessery)
wget python2 python php perl ruby proot

 oppo a7

![Screenshot_2019-04-27-00-04-54-16](https://user-images.githubusercontent.com/33788669/56829458-63720f00-6881-11e9-82e3-84129cfb3c41.png)

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , Try to create a custom URL from serveo , and upload screen snapshot.

**Comment by ZULFICHUPPZ** [comment]
![Screenshot_2019-04-27-00-21-20-05](https://user-images.githubusercontent.com/33788669/56829883-84872f80-6882-11e9-8936-05ee92e1272d.png)
![Screenshot_2019-04-27-00-21-33-55](https://user-images.githubusercontent.com/33788669/56829892-8c46d400-6882-11e9-8358-1e72c8ddfaf2.png)
 
There is even error showing in custom url

**Comment by ZULFICHUPPZ** [comment]
@An0nUD4Y 
I got this strange comment and when i hit enter it got normal...is that any problem
![Screenshot_2019-04-27-00-20-55-44](https://user-images.githubusercontent.com/33788669/56830000-cf08ac00-6882-11e9-9780-5fe2ea44b3c2.png)

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , Dude you cannot create a Domain facebook.com with serveo , 
Try just typing anything random like "facepics" or anything misspelled..

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , Please read all the tags in script.. its not an error it's just to take back on wrong typing ..

**Comment by ZULFICHUPPZ** [comment]
@An0nUD4Y Bro its facebok.com anyway i will try another it doesnt matter....same error

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , take a screenshot..

**Comment by ZULFICHUPPZ** [comment]
![Screenshot_2019-04-27-00-31-52-83](https://user-images.githubusercontent.com/33788669/56830444-f8760780-6883-11e9-88d3-21347a7afde5.png)
![Screenshot_2019-04-27-00-32-08-18](https://user-images.githubusercontent.com/33788669/56830463-04fa6000-6884-11e9-8872-b786c2ea084c.png)
Same comments are shown

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , bro try this in another terminal and give me it's result..
ssh -R 80:localhost:1111 serveo.net

**Comment by ZULFICHUPPZ** [comment]
![Screenshot_2019-04-27-00-40-47-68](https://user-images.githubusercontent.com/33788669/56830884-37f12380-6885-11e9-93a9-c8c0311bf5fb.png)
![Screenshot_2019-04-27-00-41-16-29](https://user-images.githubusercontent.com/33788669/56830894-3de70480-6885-11e9-9843-26fa22d687f4.png)
@An0nUD4Y Done, pls check i have no clued

**Comment by ZULFICHUPPZ** [comment]
![Screenshot_2019-04-27-00-43-05-02](https://user-images.githubusercontent.com/33788669/56830960-771f7480-6885-11e9-9955-af2cde072323.png)
@An0nUD4Y The link generated doesnt work

**Comment by ZULFICHUPPZ** [comment]
L

**Comment by ZULFICHUPPZ** [comment]
Sorry unknowingly closed the issue

**Comment by usama7628674** [comment]
@ZULFICHUPPZ Okay I know the problem is type `pkg install openssh` then `pkg install readline`.After that it'll not throw Cannot link executable 'php'.

**Comment by ZULFICHUPPZ** [comment]
@usama7628674 @An0nUD4Y Hey it worked perfectly....and the session do stay for hours and doesnt time out either. Thanks a lot guys for your marvelous hardwork and contribution...hatsoff bros

**Comment by saharbabaei777** [comment]
It's the same problem about the link generated doesn't work after 30 minutes!!! Even install open ssh and readline!!! Please help me how can i get a link without timeout?!

**Comment by usama7628674** [comment]
@saharbabaei777 Go to ngrok site sign up/sign in the put auth key.That will increase timeout.
