### ISSUE TITLE
Instagram head tag incomplete 

### ISSUE THREAD

**Issue by ZULFICHUPPZ** [DarkSecDevelopers/HiddenEye#308]
There is no letter 'm' of INSTAGRAM showing in mobile view, in instagram verification page, but it shows normal in desktop view.
I use oppo a7 
Screen resolution : 360 × 640 pixel
![Screenshot_2019-04-27-09-19-59-09](https://user-images.githubusercontent.com/33788669/56844471-40ba1780-68ce-11e9-8321-fcb9496c3cef.png)
![Screenshot_2019-04-27-09-20-06-32](https://user-images.githubusercontent.com/33788669/56844472-46aff880-68ce-11e9-8dea-68d55b286340.png)

**Comment by deadfishhackers** [comment]
kind of strange you all have problems with termux, do a fresh install and try again

**Comment by sTiKyt** [comment]
@deadfishhackers noone told termux it or no, @ZULFICHUPPZ  we'll figure out how to fix that as soon as possible.

**Comment by deadfishhackers** [comment]
@sTiKyt they do go through closed and opened issues

**Comment by deadfishhackers** [comment]
@sTiKyt close this issue, its BootStrap issue

**Comment by An0nUD4Y** [comment]
@ZULFICHUPPZ , I will fix that logo in next updates.. 
Currently ,I'm closing here...

**Comment by deadfishhackers** [comment]
@An0nUD4Y dude its easy to fix this issue, but it will fuck up the web

**Comment by sTiKyt** [comment]
@An0nUD4Y don't close issues if they are not solved yet please, thank u :3

**Comment by An0nUD4Y** [comment]
#569 , We may fix it later.
