### ISSUE TITLE
sudo on termux

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#309]
how to fix run HiidenEye.py with sudo
![Screenshot_20190427-111651](https://user-images.githubusercontent.com/5570136/56848561-7f59cd00-68e2-11e9-94a5-2579cff8f0d2.jpg)

**Comment by usama7628674** [comment]
@lordcharlx We've removed termux support but you can still use it on an android device.Readme is updated so head over there and read about it to use it on android.

**Comment by An0nUD4Y** [comment]
@usama7628674 , i think we should not suddenly remove Termux Branch, as working on termux is more easy for a beginner than that of UserLand..

So we can add termux branch and can also support UserLand at the same time , by which it will also not that much difficult to maintain. 
I Hope you will satisfy with these reasons.

**Comment by usama7628674** [comment]
@An0nUD4Y Did you use userland app?If you did then tell me how hard is it for a noob to set up for the first time?Termux is crap you ngrok takes a helluva time to connect and every few days new issues start to occur.You know userland only takes 10-15 minutes to set up.I did that last night and got impressed by it.Still if you insist I'll restore termux branch.

**Comment by An0nUD4Y** [comment]
@usama7628674 , I have tried it , and i know it's not that hard for a noob , but believe me Termux is quick & fast to setup.
I supports UserLand , but we should also support Termux-Branch At the same time. I hope we can do that , Don't Remove the changes , just add some more lines in readme & instructions For android's second option to install ...
I hope You will support , & Its always nice to see some new changes ...
Thanks to add UserLand Support...

**Comment by sTiKyt** [comment]
@An0nUD4Y i think you can support termux if you want to. Because this is freedom of opensource.

**Comment by deadfishhackers** [comment]
install **Kali** shell in termux a better choice

**Comment by sTiKyt** [comment]
@lordcharlx So, solved?

**Comment by skinnylx** [comment]
> @lordcharlx We've removed termux support cuz maintaining both branches are difficult so now only one branch can do the job for linux and android users but you can still use it on an android device.Readme is updated so head over there and read about it to use it on android.Read [here](https://github.com/DarkSecDevelopers/HiddenEye#whats-new-features) and [here](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md#running-for-android-users)

I still don't understand
