### ISSUE TITLE
Generated link time out

### ISSUE THREAD

**Issue by saharbabaei777** [DarkSecDevelopers/HiddenEye#311]
Same problem about the link generated doesn't work!!!
Even i install openssh and readline!!!
Please help me how can i get a link without timeout?!

**Comment by usama7628674** [comment]
@saharbabaei777 see this https://github.com/DarkSecDevelopers/HiddenEye/issues/307#issuecomment-487964701

**Comment by saharbabaei777** [comment]
Ngrok doesn't work! When i choose ngrok hidden eye stoped
Is there any way to use serveo keep alive without timeout?!

**Comment by deadfishhackers** [comment]
provide more information @saharbabaei777

**Comment by gurutylor07** [comment]
How do I get hiddeneye to run.  On my Android  . I have termux installed and other tools.  It's saying  run sudo.   But sudo is not downloading

**Comment by gurutylor07** [comment]
Secondly  once I exit  my termux the phishing page dies

**Comment by deadfishhackers** [comment]
@gurutylor07 sudo is for Kali linux not for android, its pretty hard to install `sudo` command cause it works only on NetHunter, as @usama7628674 mentioned he removed support from termux and other terminal mobile emulator apps, ill see if i can fix it but it is probably your phone, and turn wakelock on, on termux.

Thanks!
Sincerely DarkSec Support team
