### ISSUE TITLE
Facebook Phishing Page

### ISSUE THREAD

**Issue by kingmoe001** [DarkSecDevelopers/HiddenEye#312]
I tricked my friend with the phishing page with his permission. He gave his credentials to the false page.
I didn't sign in to his account. 
Couple of minutes later he was locked out of his own Facebook.
How could this have happened?
Did someone else receive his credentials?

**Comment by usama7628674** [comment]
@kingmoe001 Did you receive his credentials?

**Comment by deadfishhackers** [comment]
this happens because, Facebook detected someone log-into his account, didn't u try to log in?

**Comment by An0nUD4Y** [comment]
@kingmoe001, Closing , due to no response... 
You can open again anytime.
