### ISSUE TITLE
instagram fake follow / unfollow Error

### ISSUE THREAD

**Issue by omer-raif** [DarkSecDevelopers/HiddenEye#313]
![2019-05-02 19-47-11 ekran görüntüsü](https://user-images.githubusercontent.com/50047969/57093003-73706f80-6d15-11e9-9f40-e523a8f08b88.png)
That's the mistake I've encountered. I also have the same error in Termux and Userland.)

**Comment by An0nUD4Y** [comment]
@omer-raif , Their is instafollower webpages directory missing , wait i am uploading...

**Comment by An0nUD4Y** [comment]
Solved...
