### ISSUE TITLE
Ngrok downloading again and again in Userland

### ISSUE THREAD

**Issue by ArunDinfinity** [DarkSecDevelopers/HiddenEye#314]
**Describe the bug**
HiddenEye in userland OS Ubuntu , whenever I start the HiddenEye using the command
sudo python3 HiddenEye.py
It's checks for ngrok installation and always downloading ngrok even ngrok already downloaded..

**To Reproduce**
Start HiddenEye in userland Ubuntu
**Expected behavior**
Downloading the same file again and again
**Screenshots**
![Screenshot_20190503-001006](https://user-images.githubusercontent.com/41442211/57098492-dc68df00-6d37-11e9-9aa9-3e27c56e9835.jpg)
**Desktop (please complete the following information):**
 - OS Android Oreo 8
 - Browser [chrome]
 - Version [ 8 ]
**Smartphone (please complete the following information):**
 - Device: [e.g. Honour 7X]
 - OS: [e.g. android Oreo 8.0]
 

**Additional context**
N/A

**Comment by omer-raif** [comment]
I think it's not a big problem

**Comment by usama7628674** [comment]
@ArunDinfinity Fixed reclone it again.

**Comment by ArunDinfinity** [comment]
Okay
