### ISSUE TITLE
no internet connection.

### ISSUE THREAD

**Issue by deadfishhackers** [DarkSecDevelopers/HiddenEye#315]
_  _ . ___  ___  ___ _  _  ___ _  _ ___
        |__| | ]  | ]  | |__ |\ |  |__ \__/ |__
        |  | | ]__| ]__| |__ | \|  |__  ||  |__

          [!] ^Network error^. Verify your Internet connection.

**Comment by deadfishhackers** [comment]
Fixed ^^, had to change Defs/Checks.py from https://google.com to yandex.ru 


Explanation for people who want to know:

I changed the servers to closest ones, because my country got internet expensive and lowered the price which made people buy routers and decreased the internet speed

**Comment by sTiKyt** [comment]
@deadfishhackers not everyone can use yandex.ru, for example Ukrainians can't use it because yandex was blocked

**Comment by deadfishhackers** [comment]
@sTiKyt i know read that again, i said i changed it to nearest servers

**Comment by sTiKyt** [comment]
I see, my mistake

**Comment by antisecurity** [comment]
I have fixed  all issues on running hiddeneye with nethunter😱. See here the latest comments #329 Network Error || Android || Nethunter

**Comment by usama7628674** [comment]
@antisecurity Very well can you make pull request so that we can fix this issue?

**Comment by antisecurity** [comment]
Ok. I will make it

**Comment by usama7628674** [comment]
@antisecurity I've added it no need for PR now.

**Comment by antisecurity** [comment]
Ok
All right, I am sorry bacuse I couldn't write you soon. Bye


ср, 7 авг. 2019 г., 9:47 Usama Abdul Sattar <notifications@github.com>:

**Comment by lordcharlx** [comment]
![Screenshot at 2020-02-06 21-36-15](https://user-images.githubusercontent.com/5570136/73976511-c3293a80-4928-11ea-8afc-23548390a35f.png)
same issue

**Comment by lordcharlx** [comment]
my internet is super fast

**Comment by priyanshu-1232** [comment]
Bruh how can I change google.com to yandex.ru

**Comment by 04anubhavv** [comment]
https://www.youtube.com/watch?v=5Vb8AWFXbSM
