### ISSUE TITLE
e-mail and password convincing

### ISSUE THREAD

**Issue by raif-py** [DarkSecDevelopers/HiddenEye#316]
Hi, I had a development idea . Social networks like Facebook Instagram Twitter are not looking at the password length or the authenticity of the email . It also accepts non- @ e-mails and passwords smaller than 6 digits . If you make such an adjustment (yes I am aware that this would be too grueling ) you will already jump to the top of the top phishing program 10 steps . What would you say ?

**Comment by usama7628674** [comment]
@omer-raif What user or victim writes in a username and password field it is captured irrespective of password length or numbers and emails without @.There's no such limitation if any site has then it's the default nature of site being built with certain limitation.We're not limiting here.

**Comment by omer-raif** [comment]
for example, if the password is less than 6 characters, give a warning there?

**Comment by usama7628674** [comment]
@omer-raif Why does facebook has limitation of setting password?

**Comment by omer-raif** [comment]
I think it's very important in terms of credibility . When I try, the victims enter the e-mail and type a password that is smaller than 6 digits (for example, ASDF) and realize that the site is fake . Of course, for purely testing purposes. :d

**Comment by omer-raif** [comment]
For example, please enter this site and try to continue without putting @ in the email address. It would be nice to add a warning like HiddenEye
https://anttiviljami.github.io/browser-autofill-phishing/ (its browser-autofill-phishing test page)
And my example (its Turkish)
![2019-05-05 16-16-41 ekran görüntüsü](https://user-images.githubusercontent.com/50047969/57194629-a9019c80-6f51-11e9-97cb-18263edd1258.png)

**Comment by usama7628674** [comment]
@omer-raif But you can also log in to facebook with number no @ needed so how can I force the user to write @

**Comment by sTiKyt** [comment]
@usama7628674 just ask users for @ when they have any letters and don't ask for it when user enter digits.

**Comment by deadfishhackers** [comment]
@sTiKyt i can edit the files for autocomplete and send it to you if you want to

**Comment by sTiKyt** [comment]
@deadfishhackers just create pull request and we will review it, thanks :3

**Comment by deadfishhackers** [comment]
I will
