### ISSUE TITLE
Adding Inception-Bar Attack

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#317]
@usama7628674 @sTiKyt  , Guys in last few ago I worked to add Inception-bar attack.
But still unable to fix some errors and logics. As i am busy now , I can't keep it continue , So I am uploading the unfinished work here , You have to only check for Action.py inception functions , and the PNG images of address bars are available at (webpages/INCEPTION-BAR ) .
 
Please fix it and release it as v0.2.8

Here is the Files :  https://bit.ly/inceptionbar

I HOPE YOU WILL TAKE A LOOK ..
ASK ME IF NEED HELP .. 
I DID A LOT OF SHIT THEIR..
I HOPE YOU GUYS WILL FIX .

**Comment by omer-raif** [comment]
Link dead

**Comment by An0nUD4Y** [comment]
Wait , a min. i m uploading again..

**Comment by An0nUD4Y** [comment]
Here is the Link :- http://bit.ly/inceptionbar

**Comment by omer-raif** [comment]
![2019-05-04 19-43-15 ekran görüntüsü](https://user-images.githubusercontent.com/50047969/57182165-e9571100-6ea4-11e9-8d96-fa42ecf2f664.png)

**Comment by An0nUD4Y** [comment]
@omer-raif , that's why I asked for help , as I don't have much time to figure out issues....

**Comment by ArunDinfinity** [comment]
Can I ask a question offtopic , does a paid SMTP server send email to the
victim inbox even if it's a html script based email?
Or any ways to send a Spoofed email With html script to inbox?

**Comment by omer-raif** [comment]
I wish I knew Python's software language and helped you . but unfortunately :(

**Comment by usama7628674** [comment]
@An0nUD4Y Okay just an indentation problem could be fixed in a couple of minutes.I'm currently busy this week will look into it next week.

**Comment by usama7628674** [comment]
@An0nUD4Y So I studied inception-bar phishing method and it's very limited.The phishing trick works on Android phones but only in chrome browser. iOS users remain safe since the Chrome for iOS continues to display the URL bar.I think google will mitigate it in the coming days so I don't think it's worth a time to work on this method.It does not work on windows pc only in chrome for android.I think it's a waste of time.

**Comment by ArunDinfinity** [comment]
Nah it will be not ,since it's a latest method if we can work it out
HiddenEye will get lot of promotion also mostly there are android users
than pc or iOS users .

**Comment by usama7628674** [comment]
@ArunDinfinity  But google will fix this bug sooner or later.

**Comment by An0nUD4Y** [comment]
@usama7628674 , You are right buddy, Google will fix it as early as possible, but we should remember that the tool is made for learning purpose, so I think it's a good attack , people should be aware of such attack , and that can happen only when we made it easy to launch this attack even for script kiddies. 
As We Know , 
ATTACKING IS THE BEST DEFENCE..

I hope , you will fix issues, and please add some comments , so that users can understand when to add this attack and when should not..
Thanks buddy

**Comment by An0nUD4Y** [comment]
Please Give Response...guys

**Comment by sTiKyt** [comment]
@An0nUD4Y sorry, have no time to help with it

**Comment by deadfishhackers** [comment]
when will you add it?

**Comment by deadfishhackers** [comment]
nvm

**Comment by sTiKyt** [comment]
@deadfishhackers i can't help because now i have lot of exams, other guys probably busy this month too..
Then we'll work more intensively

**Comment by An0nUD4Y** [comment]
@deadfishhackers @sTiKyt  I am also busy a lot. I will add it whenever got time...

**Comment by deadfishhackers** [comment]
@sTiKyt ill try to work on it
<hr>
<p align="middle"><img src="http://i63.tinypic.com/qxjwd1_th.png"></p>
