### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#318]
**Is your feature request related to a problem? Please describe.**
Ability to change color scheme. You will be able to create your very own look for whole app without breaking it.

**Describe the solution you'd like**
User should be able to select theme by its name.

**Additional context**
I'll do it when will have enough of free time.

**Comment by An0nUD4Y** [comment]
@sTiKyt , You are Right bro .. Try to add this also if you can ... Learn and test as much as you can.

**Comment by sTiKyt** [comment]
@An0nUD4Y stable minimal versione done already! I'll optimize and improve it later!

**Comment by sTiKyt** [comment]
https://github.com/DarkSecDevelopers/HiddenEye/commit/a892d1b73f9d3fee1f474af3993b0275e0fd37b1

**Comment by An0nUD4Y** [comment]
@sTiKyt , Please update readme , For these changes .

**Comment by sTiKyt** [comment]
@An0nUD4Y i will, but i have to implement 1 more console command

**Comment by sTiKyt** [comment]
@An0nUD4Y added small info about it.
