### ISSUE TITLE
Instagram Phishing option 5

### ISSUE THREAD

**Issue by kingmoe001** [DarkSecDevelopers/HiddenEye#319]
Traceback Error: 
Traceback (most recent call last):
  File "HiddenEye.py", line 27, in <module>
    mainMenu()
  File "/root/Desktop/HiddenEye/Defs/Actions.py", line 308, in mainMenu
    runPhishing('Instagram', customOption)
  File "/root/Desktop/HiddenEye/Defs/Actions.py", line 76, in runPhishing
    copy_tree("WebPages/instafollowers/", "Server/www/")
  File "/usr/lib/python3.7/distutils/dir_util.py", line 127, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree 'WebPages/instafollowers/': not a directory

**Comment by sTiKyt** [comment]
@kingmoe001 are you sure about your copy of app?
Please do one of following:

- Try to copy WebPages/instafollowers manually from[ GitHub repository ](https://github.com/DarkSecDevelopers/HiddenEye/tree/master/WebPages/instafollowers)
- If it seems too hard or you don't have enough time just try to delete HiddenEye folder and install it again from [here](https://github.com/DarkSecDevelopers/HiddenEye.git). (Removing folder not recommended if you are using BlackArch)
- If you are BlackArch repository user please just reinstall app:
`sudo pacman -Syu` **_(You can ignore this one but it's very recommended! Updates local Database)_**
`sudo pacman -R hiddeneye` _**Removes HiddenEye**_
`sudo pacman -S hiddeneye` _**Installs HiddenEye**_

If you have any questions - mention me with @ and i'll help you.

**Comment by sTiKyt** [comment]
This issue will be closed during 15 days if you'll not give me answer.

**Comment by deadfishhackers** [comment]
u can close it already

**Comment by sTiKyt** [comment]
@deadfishhackers i can understand you but we have rules, he have 15 days to respond. (3 more days)

**Comment by An0nUD4Y** [comment]
@kingmoe001 , Closing Here , You can Open it anytime...

**Comment by sTiKyt** [comment]
True, we are waiting for your reopen if that was'nt solved @kingmoe001 
I'll help you with it anytime, just ask!
