### ISSUE TITLE
Becoming 1.0!

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#320]
**Is your feature request related to a problem?(**NO!**)! Please describe.**
I think our app grows perfectly and becomes better and better by time.
We should fix current 10 issues and debug it to release FIRST STABLE RELEASE! 
So, we already had lot of pre-releases but we never released stable version already.

**Describe the solution you'd like**
Do stable release 1.0

**Additional context**
I want to say thanks to every user and every issue-maker!
DarkSec always will be loyal to our community, thank you for help!

**Comment by An0nUD4Y** [comment]
@sTiKyt , You are right buddy , i think it's time for a stable release .. 
But I am currently busy , so I can't help much about it .. But will try my best to get it done..
Thanks @sTiKyt

**Comment by sTiKyt** [comment]
After release we should use DEV BRANCH for everything.
MAIN branch will be used only for stable releases.

**Comment by Moltivie** [comment]
PL (#402 - #400)
