### ISSUE TITLE
Where I can find the output if I use screen?  

### ISSUE THREAD

**Issue by ArunDinfinity** [DarkSecDevelopers/HiddenEye#321]
I used HiddenEye using screen
And where I can find the output obtained ??
After I close the connection

**Comment by sTiKyt** [comment]
@ArunDinfinity dude, please read console next time, ok?
![image](https://user-images.githubusercontent.com/35602029/57264928-94222780-707d-11e9-9ecb-922eb3a740c8.png)

**Comment by ArunDinfinity** [comment]
I already checked it before I ask but didn't find it though I used serveo

**Comment by sTiKyt** [comment]
@An0nUD4Y

**Comment by ArunDinfinity** [comment]
Issue not yet solved I can't get password or username or anything in username.txt 
It's just blank

**Comment by deadfishhackers** [comment]
provide more details

**Comment by sTiKyt** [comment]
@ArunDinfinity you should fill special "Bug" blank and answer all questions, steps to reproduce, etc. This will be closed cause you haven't done it right, thank you :3

**Comment by patrick4real83** [comment]
Hello @Arundinfinity, I ask you to send me those information about setting up Modlishka or evilginx2. Please if you can able to help out as you promise, let deal now. Thanks

**Comment by ArunDinfinity** [comment]
@patrick4real83
Well I did send the email but the owner of Modlishka said it's not trading forum and removed my email😅
pastryelite2@gmail.com

**Comment by ArunDinfinity** [comment]
pastryelite2@gmail.com

**Comment by patrick4real83** [comment]
Hello @Arundinfinity. Check your email.
