### ISSUE TITLE
Problem with google Advanced Phishing(poll_mode/login_with)

### ISSUE THREAD

**Issue by fgbread** [DarkSecDevelopers/HiddenEye#322]
@ANONUD4Y
@usama7628674 
@sTiKyt  
I've been running HiddenEye via termux on my android OS for a while now, good software, but got this kind of problem with Google Advanced Phishing. You know? I launched the tool, chose the Google option 3 (advanced Phishing) ngrok was started and I was provided with a link. The link was copied and pasted on my browser and I all I got was this (see screenshot). Standard page phishing and new google web worked fine.

![Screenshot_20190506-164438](https://user-images.githubusercontent.com/33941236/57239414-60161a80-701b-11e9-81db-9d3b4d41a916.png)

**Comment by fgbread** [comment]
I mean Google option 2 not 3. 
Option 3: New Google web works fine
![Screenshot_20190506-164634](https://user-images.githubusercontent.com/33941236/57239621-e92d5180-701b-11e9-96a7-108ab031a00f.png)

**Comment by usama7628674** [comment]
It is poll method man.This page is designed like this you know poll method nothing wrong.

**Comment by fgbread** [comment]
I got it. Thanks man
