### ISSUE TITLE
I want to contribute to this project.

### ISSUE THREAD

**Issue by psusmit** [DarkSecDevelopers/HiddenEye#324]
I am a noob developer I wanted to contribute to your incredible project.I have cloned standard(traditional) Reddit login page,I want to add just a basic keylogger functionality and credential feature to your system.Before I could do a pull request can I please have a detailed clear-cut way to contribute.
Thanks

**Comment by An0nUD4Y** [comment]
@psusmit , it's easy to contribute .
Just Read the codes , make changes/addition whatever you want ..
Create a PR(pull request) , we will verify and merge, and that's all , 2-3 good PR's are enough to add you to contributers list.

**Comment by An0nUD4Y** [comment]
@psusmit , you can also help us on #317 
Read & leave your comments their...

**Comment by sTiKyt** [comment]
@psusmit also code will be restructured following this rules: https://github.com/DarkSecDevelopers/HiddenEye/wiki/Contributor%3F-Read-please!
So, i recommend to follow it if you're going to write python code.
