### ISSUE TITLE
required for login and check the correct password 

### ISSUE THREAD

**Issue by pretech86** [DarkSecDevelopers/HiddenEye#326]
thanks for this tool , my friend  arranged a standard facebook page to force the victim to put the user name and password kindly can you make the following :

1- make a required for all page like snap chat 
2- force the victime to write the password by message appear ( please write the correct password and username ) 

after writing the first trial of credintial although he written the correct one

**Comment by usama7628674** [comment]
@pretech86 I wrote a php script for snapchat to check both fields for username  and password but it can enhanced to other pages.Currently I don't work on this project but I'll extend it to other webpages when I'll start to work on this project.

**Comment by KnightSec-Official** [comment]
you can do this by javascript.
