### ISSUE TITLE
Old config incompatibility

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#327]
**Describe the bug**
When you update to new version of HiddenEye, app not able to work with your outdated Config.ini

**To Reproduce**
1. Go to official repository
2. Click on download
3. Replace old version of HiddenEye by new

**Expected behavior**
That should be auto-updated

**Additional context**
First update to fixed version always will have this problem, but then it should be compatible with next updates, i'll fix it as soon as possible!

**Comment by uran86** [comment]
There is no need for update, the cleanest way is simply to just remove the resp rm -R Hiddeneye.

1. Reinstall it from github
2. wget==3.2
3. chmod +x Hiddeneye
4. ./Hiddeneye 

And it works.
