### ISSUE TITLE
Failed to display live credentials 

### ISSUE THREAD

**Issue by fgbread** [DarkSecDevelopers/HiddenEye#328]
@sTiKyt
@Usama
I've been testing this software and everything has been fine. I was tryna run it today and something different came up. Using serveo, when victim punches in credentials, IP and login details are shown live
 without having to open the "usernames.txt", but it keeps throwing errors now. I think there is a problem.

OS: android

![Screenshot_20190516-084537](https://user-images.githubusercontent.com/33941236/57838426-3a73d880-77b4-11e9-966f-9cab0583c24d.jpg)

**Comment by fgbread** [comment]
I had to open Username.txt to see the credentials

**Comment by sTiKyt** [comment]
@fgbread we'll figure it out, thank you for your issue!

**Comment by deadfishhackers** [comment]
maybe the ip version was IPv6

**Comment by deadfishhackers** [comment]
@sTiKyt @usama7628674 @An0nUD4Y close all dead issues.

**Comment by usama7628674** [comment]
@fgbread @deadfishhackers Yeah fixed in recent commits.
