### ISSUE TITLE
Network Error || Android || Nethunter

### ISSUE THREAD

**Issue by Vardaan79** [DarkSecDevelopers/HiddenEye#329]
[!] ^Network error^. Verify your Internet connection.

![](https://i.imgur.com/pNlliEA.png)
----

It's showing the above mentioned error. Any fix??

**Comment by deadfishhackers** [comment]
dude ive already opened this issue why didnt u just go through closed issues??

**Comment by deadfishhackers** [comment]
#315 will help

**Comment by deadfishhackers** [comment]
edit "Defs/Checks.py"

Change - https://google.com - to - https://yahoo.com

**Comment by deadfishhackers** [comment]
**From**

def checkConnection(host='**https://google.com'**): #Connection check
    system('clear')
    try:
        urlopen(host, timeout=5)
        print(_("{0}HURRAY!! Internet is available.. We can Continue{1}").format(GREEN, DEFAULT))
        return True

**To**


def checkConnection(host='**https://yandex.ru**'): #Connection check
    system('clear')
    try:
        urlopen(host, timeout=5)
        print(_("{0}HURRAY!! Internet is available.. We can Continue{1}").format(GREEN, DEFAULT))
        return True

**Comment by Vardaan79** [comment]
@deadfishhackers haven't seen that thread, bro. Still, the issue is same. Find the screenshot below -
![](https://i.imgur.com/dQvGlLp.jpg)
![](https://i.imgur.com/VpIHaVT.jpg)

Early response is highly appreciated.

**Comment by Vardaan79** [comment]
An0nUD4Y / deadfishhackers need help.

**Comment by sTiKyt** [comment]
@Vardaan79 please try to set "duckduckgo"

**Comment by deadfishhackers** [comment]
@Vardaan79 

change from yandex.ru to duckduckgo.com maybe that will help

**Comment by deadfishhackers** [comment]
@An0nUD4Y open this issue

**Comment by Vardaan79** [comment]
@sTiKyt @deadfishhackers Tried everything, no luck. :sob:

**Comment by Vardaan79** [comment]
![](https://i.imgur.com/AL4QEMY.jpg)
![](https://i.imgur.com/pYcklEV.jpg)

**Comment by deadfishhackers** [comment]
i think i see the issue, send a screenshot but without drawing all over it

**Comment by sTiKyt** [comment]
@Vardaan79 seems like you have old version of HiddenEye, where I haven't created themes system yet

**Comment by Vardaan79** [comment]
@deadfishhackers : PFB
![](https://i.imgur.com/AR68YgX.png)

@sTiKyt - This is from the latest git. If you think it's an old one. Please share the url of the latest one.

**Comment by deadfishhackers** [comment]
reinstall your termux then retry, waiting for your results :) @Vardaan79 
<img src="https://media.wired.com/photos/5b6e035177a9d822a4642726/master/pass/Identifying-Hackers_REALONE.jpg">

**Comment by sTiKyt** [comment]
@Vardaan79 are u using Termux? Maybe try to use other method for your android!
We have some options!

**Comment by deadfishhackers** [comment]
@sTiKyt no termux is a better option it self, it works good for me on termux!

**Comment by Vardaan79** [comment]
@deadfishhackers Not resolved, even tried with uninstalling the entire Nethunter suite. :pensive:

@sTiKyt yes, using termux. What are the other ways, please suggest. I've tried with termux and Nethunter terminal, both

Waiting for your response.

**Comment by usama7628674** [comment]
@Vardaan79 read this https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md#1-installing-in-userland-app

Try on userland app.For setting that app read this guide https://null-byte.wonderhowto.com/how-to/android-for-hackers-turn-android-phone-into-hacking-device-without-root-0189649/

**Comment by An0nUD4Y** [comment]
@Vardaan79 , Follow @usama7628674 suggestions, or if you still wants to use it in Nethunter/Termux & already tried everything  I want to add 3 more possible ways ,
1)- Try to increase the timeout (same in checks.py ),  To verify connection in slow internet.
2)- Or Replace that link with your localhost address to skip verification (Don't forget to start localhost service first) 
3)- Or you can simply remove " exit(0) "  present above " def checkNgrok() " this will Simply allow script even after error.
4)- Try To just remove the error msg ,  ( just replace ' return False ' with ' return True ' ) But as the script is still not have access to internet , may be the serveo link not generated..

Nearly all are same ..
BUT THESE ALL ARE THE POSSIBLE WAYS YOU CAN TRY.
Waiting For Your response ...

**Comment by deadfishhackers** [comment]
@Vardaan79 if those didnt work as they said try regit installing it, waiting for your reply.
<hr>
<p align="center"><img src="http://i67.tinypic.com/5d6v4y_th.png"></p>

**Comment by sTiKyt** [comment]
@Vardaan79 he already tried, aren't he?

**Comment by Vardaan79** [comment]
@An0nUD4Y - Still, not resolved.
@sTiKyt - Yes, already tried.
@usama7628674 - It's working with Termux but not in Nethunter.

**Comment by usama7628674** [comment]
@Vardaan79 Did it work on userland app?You basically need to install kali on userland app.

**Comment by Vardaan79** [comment]
@usama7628674 I have managed to make it run on Termux. For me, Termux is more preferable. But still not working with Nethunter.

**Comment by jepunband** [comment]
same issuse here on nethunter. [!] ^Network error^. Verify your Internet connection. Using the latest version of hiddeneye.

**Comment by Vardaan79** [comment]
Not working @jepunband

Pfb
 ![](https://i.imgur.com/Xv4p5mv.png)

**Comment by jepunband** [comment]
The code needs to have indentation.(space) at the last 2 lines.

**Comment by Vardaan79** [comment]
@jepunband tried, no luck. Same error.

**Comment by jepunband** [comment]
Screen capture the code you placed here.

**Comment by usama7628674** [comment]
It's indentation problem can be fixed in a couple os seconds.

**Comment by jepunband** [comment]
Yes that is what im trying to tell him.

**Comment by Vardaan79** [comment]
@jepunband PFB,
![](https://i.imgur.com/1q8TRBv.jpg)

Suggest if something else needs to be done here.

**Comment by deadfishhackers** [comment]
reinstall termux or regit the project, ive never had problems with this script it might be your phone :/
@Vardaan79

**Comment by deadfishhackers** [comment]
@sTiKyt @An0nUD4Y or anyone close this issue 12 days without a reply.

**Comment by Vardaan79** [comment]
This is not resolved  :disappointed:

**Comment by deadfishhackers** [comment]
Bro it's same issue on my nethunter terminal, try termux it works on termux
not on nethunter

**Comment by jepunband** [comment]
This issue is resolved.
![Screenshot_20190629-203427](https://user-images.githubusercontent.com/46950575/60384624-bbf89f00-9ab2-11e9-902e-99a38688e4a3.png)
 It is working perfectly .. and yes also on Nethunter!!

**Comment by deadfishhackers** [comment]
Termux emulates real openbsd while nethunter emulates nethunter so, same as
saying android and linux

**Comment by deadfishhackers** [comment]
How did u fix it tho?

**Comment by jepunband** [comment]
Add that short code above..

**Comment by ScrewDSarFi** [comment]
@jepunband how to solve in NETHUNTER please Elaborate

**Comment by ScrewDSarFi** [comment]
@Jepunband please Show me How to fix this Problem

**Comment by antisecurity** [comment]
Yes, Tell us About how did you fix this problem on Termux, please?!

**Comment by antisecurity** [comment]
> @jepunband how to solve in NETHUNTER please Elaborate

Hey, Dears. You know what?. I have fixed this issue
![Uploading Screenshot_20190726-181236_Gallery.jpg…]()

**Comment by antisecurity** [comment]
Here you are. !!! To Fix this issue you have to put following code in HiddenEye.py between" import sys" and *from Defs.Cheks import* 
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
getattr(ssl, '_create_unverified_context', None)):
 ssl._create_default_https_context =  ssl._create_unverified_context
![Screenshot_20190726-181831_ES File Explorer](https://user-images.githubusercontent.com/45734229/61954225-cdf63080-afd1-11e9-9f75-ab64622bce3a.jpg)

**Comment by antisecurity** [comment]
And the result is:
![Screenshot_20190726-182143_NetHunter Terminal](https://user-images.githubusercontent.com/45734229/61954426-452bc480-afd2-11e9-9aaa-0c8d6959f67c.jpg)

Thats all 
Note: don't need to change servers as yandex.ru 😘
 All right. Cheers!!!
