### ISSUE TITLE
Request: reddit phishing page templates

### ISSUE THREAD

**Issue by spmedia** [DarkSecDevelopers/HiddenEye#330]
Adding a reddit phishing page this to would be awesome. reddit is in the middle of a redesign so there are two different versions of it currently. Old an New.

HiddenEye will need to have both the old.* and new.* versions of the login screen.

Old reddit login template: https://old.reddit.com/login
New reddit login template: https://www.reddit.com/login/

**Comment by usama7628674** [comment]
@spmedia Will be added in next version.

**Comment by deadfishhackers** [comment]
@spmedia hm, why do you need old login template?
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by spmedia** [comment]
Because many reddit users still use the old reddit design and URL. The new
redesign and new.* URL is not forced or mandatory on the reddit community
yet.

**Comment by deadfishhackers** [comment]
@spmedia Ok we'll add that later, stay tuned!

<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by usama7628674** [comment]
@spmedia They will be up in a under a week so stay tuned.

**Comment by usama7628674** [comment]
@spmedia Reddit phishing pages completed will upload them tomorrow

**Comment by usama7628674** [comment]
@spmedia Reddit pages added old and new one
