### ISSUE TITLE
Android device huawei p20 pro 

### ISSUE THREAD

**Issue by 07050zero** [DarkSecDevelopers/HiddenEye#331]
Android device huawei p20 pro doesn't download https://github.com/DarkSecDevelopers/HiddenEye.git and also  ( /data/datatech.ula/files/support/dbcliend: Caution,  skipping hostkey check localhost ) eror in my phone cant fixed this problem how can i do it please help ty.

**Comment by An0nUD4Y** [comment]
@07050zero , Upload ScreenShot and provide more info.

**Comment by deadfishhackers** [comment]
give termux storage  permissions, tested it on my phone works perfectly.

**Comment by 07050zero** [comment]
> Android device huawei p20 pro doesn't download https://github.com/DarkSecDevelopers/HiddenEye.git and also ( /data/datatech.ula/files/support/dbcliend: Caution, skipping hostkey check localhost ) eror in my phone cant fixed this problem how can i do it please help ty.

![Screenshot_20190517_230543_tech ula](https://user-images.githubusercontent.com/44039267/57953772-bb88b800-78f9-11e9-8871-cab03aa10f01.jpg)

**Comment by 07050zero** [comment]
> give termux storage permissions, tested it on my phone works perfectly.

workin on termux not a problem, but i want to use it on  userland kali linux system on my android phone.  so there is any command to fix all ?

**Comment by 07050zero** [comment]
> @07050zero , Upload ScreenShot and provide more info.

![Screenshot_20190517_230543_tech ula](https://user-images.githubusercontent.com/44039267/57954064-8c267b00-78fa-11e9-942b-19972b3ce713.jpg)    workin on termux not a problem, but i want to use it on userland kali linux system on my android phone. so there is any command to fix all ?

**Comment by sTiKyt** [comment]
@07050zero you have to install "git" dude.. "Caution" is not an exception, you can try to ignore it.

**Comment by deadfishhackers** [comment]
do  'pkg install git' then show us the results

**Comment by deadfishhackers** [comment]
@07050zero did u solve it yet?

**Comment by 07050zero** [comment]
There is a problem show at like Superuser  dkgn eror dunno what to do

**Comment by sTiKyt** [comment]
Always give us screenshots @07050zero

**Comment by deadfishhackers** [comment]
Show us screenshot, and is your device rooted??

**Comment by exatonix** [comment]
pkg install git 
pkg install coreutils ....
yournpackages is lost.admin is right.then try again.also application manager give stirage permission to termux app in settings menu of your phone

**Comment by deadfishhackers** [comment]
@exatonix hahaha nice you stole all of our ideas and put it in one ;p

<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by exatonix** [comment]
no.ım just read and ı have same problem before you and ı give storage permission and solved.also try insayl tsu and tsudo.

pkg install tsu

pkg install tsudo

ı think your problem is solved

**Comment by deadfishhackers** [comment]
@exatonix he might not have a rooted phone so he will think he has more problems if he does
`pkg install tsu` or or
<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by deadfishhackers** [comment]
@exatonix add me on <a href="http://instagram.com/unoreversecardonceayear">instagram</a><br>
We'll talk there
<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by exatonix** [comment]
delete uour comments on my unnecessry comments.

**Comment by 07050zero** [comment]
ty for all guys

**Comment by deadfishhackers** [comment]
@07050zero Any time!

<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by usama7628674** [comment]
@deadfishhackers Really?
