### ISSUE TITLE
Server Errors ( Disconnecting)

### ISSUE THREAD

**Issue by omer-raif** [DarkSecDevelopers/HiddenEye#332]
Serious disconnetcing. Even if the ngrk site works very badly, it doesn't show the passwords . The serveo custom option sometimes disconnects and fails when trying to connect again :) maybe (instagram adventure attack) index.this is happening because I have customized HTML and I'm really having a disconnection from the link in Guinea . If you want, I can take a video recording...

**Comment by sTiKyt** [comment]
If you need help - take video or screenshots ALWAYS. Thank you :3

**Comment by deadfishhackers** [comment]
hm, a screenshot would be better, if u have customized HTML upload it to <a href="https://uploadfiles.io">here</a> then send us the link

**Comment by KnightSec-Official** [comment]
this happens to me too.... idk if a screenshot matters... but the problem is with serveo.... it disconnects after a minute or 2 if somebody doesnt enter the link
altrough with ngrok... it doesnt ever disconnects.......

**Comment by usama7628674** [comment]
@KnightSec-Official Reclone or `git pull`.I pushed a commit that might fix it.Try it.
