### ISSUE TITLE
unable to establish connection to localhost:1111

### ISSUE THREAD

**Issue by Sanihaa7551** [DarkSecDevelopers/HiddenEye#334]

**Comment by Sanihaa7551** [comment]
even with ngrok and serveo. i am not being able to run the tool succesfully.

**Comment by Sanihaa7551** [comment]
same issue as #170

**Comment by deadfishhackers** [comment]
#174 that might help :)

**Comment by deadfishhackers** [comment]
![image1](https://user-images.githubusercontent.com/37667454/58076000-ed01bd80-7b5d-11e9-98af-d84fdc8a0235.png)

**Comment by Sanihaa7551** [comment]
hi, where exactly can i edit the port number. could you explain further

**Comment by deadfishhackers** [comment]
@Sanihaa7551 its pretty hard to explain, do you have Nginx or Apache2 installed?

<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by Sanihaa7551** [comment]
yes apache2

**Comment by deadfishhackers** [comment]
@Sanihaa7551 i edited my comment go check it

**Comment by Sanihaa7551** [comment]
thank u so much.

**Comment by deadfishhackers** [comment]
@Sanihaa7551 Any time!

<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>
