### ISSUE TITLE
Redirect doesn't work in Instagram Badge Verification page

### ISSUE THREAD

**Issue by c0m94d3** [DarkSecDevelopers/HiddenEye#335]
Option to redirect doesn't work in instagram badge verification attack
So, i found a way to do that just change the index3.html's <meta> tag's URL to the redirect url, and change the same tag's connect attribute value to a number <4 for a faster redirect(default is 4)

**Comment by deadfishhackers** [comment]
@c0m94d3 in real instagram page it shouldn't redirect so its not an issue, you just have to remove redirecting option in our script, Thanks!


<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by sTiKyt** [comment]
@deadfishhackers one more advertisement and you will be reported, thank you for understanding :3

**Comment by An0nUD4Y** [comment]
@deadfishhackers , I appreciate your efforts for the tool , thanks for being a part of us ..
But please don't advertise anything here .
It's just a humble request , don't take it otherwise.

Thank to be a part of us !

**Comment by An0nUD4Y** [comment]
@c0m94d3 , i will try to fix it in next release..

**Comment by An0nUD4Y** [comment]
@sTiKyt , Please buddy , Don't block anyone ... If you feel some user should be blocked , Then Please Ask others before such action, it's just a request buddy .. 

Thanks To Maintain Stability ..

**Comment by sTiKyt** [comment]
@An0nUD4Y that was only for some days, also i reported him to GitHub support and they will decide what to do

**Comment by An0nUD4Y** [comment]
@sTiKyt , Don't do that buddy, He just wants to help us , And now he is also working on our Script , I think we can't loose contributors..
And also , i suggested him not to add those images more than once.. And i think its ok for once...

**Comment by sTiKyt** [comment]
@An0nUD4Y I want to have high quality software and support
What Microsoft or google will do if he post his advertisement somewhere on the official forum?
I would like to have clean and professional issues without distracting info that might make our users confused about who we are.
Users will ignore us because of this and we will loose much more contributors than 1
We don't need spam, ok?
Amount not important, but quality very!

**Comment by sTiKyt** [comment]
If he want to contribute to OPEN software, he can do this for FREE, without advertisements.

**Comment by An0nUD4Y** [comment]
@sTiKyt , Thanks for your efforts buddy , o have asked him not to do that again ..

**Comment by usama7628674** [comment]
Just block him he's so annoying.

**Comment by c0m94d3** [comment]
Calm down everyone, please

**Comment by An0nUD4Y** [comment]
@usama7628674 , You are right , he's annoying , but I just gave give last chance to be useful ..

**Comment by An0nUD4Y** [comment]
@c0m94d3 , I am closing here as , I mentioned I  will fix it in next update .
