### ISSUE TITLE
Facebook  serveo.net

### ISSUE THREAD

**Issue by blackbravo90** [DarkSecDevelopers/HiddenEye#337]
yesterday i used the facebook standard page section and use an custom URL and its work. But today i try to do the same things on it and its doesnt work at all in smartphone (iphone). its only shows a white pages on the screen. Btw its work for random Url. thank you so much

**Comment by An0nUD4Y** [comment]
@blackbravo90 , it's looking like your personal issues rather our script issues, And the reason behind the blank page in iPhone was due to the dead link, may be the link broken or failed anyway.
Thanks to mention ...

Closing currently , Feel free to Reopen...

**Comment by blackbravo90** [comment]
Thank you for the answer.

**Comment by deadfishhackers** [comment]
@blackbravo90 the link was dead thanks!
<hr>
<p align="center"><img src="http://i67.tinypic.com/5d6v4y_th.png"></p>
