### ISSUE TITLE
Facebook Page Break

### ISSUE THREAD

**Issue by Vardaan79** [DarkSecDevelopers/HiddenEye#341]
Facebook phishing page is not working properly. Any FIX??

![](https://i.imgur.com/wSirIRT.png)

**Comment by An0nUD4Y** [comment]
@Vardaan79 , We will fix it in next release.

**Comment by thepinguin** [comment]
Same here.

**Comment by gurutylor07** [comment]
I have an issue.  My hidden  do not open.  Must I root my phone before  it works.  It ask to run. Sudo.  But sudo refused  to install

**Comment by TheKingLmac** [comment]
Hey DarkSec, any idea on when this will be fixed? Cheers!

**Comment by An0nUD4Y** [comment]
@TheKingLmac , We will try to update the tool till next week , Stay Tuned ..
Cheers!

**Comment by TheKingLmac** [comment]
Love your work! Any other recommendations in the mean time? Cheers!

**Comment by An0nUD4Y** [comment]
@gurutylor07  Please clone the termux branch , use this command..
_git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git_

& Please take look carefully at readme file , and follow the [instructions ](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md)

**Comment by TheKingLmac** [comment]
I'm Apple unfortunately brother, Termux doesn't apply to me haha! I will just wait for the update fixing the Facebook issue, cheers!

**Comment by sTiKyt** [comment]
@TheKingLmac that's why i don't like apple

**Comment by usama7628674** [comment]
@sTiKyt Nice pic though.

**Comment by usama7628674** [comment]
@sTiKyt You look older then me.How old are you?

**Comment by sTiKyt** [comment]
@usama7628674 lmao, 17 years old -_-

**Comment by usama7628674** [comment]
@sTiKyt I'm turning 23 next month and you look older then me.Some people look quite aged then they really are.

**Comment by sTiKyt** [comment]
@usama7628674 maybe that seems like it for you? I mean, everyone think i'm very young here, just different countries, different looks xD

**Comment by usama7628674** [comment]
@sTiKyt Yeah that's right.

**Comment by arjunindia** [comment]
In case you need some help or want to do some phishing you can use my project 
https://github.com/arjunindia/fb-phisher-python
just a try to help.

**Comment by kwamet** [comment]
Any news on this fix?

**Comment by usama7628674** [comment]
@kwamet @sTiKyt @Vardaan79 @thepinguin @TheKingLmac Fixed it pull latest commit and try again.

**Comment by Onionboi1000** [comment]
# **hello guys my HiddenEye is not workin properlt_**
