### ISSUE TITLE
Random Serveo link is not generating

### ISSUE THREAD

**Issue by Basu-banakar** [DarkSecDevelopers/HiddenEye#342]
_  _ . ___  ___  ___ _  _  ___ _  _ ___
        |__| | ]  | ]  | |__ |\ |  |__ \__/ |__                                       |  | | ]__| ]__| |__ | \|  |__  ||  |__
        http://github.com/darksecdevelopers                                           ** BY:DARKSEC **
                                                                              -------------------------------
[ RANDOM SERVEO URL ]!!                                                       -------------------------------

**Comment by usama7628674** [comment]
@Basu-banakar Serveo is down pushing fix for ngrok wait.

**Comment by usama7628674** [comment]
@Basu-banakar update Hiddeneye and choose Ngrok cuz serveo is down.

**Comment by Basu-banakar** [comment]
Bro ngrok also link not generating

**Comment by usama7628674** [comment]
@Basu-banakar I said reclone the tool to match with latest commits.I fixed it

**Comment by Basu-banakar** [comment]
Ok thank you
