### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Jonny-k45** [DarkSecDevelopers/HiddenEye#344]
When running the pip3 install -r requirements.txt I get  a memory error (can be seen in screenshot) I have tried --no-cache-dir command which still did not work please help 
![Screenshot_20190626-193933_JuiceSSH](https://user-images.githubusercontent.com/52248136/60187047-85205000-984a-11e9-9c56-638554521e1d.jpg)

**Comment by sTiKyt** [comment]
I'm not sure if that's our issue

**Comment by Jonny-k45** [comment]
@sTiKyt I'm well aware of that but Im looking for advice on how to fix it cus I tried searching all over and couldn't find a good source for help

**Comment by usama7628674** [comment]
@Jonny-k45 I don't know about it but what I see form your image is there's a bug in ctypes module so your only solution is to comment out the line so navigate to `/usr/lib/python3.7/ctypes/__init__.py` and open in your text editor to do like following.
From
`CFUNCTYPE(c_int)(lambda: None)`

to
`#CFUNCTYPE(c_int)(lambda: None)`

**Comment by Jonny-k45** [comment]
@usama7628674 Unfortunately IV tried to find where userland stores the kalu file system and haven't been able to find it thanks for the help anyway

**Comment by usama7628674** [comment]
So you're using userland I also use kali on userland and it's working fine for me.

**Comment by Jonny-k45** [comment]
@usama7628674 do you know where userland stores Kali file system in androids storage?

**Comment by deadfishhackers** [comment]
@Jonny-k45 its not our script issue, try on Termux see if that works, this script works fine for me

**Comment by Jonny-k45** [comment]
I used termux and it worked thx

**Comment by Jonny-k45** [comment]
I used termux and it worked thx
