### ISSUE TITLE
Not able to create subdomain

### ISSUE THREAD

**Issue by Ankitu760** [DarkSecDevelopers/HiddenEye#345]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by An0nUD4Y** [comment]
Please provide more details .....

**Comment by An0nUD4Y** [comment]
Check for closed issue ,

**Comment by Ankitu760** [comment]
Same issue all time showing

**Comment by An0nUD4Y** [comment]
Please Describe it clearly...And give a screenshot

**Comment by Ankitu760** [comment]
I am not able to create custom subdomain
I am using oreo 8.1

**Comment by An0nUD4Y** [comment]
ScreenShot??

**Comment by Ankitu760** [comment]
Screen shot of this always same issue I tried many different names

**Comment by Ankitu760** [comment]
??
