### ISSUE TITLE
Can't open hidden eye

### ISSUE THREAD

**Issue by Jonny-k45** [DarkSecDevelopers/HiddenEye#346]
When I type python HiddenEye.py it says no such file or directory and when I type python HiddenEye this error pops up 
![Screenshot_20190629-141539_Termux](https://user-images.githubusercontent.com/52248136/60381878-ac5c6480-9a78-11e9-9dec-7e59bbe4ad19.jpg)
It worked perfect after first install but once I exited and tried to start again it didn't work anymore

**Comment by An0nUD4Y** [comment]
@Jonny-k45 , Please check the instructions carefully , As here you have not gone inside the HiddenEye directory.
Before launching the script , go to the script location at least ...
Check instructions Here : [Click Here ](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md)

**Comment by Jonny-k45** [comment]
Oh yeah my bad I skipped the cd command sorry for the ignorance
