### ISSUE TITLE
When I try to do the fishing link for Instagram the link doest creat

### ISSUE THREAD

**Issue by uUnnameDd** [DarkSecDevelopers/HiddenEye#349]
![Screenshot_20190701-153225_Termux](https://user-images.githubusercontent.com/52412177/60436777-76a0b280-9c15-11e9-81ed-ed96cd028210.jpg)
**Describe the bug**
When I do the fishing link for Instagram the link doesnt create

**Expected behavior**
I expected for a link to show

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S9]
 - OS: [Android 9]

**Comment by An0nUD4Y** [comment]
@uUnnameDd , Please clone Again ,We have fixed it  ...

use :

git pull

**Comment by usama7628674** [comment]
@uUnnameDd Use `git reset --hard` then `git pull -f`

**Comment by uUnnameDd** [comment]
@usama7628674 I did that and an error occured: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
$ git reset --hard

**Comment by uUnnameDd** [comment]
@usama7628674 when I type git pull -f I have thise :$ git pull -f
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

**Comment by uUnnameDd** [comment]
@usama7628674 when I type git pull -f I have thise :$ git pull -f
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

**Comment by usama7628674** [comment]
@uUnnameDd Just delete and clone the tool again.

**Comment by uUnnameDd** [comment]
@usama7628674 how do I do that?

**Comment by usama7628674** [comment]
@uUnnameDd Use git to clone

**Comment by uUnnameDd** [comment]
@usama7628674 I dont understand. Can you just type the code please

**Comment by usama7628674** [comment]
@uUnnameDd See installation instructions.

**Comment by afzal-kbr** [comment]
@usama7628674
I have tried recloning but the link is not getting created with serveo/ngrok. Tried reinstalling the termux also.. but no change. Please help.

**Comment by FXkracht** [comment]
you need te get a fishing smartschool
