### ISSUE TITLE
Not able to create subdomain

### ISSUE THREAD

**Issue by Ankitu760** [DarkSecDevelopers/HiddenEye#350]
[**Describe](url
![Screenshot_2019-06-29-22-32-38-016_com termux](https://user-images.githubusercontent.com/52342832/60519945-0dcc3f80-9cd4-11e9-9834-75f8c65ac197.png)
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by An0nUD4Y** [comment]
@ankitu760 , This is because serveo.net is down currently..
You can try Ngrok or wait for serveo ...

**Comment by loveablefellow007** [comment]
I tried both ngrok and serveo.net but same result not valid going back
