### ISSUE TITLE
Serveo link is not genarating

### ISSUE THREAD

**Issue by MrNobodyTharusha** [DarkSecDevelopers/HiddenEye#352]
Cant genarate serveo custom and random urls. But ngrok working well.
I have used serveo link before i reinstalling the termux. But now cant creat subdomain.
Please help me.

**Comment by usama7628674** [comment]
@MrNobodyTharusha Serveo is down use ngrok

**Comment by MrNobodyTharusha** [comment]
Ok. Please fix it if u can. because i love this tool....
