### ISSUE TITLE
Sub Domain Serveo Error

### ISSUE THREAD

**Issue by SheZCo** [DarkSecDevelopers/HiddenEye#354]
Every time I choose serveo as my server provider no matter if i make a custom or choose a random it takes forever to load(Never loads)

**To Reproduce**
1. Go to './HiddenEye.py'
2. Click on 'Any of the options'
3. Select 'Serveo'
4 Choose 'Random or Custom'
5. See error aka Foreverloading

**Expected behavior**
I expected for me to be able to use the serveo server provider

**Additional context**
I also get this error

Traceback (most recent call last):
  File "./HiddenEye.py", line 38, in <module>
    getCredentials()
  File "/home/bitchx/HiddenEye/Defs/Actions.py", line 558, in getCredentials
    ip = re.match('Victim Public IP: (.*?)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by usama7628674** [comment]
Serveo is down use ngrok
