### ISSUE TITLE
Link not getting generated

### ISSUE THREAD

**Issue by afzal-kbr** [DarkSecDevelopers/HiddenEye#355]
I have tried recloning of hiddeneye and reinstalling of termux app but still the link doesn't get generated. Tried with both serveo and ngrok. 
![Screenshot_20190709-165138](https://user-images.githubusercontent.com/52703453/60885742-ecd49300-a26d-11e9-82c0-bdfa3b0a565b.png)
Please help out.

**Comment by STAR-Sec** [comment]
Serveo is having a lot of issues lately. It will most likely start working as soon as they finish whatever they are working on.

**Comment by usama7628674** [comment]
Serveo is up now.try again
