### ISSUE TITLE
ADDING TOOLS ....

### ISSUE THREAD

**Issue by An0nUD4Y** [DarkSecDevelopers/HiddenEye#356]
Hey Guys ,
I have worked on the tools made by @thelinuxchoice , and i think his tools are useful and effective , I found some of his tools which can be useful enough.
And the same tools i have added to the HiddenEye last month , But its not working as it should to be, & i think it need a little more documentation..
It would be very helpfull if anyone of you can help me to complete the documentation because i am busy since two months , 
Check my [instagram post](https://www.instagram.com/p/BywmtONg6zJ/)  which i made before completing the documentation process, I need help if anyone can ..
I am uploading [my  work Here](https://drive.google.com/file/d/1l-kPcAf557GphRtZ1fddjf414NwVTq5E/view?usp=sharing)
Suggest me if you have any suggestion related to this.....
I am busy with studies so unable to complete it & also the document modification had already wasted my enough time.

i am waiting for response .....

**Comment by usama7628674** [comment]
Can you explain what tools you've been working for months

**Comment by An0nUD4Y** [comment]
@usama7628674 , Actually , I didn't worked for the whole month. I only did it few days last month. I was got stuck in other works..
The tools I m talking about are:
1) Locator 
2) Saycheese
3) Excuseme
4) Clipboardme

These all are @thelinuxchoice tools, you can find it on his Repo list..

I know these are not a lot tools , but by adding tools to Hiddeneye , I think it will make it more useful.

**Comment by An0nUD4Y** [comment]
I am waiting for responses ...

**Comment by gungdalem** [comment]
Can you teach me how to make tools with server
😀

**Comment by gungdalem** [comment]
Please teach me how to make tools

**Comment by An0nUD4Y** [comment]
No Response. Closing Here..
Feel Free to Reopen.
