### ISSUE TITLE
verify internet

### ISSUE THREAD

**Issue by Duplic8e** [DarkSecDevelopers/HiddenEye#357]
i have a probelm,when i am connected to the Internet it keeps saying

 [!] ^Network error^. Verify your Internet connection.

**Comment by Micrafast** [comment]
Which country are you in? Google might be banned in that country. Open Defs/Checks.py, find a row like this: 
def checkConnection(host='https://google.com'): #Connection check
Change https://google.com into a available website in the country you're in.

**Comment by An0nUD4Y** [comment]
Please check for solved issues first ...

https://github.com/DarkSecDevelopers/HiddenEye/issues?utf8=%E2%9C%93&q=network+error

**Comment by Duplic8e** [comment]
i have checked the solved issues but havent gotten it resolved on my end

**Comment by Duplic8e** [comment]
@Micrafast google works fine in my country (UAE)

**Comment by usama7628674** [comment]
@Duplic8e Reclone or `fit pull -f` and try agian.

**Comment by Duplic8e** [comment]
@usama7628674 still didnt work sir

**Comment by argtje99** [comment]
Are you using Nethunter? @Duplic8e

**Comment by usama7628674** [comment]
@Duplic8e If you're using Nethunter then do `git pull`.I've fixed it.

**Comment by argtje99** [comment]
Latest nethunter version has some problems with SSL. Try
update-ca-certificates -f 
This will refresh your ssl certificates and reinstalls them. This worked for me !

**Comment by Duplic8e** [comment]
Guys all I’m using is kali Linux on an HP computer and I’m using the regular terminal in kali.plus I always get the problem whet not available and when I download it the no internet problem takes place

**Comment by sTiKyt** [comment]
@Duplic8e you have to change link to something available in your country.We use Google or DuckDuckGo, It's probably blocked for you.

**Comment by Duplic8e** [comment]
@sTiKyt google or duck duck go work fine for me

**Comment by usama7628674** [comment]
@Duplic8e So is it working now?

**Comment by An0nUD4Y** [comment]
No Response. Closing Here..
Feel Free to Reopen.
