### ISSUE TITLE
Error Installing Hidden Eye on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by hyankwildan** [DarkSecDevelopers/HiddenEye#358]
**Describe the bug**
i have this isue whe i installing on my ubuntu 18.04 LTS
* i have try to using Python 2 its fail, so i remove it with auto remove and so i installing new one python3 the problem is still the same.
* i have done with this requirments

    Python 3
    Wget from Python
    PHP
    sudo
but i, still not succes install it on ubuntu 18.04 LTS

root@syaiful-HP-ProBook-4341s:/home/syaiful/HiddenEye# ./HiddenEye.py
Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/home/syaiful/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24380263/61167400-cf9f0d80-a568-11e9-8ec7-4c6a60183a1a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser Firefox Quantum 67.0.4 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by An0nUD4Y** [comment]
You need to install wget first ...
Try this...

pip3 install wget

**Comment by An0nUD4Y** [comment]
NO RESPONSE : CLOSING HERE 
You can open it again if the above answer doesn't work for you.
