### ISSUE TITLE
Unexpected close after the first credentials capture

### ISSUE THREAD

**Issue by Hunter310** [DarkSecDevelopers/HiddenEye#359]
This error occurs after having first captured the user's credentials.

[*] Waiting For Victim Interaction. Keep Eyes On Requests Coming From Victim ...

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

..................................................................
[ CREDENTIALS FOUND ]:
[EMAIL]: 1223 [PASS]: 1234
..................................................................
Traceback (most recent call last):
File "./HiddenEye.py", line 38, in
getCredentials()
File "/root/Escritorio/HiddenEye/Defs/Actions.py", line 572, in getCredentials
log('..................................................................'.format(MAIN0, MAIN4))
NameError: name 'log' is not defined

Someone will know why this error occurs. (The script has root user permissions)

NOTE: Note that this error occurs in Localhost URL.

**Comment by usama7628674** [comment]
Please use english

**Comment by Hunter310** [comment]
This error occurs after having first captured the user's credentials.

[*] Waiting For Victim Interaction. Keep Eyes On Requests Coming From Victim ...

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

..................................................................
[ CREDENTIALS FOUND ]:
[EMAIL]: 1223 [PASS]: 1234
..................................................................
Traceback (most recent call last):
File "./HiddenEye.py", line 38, in
getCredentials()
File "/root/Escritorio/HiddenEye/Defs/Actions.py", line 572, in getCredentials
log('..................................................................'.format(MAIN0, MAIN4))
NameError: name 'log' is not defined

Someone will know why this error occurs. (The script has root user permissions)

**Comment by An0nUD4Y** [comment]
Check these closed issue #204 #207  ...
If these do not resolve your problem.
Then try to update & relaunch script.


Let me know if it helps or not.

**Comment by Mageshwar01** [comment]
Sometimes it's working and sometimes it isn't......I can't understand why........
.
.
.
........................................................
Traceback (most recent call last):
File "./HiddenEye.py", line 38, in
getCredentials()
File "/root/Escritorio/HiddenEye/Defs/Actions.py", line 558, in getCredentials
.
Etc....,
.

**Comment by usama7628674** [comment]
@Mageshwar01 do `chmod 777 HiddenEye`

**Comment by Mageshwar01** [comment]
@usama7628674 I did that when I installed HiddenEye...... should I do that once again?

**Comment by sTiKyt** [comment]
Fixed in #401

**Comment by sTiKyt** [comment]
That was our mistake guys, wait until it's merged and you'll be fine and ready!

**Comment by loveablefellow007** [comment]
Why custok domain in serveo is not working??

**Comment by Moltivie** [comment]
@Hunter310 how you may reproduce the error?

**Comment by Moltivie** [comment]
Tested and already been fixed.

**Red** first request
**Blue** second request

![image](https://user-images.githubusercontent.com/14014692/69009698-45244b80-0958-11ea-83f6-ed8846e2587c.png)
