### ISSUE TITLE
Doesn't Generated links in Both Ngrok and Serveo 

### ISSUE THREAD

**Issue by airblazerz** [DarkSecDevelopers/HiddenEye#361]
No links generated
![Screenshot_20190718-210045](https://user-images.githubusercontent.com/20871079/61459584-a551b380-a99f-11e9-8ab1-8aa7e0d4a3fd.png)

**Comment by KathanP19** [comment]
it takes some time but if it doesn't generated then upgrade update packages.

**Comment by airblazerz** [comment]
Thanks , i can now generate on serveo , i think the problem is on its server.
