### ISSUE TITLE
Add my own server 

### ISSUE THREAD

**Issue by Alyoninthecity** [DarkSecDevelopers/HiddenEye#363]
great job, I wonder if it would be possible to insert a custom link without using serveo or ngrok. I upload the necessary files like instagram or facebook to my site, if you can already do how to do it? I hope I explained myself

**Comment by usama7628674** [comment]
@Alyoninthecity Yes you can upload webpages to any hosting site and it'll work fine.

**Comment by An0nUD4Y** [comment]
@Alyoninthecity  , Before uploading to your server don't forget to add the files like ip.php , keylogger.php , keylogger.js . These will help you to capture keystrokes and ip addresses.

I hope it will help you.

**Comment by lordcharlx** [comment]
how about hosting on a webserver
