### ISSUE TITLE
[MAC OS X] PermissionError: Permissions denied! Unexpected platform

### ISSUE THREAD

**Issue by danilogkir** [DarkSecDevelopers/HiddenEye#364]
Can't start the script: `python3 HiddenEye.py`                                                   

What displays next: ```HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):  File "HiddenEye.py", line 15, in <module>
    checkPermissions()
  File "/Users/daniel/HiddenEye/Defs/Checks.py", line 67, in checkPermissions
    raise PermissionError("{0}Permissions denied! Unexpected platform".format(RED))
PermissionError: Permissions denied! Unexpected platform```

After installing everything on Mac OS X run the python3 command with HiddenEye.py (python3 HiddenEye.py)

 - OS: macOS Mojave

**Comment by gekza** [comment]
sudo chmod +x HiddenEye.py

**Comment by usama7628674** [comment]
Will push fix soon

**Comment by sTiKyt** [comment]
@danilogkir MacOS not supported yet.

**Comment by danilogkir** [comment]
Sad.

**Comment by iamtheWitchDoctor** [comment]
Same issue on Mojave - Any idea on a timeframe for Mac support?

**Comment by usama7628674** [comment]
@danilogkir @iamtheWitchDoctor Please reclone or `git pull -f` to get latest commits.MAC OS is not supported.

**Comment by An0nUD4Y** [comment]
CLOSING HERE.
Feel Free to Reopen..
