### ISSUE TITLE
How can i add my own custom page?

### ISSUE THREAD

**Issue by filebe777** [DarkSecDevelopers/HiddenEye#365]
how can i add my own custom page, i need to teach and test colleagues knowledge on Phishing

**Comment by merabet1024** [comment]
am run the script on Kali , but i got this bug

Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/clons/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by usama7628674** [comment]
@filebe777 Basically you can just create your own phishing page and run it with any local server you don't need this tool to teach.If you know python you can easily go through script and add your own phishing page.

**Comment by usama7628674** [comment]
@merabet1024 install wget `pip3 install wget`

**Comment by merabet1024** [comment]
> install wget `pip3 install wget`

i ready had this installed

**Comment by usama7628674** [comment]
@merabet1024 Make sure you run script with `python3`

**Comment by merabet1024** [comment]
> Make

root@kali:~/clons/HiddenEye# python3 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/clons/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'
root@kali:~/clons/HiddenEye#

**Comment by usama7628674** [comment]
@merabet1024 There's something wrong on your OS and I can't help you cuz I only solve problems related to this tool and not issues related to individual user OS.

**Comment by merabet1024** [comment]
my OS are Updated. your script have bugs
