### ISSUE TITLE
Ngrok link not generating

### ISSUE THREAD

**Issue by X1nto** [DarkSecDevelopers/HiddenEye#369]
Hi, i have problem with generating Ngrok links

When choosing ngrok instead of serveo.net this happens
![Screenshot_20190730-203239](https://user-images.githubusercontent.com/48173186/62147865-89d49a00-b309-11e9-9cd2-4e36a1946aaa.png)
It gets stuck on this screen and program is not responding

It should show the generated ngrok link

 - Device: Amazon Fire HD 8
 - OS: Android 7.1.2
 - Browser - Stock browser: Silk browser
 - Version: 0.2.7

**Comment by Husainali786** [comment]
When you select ngrok turn on your mobile hotspot . It is a defect of ngrok so when you start ngrok turn on your mobile hotspot. Then it will start port forwarding and generat your link

**Comment by X1nto** [comment]
> When you select ngrok turn on your mobile hotspot . It is a defect of ngrok so when you start ngrok turn on your mobile hotspot. Then it will start port forwarding and generat your link

I'm on a tablet with no LTE/3G, so no fix for me?

**Comment by An0nUD4Y** [comment]
It's not the issue with script.
Closing Here , Feel Free to Reopen.

**Comment by bhuveshrao198** [comment]
> When you select ngrok turn on your mobile hotspot . It is a defect of ngrok so when you start ngrok turn on your mobile hotspot. Then it will start port forwarding and generat your link

Thankyou brother 
It works

**Comment by bhuveshrao198** [comment]
.

**Comment by vivopixel** [comment]
Ngrok still not generating link even after turning on my hotspot.
