### ISSUE TITLE
Does not show the credentials and closes the connection unexpectedly

### ISSUE THREAD

**Issue by MrDrago** [DarkSecDevelopers/HiddenEye#371]
**Describe the bug**
When trying to perform any test, an error occurs that breaks the script

**To Reproduce**

1* Sudo ./HiddenEye.py

2*  Select any template

3* Configure the necessary parameters

4* Start the attack

5* When the victim enters their data

6* Error: 

```
Traceback (most recent call last):
  File "HiddenEye.py", line 44, in <module>
    getCredentials(port)
  File "/home/elvaquero/Git/HiddenEye/Defs/Actions.py", line 583, in getCredentials
    ip = re.match('Victim Public IP: (.*?)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Expected behavior**
Be able to visualize the data and continue with the attack

**Screenshots**

![Captura de pantalla de 2019-08-02 21-56-56](https://user-images.githubusercontent.com/32129880/62406038-e1c20980-b572-11e9-8927-3b80dc081cb6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 74.0.3729.169

**Smartphone (please complete the following information):**

I have not tried on mobile

**Additional context**

I have tried them from my own attacking machine, from an incognito window

**Comment by MrDrago** [comment]
I added, I have tested if KEYLOGGER causes the problem, so do not activate it and it still happens.

**Comment by usama7628674** [comment]
@MrDrago Please do `git pull -f` or reclone the tool.I've pushed some fixes that might work for you.

**Comment by MrDrago** [comment]
> @MrDrago Please do `git pull -f` or reclone the tool.I've pushed some fixes that might work for you.

I have cloned the tool and it still causes the error, under the same test conditions.  @usama7628674 


![image](https://user-images.githubusercontent.com/32129880/62412117-f8487f00-b5cb-11e9-864b-85dfb4217ce9.png)


```
Traceback (most recent call last):
  File "./HiddenEye.py", line 44, in <module>
    getCredentials(port)
  File "/home/elvaquero/Git/HiddenEye/Defs/Actions.py", line 583, in getCredentials
    ip = re.match('Victim Public IP: (.*.*.*)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

He added that he used **port 80** and **serveo.net** to carry out the attack.
At the moment I have not tried **Ngrok**


_I update, just before publishing the answer, I test the script and it worked, with the standard Facebook phishing page, with and without keylogger it worked._

I don't understand, because sometimes it works and sometimes it doesn't.

Similarly, I will try all the templates to see if it has to do with anything.

**Comment by Ajitprajapati23** [comment]
[
![Screenshot_20190804-052742](https://user-images.githubusercontent.com/53351269/62417859-d3f6ac00-b678-11e9-9636-073f67df4363.png)
](url)



Same error with termux 1st attempt successful after that getting same error...

**Comment by MrDrago** [comment]
> [ ![Captura de pantalla_20190804-052742](https://user-images.githubusercontent.com/53351269/62417859-d3f6ac00-b678-11e9-9636-073f67df4363.png) ](url)
> 
> El mismo error con el primer intento de termux exitoso después de obtener el mismo error ...

@Ajitprajapati23  What template did you use?
Try launching the script again with another template and then try again with the template you want, sometimes it works normally and sometimes it doesn't.
But more are the times it doesn't work.

**Comment by usama7628674** [comment]
@MrDrago I'll push new fix soon.

**Comment by KathanP19** [comment]
Guys try chmod 777 to whole directory

**Comment by MrDrago** [comment]
> Guys try chmod 777 HiddenEye to whole directory

@KathanP19  That was the mistake brother, thanks for the help that was the only value.
