### ISSUE TITLE
I don't get the redirect link

### ISSUE THREAD

**Issue by Ark32** [DarkSecDevelopers/HiddenEye#372]
I am using kali linux on termux android i have done all the steps mentioned in the instructions it works well but in the end i don't get a redirect link
![Screenshot_20190811-054029](https://user-images.githubusercontent.com/53979519/62828068-f3eb1a00-bbfa-11e9-9562-dfdad8b22890.png)

**Comment by An0nUD4Y** [comment]
@Ark32 , You have not downloaded Ngrok,
Try to relaunch or reclone the script.
