### ISSUE TITLE
HiddenEye

### ISSUE THREAD

**Issue by lakis12345** [DarkSecDevelopers/HiddenEye#373]
IF FOUND SEGMENTATION FAULT, IT MEANS THE SERVER FAILED.            |
[!] THEN YOU HAVE TO RUN IT AGAIN.                                      |
[!] Use This Command In Another Terminal.                               |
(cd Server/www/ && php -S 127.0.0.1:4444 > /dev/null)             
Help my

**Comment by An0nUD4Y** [comment]
It's Not Clear Description of issue.
Closing it....
