### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by saharbabaei777** [DarkSecDevelopers/HiddenEye#374]
![Screenshot_20190813-211736_Chrome](https://user-images.githubusercontent.com/50140993/62960458-ece92500-be0f-11e9-84a0-7b2bae571a6f.jpg)

**Comment by An0nUD4Y** [comment]
This is because of the malicious use of serveo for illegal phishing , & some others illegal uses.
That is why it's blocked, and shows this message in Google Chrome.

WE DON'T SUPPORT MALICIOUS ACTIVITIES.

**Comment by usama7628674** [comment]
@saharbabaei777 Please generate other serveo sites using "custom url option" and this error will go away.
