### ISSUE TITLE
NGROK option holds the program

### ISSUE THREAD

**Issue by elunala** [DarkSecDevelopers/HiddenEye#376]
Hey, so lately when I use the NGROK option the program gets hold with the message [ NGROK SERVER PROCEDURE ]!! does any body have the same issue?

**Comment by usama7628674** [comment]
@elunala It's not an issue script is just letting the user know that you're using ngrok.

**Comment by elunala** [comment]
The thing is that after I select the NGROK option I cant do anything else in the program, an URL to use by NGROK is generated neither below the print......

|_| | ]  | ]  | |_ |\ |  |_ \/ |_
        |  | | ]_| ]| |_ | \|  |_  ||  |_
        http://github.com/darksecdevelopers
        * BY:DARKSEC *

-------------------------------
[ HOST SERVER SELECTION ]!!
-------------------------------

 [!](SERVEO WORKS BETTER)

 [*]Select Any Available Server:

 [1]Ngrok
 [2]Serveo

HiddenEye >>> 1

        _  _ . _  _  _ _  _  _ _  _ _
        |_| | ]  | ]  | |_ |\ |  |_ \/ |_
        |  | | ]_| ]| |_ | \|  |_  ||  |_
        http://github.com/darksecdevelopers
        * BY:DARKSEC *

-------------------------------
[ NGROK SERVER PROCEDURE ]!!
-------------------------------

***The program stops here, any further information provided

**Comment by An0nUD4Y** [comment]
@elunala , I encountered no such issue , Even after trying multiple times .
I have tried to reproduce this issue in both Termux and Linux.

You can help by providing more information including device you are using.

And also make you have the latest cloned files.

**Comment by jhotayex** [comment]
I am stuck in this on ngrok but serveo works fine.

_  _ . ___  ___  ___ _  _  ___ _  _ ___                       |__| | ]  | ]  | |__ |\ |  |__ \__/ |__
        |  | | ]__| ]__| |__ | \|  |__  ||  |__                       http://github.com/darksecdevelopers
        ** BY:DARKSEC **                                      
-------------------------------
[ NGROK SERVER PROCEDURE ]!!
-------------------------------
Is there any fix for this issue?

**Comment by DocKali** [comment]
I have exactly the same problem than @jhotayex 
For me serveo works fine, but with Ngrok I'm stuck with message [Ngrok server procedure]
Any idea where the problem comes from?

**Comment by jepunband** [comment]
ngrok is hitting too many corrections

**Comment by juanjavito** [comment]
> I too have the same problem I'm using a Samsung A50s can anyone help me with this

do this :

-Select ngrok 
-turn on the hostpot 
-wait

work for me

**Comment by An0nUD4Y** [comment]
Check #526
