### ISSUE TITLE
Stopped at [NGROK SERVER PROCEDURE]!!

### ISSUE THREAD

**Issue by zaydhisyam** [DarkSecDevelopers/HiddenEye#379]
![Screenshot_20190827-085530](https://user-images.githubusercontent.com/36096721/63735019-a207ec80-c8a8-11e9-81e8-825d9dbf7de9.png)

Hello hiddeneye, my termux app stopped after menu "Select any available server". Can you help me what I should do next or maybe it's kind of bug? Thank you

**Comment by An0nUD4Y** [comment]
Check #376  ,
