### ISSUE TITLE
Serveo doesn't work

### ISSUE THREAD

**Issue by Gwinbleiddd** [DarkSecDevelopers/HiddenEye#380]
Why doesn’t serveo site work in termux? they are not immersed in the browser.

**Comment by usama7628674** [comment]
Serveo is down

**Comment by Gwinbleiddd** [comment]
Forever and ever?

**Comment by usama7628674** [comment]
No it'll be back once it'll be online

**Comment by Gwinbleiddd** [comment]
thank you
