### ISSUE TITLE
Other Tunneling Server

### ISSUE THREAD

**Issue by tony3ds** [DarkSecDevelopers/HiddenEye#382]
Is it possible to add other server like serveo for tunneling host? 

Can I add other ones by myself? 

Sorry for my bad English (i'm Italian)

**Comment by An0nUD4Y** [comment]
@tony3ds , yes you can add other servers too.
But rather than Adding that tunneling host to script , You should lauch it manually. And also configure it to tunnel the localhost address and port no. Same as that generated.
Just use the same port as you choosen in the script.

**Comment by Moltivie** [comment]
@tony3ds by the way you there are a couple of tunneling services within the software. You may want to check them out. In any case you may want to contribute!

Thanks.

**Comment by Moltivie** [comment]
@An0nUD4Y @sTiKyt it can be considered as closed issue and a "done" over the "project" section.
