### ISSUE TITLE
Is Serveo down?

### ISSUE THREAD

**Issue by Frosty4819** [DarkSecDevelopers/HiddenEye#383]
Ever since the new cloudflare update came out the websites don't even work anymore.

i used to just make it and it worked now whenever i try to click it it doesn't take me to a page.

![yeetok](https://user-images.githubusercontent.com/54737263/64061142-0e3e6500-cbb5-11e9-901b-8778f3b99286.png)

im putting port 443 when it asks me to pick a website port and i hit no for keylogging and yes for cloudflare.

**Comment by An0nUD4Y** [comment]
@Frosty4819 , This error is not because of the latest commits , Errors are because of serveo , As currently is DOWN CURRENTLY [Check Here](https://www.isitdownrightnow.com/serveo.net.html).

**Comment by usama7628674** [comment]
@An0nUD4Y @Frosty4819 In the coming days i'll add an alternative of serveo cuz it's mostly down at times so i may add this https://github.com/antoniomika/sish

**Comment by An0nUD4Y** [comment]
@usama7628674 , Then I will wait for your commits.
Thanks Bro.
You are helping me a lot to learn new things.
