### ISSUE TITLE
Add PlayStation login page.

### ISSUE THREAD

**Issue by Frosty4819** [DarkSecDevelopers/HiddenEye#384]
PlayStation would be an amazing addition to the tool, thank you.
![image](https://user-images.githubusercontent.com/35602029/64943190-c0dc1c00-d873-11e9-8cb7-3f41ecac7c9e.png)

**Comment by An0nUD4Y** [comment]
@Frosty4819 , Thanks for a Request.
We will add it in next commits...

**Comment by Moltivie** [comment]
@An0nUD4Y @sTiKyt proceed to close this issue and mark it as done.

Thank you.

**Comment by Moltivie** [comment]
@sTiKyt Thanks.
