### ISSUE TITLE
REQUEST : Add Website Cloner ??

### ISSUE THREAD

**Issue by alari73512** [DarkSecDevelopers/HiddenEye#385]
idk if there is but there isnt a website cloner option there, then can you please add it?. this is an awesome tool but without website cloner its useless for me.
thank you!

**Comment by An0nUD4Y** [comment]
@alari73512 , Adding a website clonner is not a good idea, This request came many time by the users.

As it will create more difficulties in maintaining the Repo.
And also Now the most of the websites have protection from such cloning tools, So the cloned page will not work & will get broke.

If you still need a cloner , just check for SETTOOLKIT.
