### ISSUE TITLE
ngrok in Termux 

### ISSUE THREAD

**Issue by Gwinbleiddd** [DarkSecDevelopers/HiddenEye#386]
How to use ngrok in Termux with HiddenEye?

**Comment by An0nUD4Y** [comment]
Well, We have a [Termux-support-branch](https://github.com/DarkSecDevelopers/HiddenEye/tree/Termux-Support-Branch)  of Hiddeneye Tool. You can use the same script in Termux also , You can simply select NGROK when asked to select server.

**Comment by Gwinbleiddd** [comment]
I have it not work.  just does not start.

**Comment by Gwinbleiddd** [comment]
Please, help me.

**Comment by Gwinbleiddd** [comment]
I choose ngrok but nothing happens.

**Comment by sTiKyt** [comment]
@Gwinbleiddd sometimes Ngrok goes offline, it's not related to our team. 
Sorry :3
