### ISSUE TITLE
Ngrok Is Bugging Out

### ISSUE THREAD

**Issue by thehacker887** [DarkSecDevelopers/HiddenEye#387]
Its Giving Me The Same Ngrok Link. Every single time i make a session
![HELP ME PLEASE](https://user-images.githubusercontent.com/21208848/64131616-c4fa3b00-cd97-11e9-9c4f-7cb70f2c71df.PNG)
![HELP ME PLEASE](https://user-images.githubusercontent.com/21208848/64131623-d2afc080-cd97-11e9-9848-02f278244152.PNG)

**Comment by An0nUD4Y** [comment]
#526
