### ISSUE TITLE
Static phishing pages

### ISSUE THREAD

**Issue by hxrofo** [DarkSecDevelopers/HiddenEye#388]
Hi
Facebook and messenger pages don't load properly because, AFAIK, the resources like CSS, JavaScript and images load from a different server every single day. 

Everybody, I guess, knows how to clone a website... but that's a lot of work if we want to use phishing attacks on a regular basis.

I suggest that you remove the old phishing pages and clone new ones but instead you store all the resources in a local folder "static" and change the links accordingly. 

Thanks

**Comment by An0nUD4Y** [comment]
#569
