### ISSUE TITLE
Can you add Xbox accounts?

### ISSUE THREAD

**Issue by Pickleman95** [DarkSecDevelopers/HiddenEye#389]
**Is your feature request related to a problem? Please describe.**
It's Feature request

**Describe the solution you'd like**
I really want to be able to break into Xbox accounts and cannot find any good tool for the job.

Add XBox login page.

**Additional context**
![image](https://user-images.githubusercontent.com/35602029/64942473-cdf80b80-d871-11e9-97c0-b05067309c71.png)

**Comment by Pickleman95** [comment]
I really want to be able to break into Xbox accounts and cannot find any good tool for the job.

**Comment by Moltivie** [comment]
Added! Thanks. (PL #450)

If you would like to have others websites to be added, do not hesitate to tell us!
