### ISSUE TITLE
MySpace & ProtonMail doesn't work, prompts to restart

### ISSUE THREAD

**Issue by Pickleman95** [DarkSecDevelopers/HiddenEye#390]
Certain phishing sites will not work. An example of this is the myspace phishing site. It tells you to choose one site and prompts you to restart the program.

**Comment by Pickleman95** [comment]
> Certain phishing sites will not work. An example of this is the myspace phishing site. It tells you to choose one site and prompts you to restart the program.

Protonmail and Myspace are the sites that do not work

**Comment by usama7628674** [comment]
@Pickleman95 Will be fixed soon

**Comment by DocKali** [comment]
> @Pickleman95 Will be fixed soon

Any idea when?

**Comment by Moltivie** [comment]
Resolving!

**Comment by Moltivie** [comment]
Fixed PL (#450)
