### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Pickleman95** [DarkSecDevelopers/HiddenEye#391]
Could you add Youtube accounts? It would be very useful. Thank you.

**Comment by An0nUD4Y** [comment]
@Pickleman95 , May be on next update..

**Comment by iamat8080** [comment]
Can you help me to run this with my external ip or apache2 server 
:)

**Comment by Pickleman95** [comment]
> Could you add Youtube accounts? It would be very useful. Thank you.

> @Pickleman95 ,
> Please provide a direct link of that webpage.
> May be on next update we can add ..
The login is very similar to the google one. Here is the link: https://accounts.google.com/signin/v2/identifier?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252F&hl=en&ec=65620&flowName=GlifWebSignIn&flowEntry=ServiceLogin

**Comment by usama7628674** [comment]
@Pickleman95 We already have gmail phishing page.If you have email and pass you can access youtube with gmail account.
