### ISSUE TITLE
webserver port selection

### ISSUE THREAD

**Issue by DerekCool21** [DarkSecDevelopers/HiddenEye#393]
When I select any media, then I put the redirect link, and instead of making me choose between ngrok or serveo, it makes me select an available port. I haven't seen this in any tutorial, and I don't know what port I should select

1. Go to 'cd HiddenEye, then sudo python3 HiddenEye.py'
2. Select social media and redirect link
3. I am the only one who I see "Select any available port"

It should make me choose between ngrok and serveo

**Comment by DerekCool21** [comment]
Nope, it doesn't work, it says "sh: 1: curl\: not found ", the same that with other ports

**Comment by An0nUD4Y** [comment]
@DerekCool21 , Looks like you haven't installed curl .
Use this command to install curl.
`apt install curl`

**Comment by DerekCool21** [comment]
@An0nUD4Y it says unable to acquire the dpkg frontend lock

**Comment by usama7628674** [comment]
@DerekCool21 `pkill packagekitd` and then install curl

**Comment by DerekCool21** [comment]
@usama7628674 oh my god I love you
