### ISSUE TITLE
iCloud form off screen

### ISSUE THREAD

**Issue by Pickleman95** [DarkSecDevelopers/HiddenEye#396]
When the link for icloud is accessed the login is off the screen.

**Comment by Pickleman95** [comment]
The problem seems to have grown worse. The login appears to be absent.
![Screenshot from 2019-09-25 18-17-06](https://user-images.githubusercontent.com/55029135/65623966-7287f500-dfb8-11e9-9642-83f1affa0cf7.png)

**Comment by Pickleman95** [comment]
![Screenshot from 2019-09-25 18-24-27](https://user-images.githubusercontent.com/55029135/65624414-5c2e6900-dfb9-11e9-8d6b-b8389e6d1d44.png)

**Comment by JustMario0** [comment]
yeah if someone have fix please help me

**Comment by Moltivie** [comment]
Thanks, we are working on it!

**Comment by JustMario0** [comment]
@Moltivie thank you so much we need this page

**Comment by An0nUD4Y** [comment]
@JustMario0 , You can increase this issues priority by funding this issue.

**Comment by JustMario0** [comment]
@An0nUD4Y i found another HTML and CSS but hiddeneye dont let me use it.. information not showing apple id and passowrd

**Comment by usama7628674** [comment]
@JustMario0 icloud page is outdated.I'll update it later.

**Comment by JustMario0** [comment]
@usama7628674  its still like this.. 
![AC45104B-2A59-46B6-8B23-8297D885BB2E](https://user-images.githubusercontent.com/57155446/69563506-e6934900-0fb9-11ea-80c2-cf66c7678b34.jpeg)

**Comment by An0nUD4Y** [comment]
#569
