### ISSUE TITLE
Blogger.com template request 

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#399]

**Comment by usama7628674** [comment]
Will be added soon

**Comment by lordcharlx** [comment]
@usama7628674  how soon ?

**Comment by sTiKyt** [comment]
@lordcharlx you can speed it up using "sponsor" button >_<

**Comment by Moltivie** [comment]
@lordcharlx working on it!

**Comment by Moltivie** [comment]
@usama7628674 @sTiKyt could you add the user-request label for this one.

**Comment by An0nUD4Y** [comment]
@lordcharlx , Track Progress #569
