### ISSUE TITLE
Python code structure fix

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#400]
**Is your feature request related to a problem? Please describe.**
Our code sometimes seems very unorganized.

**Describe the solution you'd like**
I'd like to rewrite everything, according to conventions and structure suggestions.

**Additional context**
Working on it right now.

**Comment by sTiKyt** [comment]
Will have to remove language system for now :/

I'll add it much later, with improvements

**Comment by usama7628674** [comment]
Yes please i'm busy these days

**Comment by usama7628674** [comment]
Make a PR and i'll review it

**Comment by aamirawan7584** [comment]
hi anyone of can provide me your email? i wanna work with you guys :)

**Comment by sTiKyt** [comment]
@aamirawan7584 just make pull requests.

**Comment by An0nUD4Y** [comment]
Closing Here , Feel Free To reopen.

**Comment by sTiKyt** [comment]
Working on it, check DEV branch.

**Comment by sTiKyt** [comment]
Done, now we should do tests.
