### ISSUE TITLE
Create .json based themes system

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#402]
**Is your feature request related to a problem? Please describe.**
Themes can't be created/added without our approval, they are placed at same place under 1 file.

**Describe the solution you'd like**
System will be able to read .json files from specific folder and import themes.

**Additional context**
WIP

**Comment by sTiKyt** [comment]
Will work on it as soon as i have time

**Comment by An0nUD4Y** [comment]
@sTiKyt , Reopen This issue , whenever you will start working again.
