### ISSUE TITLE
Ngrok server

### ISSUE THREAD

**Issue by Tulasinathreddy** [DarkSecDevelopers/HiddenEye#407]
I have selected the facebook and selected keylogger next I selected a port as 4444, then I selected Ngrok server then nothing shows up.
Please see the screenshot
![Screenshot_2019-10-11-17-56-30-594_com termux](https://user-images.githubusercontent.com/34623886/66651535-e5e46480-ec50-11e9-8446-df846d010aca.png)

**Comment by Siva-Cyber** [comment]
Just turn on your Hotspot and then reconnect it

**Comment by An0nUD4Y** [comment]
No Response. Closing Here..
Feel Free to Reopen.
