### ISSUE TITLE
HiddenEye can't deal with hostname

### ISSUE THREAD

**Issue by DocKali** [DarkSecDevelopers/HiddenEye#408]
I bought a pro version of Ngrok and I try now to deal with hostname. I reserve the hostname I want in Ngrok, no problem. Then I launch a Ngrok session in the Server folder, everything is OK and Ngrok is running.
But when I try to configure HiddenEye, I set up the same port as the one specified in Server's folder and the tool stay stuck with the message : 
[ NGROK SERVER PROCEDURE ]!! 
Any idea why? 
When I set up specific subdomain in Ngrok and then in HiddenEye, everything is OK. It's just with hostnames that the problem occurs.

**Comment by An0nUD4Y** [comment]
@DocKali , Please be more clear about issue.
And also try to share some screenshots.

Describe issue step by step ... 
Then only others can try to solve it.

**Comment by An0nUD4Y** [comment]
No Response , Closing Here..
Feel Free to reopen if required.
