### ISSUE TITLE
Each page on termux created returns 502 error

### ISSUE THREAD

**Issue by darkmidus** [DarkSecDevelopers/HiddenEye#409]
**Describe the bug**

On termux when making webpages I get a 502 error when using them with chrome

**To Reproduce**
1. Choose chrome webpage
2. No keylogger. Serveo. Use a custom url.
3. Use the outputted url in chrome.

**Expected behavior**

Chrome will return 502 http error.

**Screenshots**

![Screenshot_2019-10-14-16-02-37](https://user-images.githubusercontent.com/39868305/66783359-5c75a200-ee9d-11e9-973f-aa7bdf76854f.png)

**Desktop (please complete the following information):**
 - Android, Termux
 - Chrome

**Smartphone (please complete the following information):**
 - Device: Lg Phoenix 4
 - OS: Oreo 8.0.1
 - Browser: Chrome
 
**Additional context**

**Comment by sTiKyt** [comment]
> Expected behavior
A clear and concise description of what you expected to happen.
Chrome will return 502 http error.

Whaaaaat?

**Comment by An0nUD4Y** [comment]
@darkmidus , Looks like serveo dismissed your generated URL.
As serveo implemented techniques to detect malicious URL.
Try with random URL instead.

**Comment by darkmidus** [comment]
Even after choosing random the same thing still happens.

**Comment by An0nUD4Y** [comment]
@darkmidus , Steps you can try.
1) Turn off wifi and try connecting with mobile data.
2) Check your internet connection.
3) Relaunch the script and then try Ngrok or Random Serveo.
4) Last if nothing works , Try Recloning the script.

Please share if Something worked or not.

**Comment by darkmidus** [comment]
Ok, none of them have worked. How would i reclone the script? This isn't just happening to me. This is also happening to my friends phones too.

**Comment by An0nUD4Y** [comment]
@darkmidus , Please Try Again cloning, and also let us know if this issue is still present or not.

**Comment by darkmidus** [comment]
Ok, I'll try.

**Comment by Moltivie** [comment]
@darkmidus it was a servied-sided issue. Sometimes tunneling services shut down phishing websites. May I have you reply back as soon as possible. Otherwise it will be considered as resolved.

Thanks.
