### ISSUE TITLE
Make Custom URL an effective visible URL instead of Ngrok.io ecc

### ISSUE THREAD

**Issue by FabxBs** [DarkSecDevelopers/HiddenEye#410]
While we insert a custom URL, the URL that appears is still from ngrok.io server. To make it more hard to understand if it's a fake link or not, let the generated link be as the custom one that we type, example:
Custom URL www.google.com
NGROK URL: www.google.com instead of the random link.

**Comment by FabxBs** [comment]
Also i want to add a bug report, while the victim opens the link i don't get any info about his IP, IPS, location ecc, this thing works under a VPN/Proxy?

**Comment by FabxBs** [comment]
A feature request: add Yap phishing if possible

**Comment by An0nUD4Y** [comment]
@FabxBs , Create another issue for Feature Request.
And Yupp, 
Getting a similar domain is not possible As how you Explained!!
And 
It's easy to get notify who clicked the click.
Just edit the index file and add this line.
`<script src="ip.php"></script> `

This will load the ip.php file with index file and you will get the ISP/IP and other info.

**Comment by FabxBs** [comment]
Okay, where is located the index file?

**Comment by An0nUD4Y** [comment]
@FabxBs , Most of these are already available.

**Comment by FabxBs** [comment]
@An0nUD4Y  okay, but what about the index file? i want to modify the script to make  the info's appear in the console when the person  clicks the link.

**Comment by An0nUD4Y** [comment]
Closing Here As I have already mentioned the solution above.
