### ISSUE TITLE
Suddnly stopped workin

### ISSUE THREAD

**Issue by Zeptic1337** [DarkSecDevelopers/HiddenEye#411]
Hello so a few days Hiddeneye was working fine and now today, When i try to open Hiddeneye i get this error.

Traceback (most recent call last):
  File "HiddenEye.py", line 13, in <module>
    from Defs.Checks import *
  File "/root/Downloads/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

i have the latest version of wget and did apt-get upgrade and this has still not fixed this issus and was wounding what do i do

**Comment by An0nUD4Y** [comment]
#196
