### ISSUE TITLE
Micr0s0ftpage not delivering username anymore

### ISSUE THREAD

**Issue by donpuzzo-tx** [DarkSecDevelopers/HiddenEye#416]
https://ibb.co/2N4n0y4

**Comment by An0nUD4Y** [comment]
@donpuzzo-tx , Thanks for this issues ,
And also I am aware of this issue. And will fix it soon.

**Comment by donpuzzo-tx** [comment]
is there any time frame you will be fixing it ?

**Comment by An0nUD4Y** [comment]
@donpuzzo-tx , Not Sure About time frame.
If you still want it to get fixed quickly ,
You can sponsor the request by donating.

**Comment by donpuzzo-tx** [comment]
Provide me bitcoin address i will donate, i do not want to use my cc to donate again, your donation BARCODE picture is not working for electrum wallet

**Comment by Stellarize** [comment]
hello i  get this error when running Micr0s0ft 

`Traceback (most recent call last):
  File "HiddenEye.py", line 47, in <module>
    getCredentials(port)
  File "/home/kubutsushimuzan/Bureau/HiddenEye/Defs/Actions.py", line 788, in getCredentials
    ip = re.match('Victim Public IP: (.*.*.*)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
`

it's the only issue i get

**Comment by Moltivie** [comment]
Fixed. PL (#450)
