### ISSUE TITLE
REQUEST: ADD OPTION TO SEND CAPTURED DATA TO EMAIL ACCOUNT. 

### ISSUE THREAD

**Issue by donpuzzo-tx** [DarkSecDevelopers/HiddenEye#417]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DarkSecDevelopers/HiddenEye/issues/417)

Is it possible to make the user information go to email ?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars1.githubusercontent.com/u/55586438?v=4' alt='donpuzzo-tx' width=24 height=24> donpuzzo-tx](https://issuehunt.io/u/donpuzzo-tx) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DarkSecDevelopers/HiddenEye/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Moltivie** [comment]
@sTiKyt @usama7628674 would you label this one and add it on [HiddenEye 1.0 - First Stable Release
](https://github.com/DarkSecDevelopers/HiddenEye/projects/3#card-27191977)
Thanks

**Comment by Moltivie** [comment]
@An0nUD4Y please over [HiddenEye 1.0 - First Stable Release](https://github.com/DarkSecDevelopers/HiddenEye/projects/3) - change this title to be something related to what user asked for. It will be more clear for us to understand what people asked for

**Comment by An0nUD4Y** [comment]
@donpuzzo-tx  ,  Thanks for Request ,
I have added email support but currently in BETA branch ..
Use this command to clone.

For Termux.
`git clone -b Email-Support-BETA-BRANCH-Termux-Support https://github.com/darksecdevelopers/HiddenEye`
For Linux
`git clone -b Email-Support-BETA-BRANCH  https://github.com/darksecdevelopers/HiddenEye`

**Comment by An0nUD4Y** [comment]
ADDED TO MASTER BRANCH ..
CLOSING HERE..
FEEL FREE TO REOPEN.
