### ISSUE TITLE
Please Add go daddy page also

### ISSUE THREAD

**Issue by donpuzzo-tx** [DarkSecDevelopers/HiddenEye#419]
**Is your feature request related to a problem? Please describe.**
Go Daddy Page 

**Describe the solution you'd like**
Add godaddy page and also email function

**Comment by donpuzzo-tx** [comment]
i take it that you don't want to add Godaddy Phishing Page Because i didn't pay for it....Well you tool is trash anyway.....its Never Stable and it keeps falling apart

GoodLuck on your Trash tool Mate

**Comment by An0nUD4Y** [comment]
@donpuzzo-tx , 
Check #569
