### ISSUE TITLE
what does cloudflare protection fake page means?

### ISSUE THREAD

**Issue by webmojoo** [DarkSecDevelopers/HiddenEye#420]
Do you want to add a cloudflare protection fake page? What does that really mean and should i say yes or no?

**Comment by An0nUD4Y** [comment]
@webmojoo , 
For Actual CloudFare Working [Check This](https://support.cloudflare.com/hc/en-us/articles/200170026-What-does-enabling-CloudFlare-Hotlink-Protection-do-)

But As mentioned its Just a Fake Cloned Page Similar to CloudFare, Adding this page to any phishing
module will do these Things.
1) Whenever Victim will open the Link , The victim will encounter first with this Cloudfare Protection Page.
2) This Sometimes tricks victim to think that the Phishing Page is Legitimate. As most of Popular Legitimate Sites used it.
3) Adding This Page increases the Success Rate of Phishing Attacks.

INSPIRED FROM (Smart Logger Option)  https://grabify.link
