### ISSUE TITLE
Phishing URL text is: Binary file link.url matches

### ISSUE THREAD

**Issue by saurabhs2t** [DarkSecDevelopers/HiddenEye#426]
Hi, whenever I am trying to generate an URL using these servers:
 [2] **Serveo**
 [3] **Localxpose**
 I am always getting the link as below-
**"Binary file link.url matches"**.

![image](https://user-images.githubusercontent.com/42425945/68282387-93ae2c00-00b4-11ea-81ed-43987c0187eb.png)

Also, when trying to use the below server-
[1] **Ngrok**

I am getting this error-

![image](https://user-images.githubusercontent.com/42425945/68283038-be4cb480-00b5-11ea-9884-7d3b15db1733.png)

So please suggest if there any solution. Thanks in advance.

**Comment by An0nUD4Y** [comment]
@saurabhs2t , Delete the link.url file from Hiddeneye Directory.
This will surely fix this problem.

And in case of Ngrok,
Try not adding keylogger.

**Comment by saurabhs2t** [comment]
@An0nUD4Y, thanks  for the reply. The issue has been resolved.

**Comment by saurabhs2t** [comment]
But for Ngrok,
I am not using the keylogger, but the issue still there. 

![image](https://user-images.githubusercontent.com/42425945/68357717-2c928500-0151-11ea-8f82-23b3ae0477e4.png)

**Comment by An0nUD4Y** [comment]
@saurabhs2t , Which page you are using.
Read the Tunnel Expired cause Carefully.

This issues many times described in closed issues.

It's happening b/c
1) whether you have added keylogger .
2) Or you are using template which is sending multiple Requests back to your host for various files like html , CSS, and images and also js files.
3) Or Your connection timeout completed.

As we are using free plan , These are obvious reasons.
Thats why we introduced 2  more alternatives.

But if you still wants to use Ngrok try Purchasing the Paid version of Ngrok.
And just add authoken of Ngrok to Server/Ngrok file.

**Comment by An0nUD4Y** [comment]
Closing Here Feel Free to Open Again.
