### ISSUE TITLE
Every host subdomain error

### ISSUE THREAD

**Issue by Jsikkema1** [DarkSecDevelopers/HiddenEye#429]
I've tried custom url for serveo and localxpose in termux and kali linux and i keep getting this
![Screenshot_20191108_164303_com termux](https://user-images.githubusercontent.com/51862581/68489465-6fcf1f80-0247-11ea-92d5-725a88e7fb51.jpg)

**To Reproduce**
1. Every site wont work but ok. Lets do google
2. No keylogger no cloudflare (also with them error) 
3. Redirect google.com
4. Serveo 
5. Custom
6. Everything that i type wont work 
7. ERROR!! 
**Expected behavior**
when i first tried it it workerd but 1 dat later i keep getting this error. 

  kali linux AND termux

**Comment by An0nUD4Y** [comment]
@Jsikkema1 , You can't get a subdomain named as 'google' ..
And also there's a obvious reasons for that.
1) Serveo or Localxpose will never assign you a subdomain which looks suspicious.
As that in your case , you used Google as subdomain.
2) Such subdomain are easily detected as malicious and Serveo/localxpose will never assign you such subdomain.

**Comment by Jsikkema1** [comment]
Thx for your reaction, but even if i name it cheese or something it still wont work.
