### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by DocKali** [DarkSecDevelopers/HiddenEye#431]
Hi,
I just made a git pull to update the tool, now I have errors I didn't have before. 
When I test the tool (in Kali) I setup it up with no keylogger, no cloudflare page.
If I choose Ngrok, I have a crash when I click the provided link :
```
Traceback (most recent call last):
  File "HiddenEye.py", line 47, in <module>
    getCredentials(port)
  File "/opt/HiddenEye/Defs/Actions.py", line 696, in getCredentials
    ip = re.match('Victim Public IP: (.*.*.*)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
And when I choose localexpose, I obtain that instead of the link to provide to the target : 
`LOCALXPOSE URL: Binary file link.url matches`

In all tests URL are random URL and selected phishing page is Microsoft.
Any idea where the problem comes from? 
Thanks!

**Comment by Moltivie** [comment]
@DocKali could you verify me, if still have this issue?

It is working fine for me. Make sure you update your local repo.

**Comment by Moltivie** [comment]
> @DocKali could you verify me, if you still have this issue?
> 
> It is working fine for me. Make sure you update your local repo.

**UPDATE:**
localxpose tunnel service working fine at the moment

**Comment by Moltivie** [comment]
Fixed. PL (#450)
