### ISSUE TITLE
Localhost exposing service 

### ISSUE THREAD

**Issue by endbehavi0r** [DarkSecDevelopers/HiddenEye#432]
[Serveo](https://www.serveo.net) has recently been temporarily disabled due to phishing. I would suggest using [Localtunnel](https://localtunnel.github.io/www/) because other services like Ngrok and LocalXpose don't support custom subdomains. The script can implement npm to install the service.

**Comment by Moltivie** [comment]
@An0nUD4Y consider to close this one too. Thanks
