### ISSUE TITLE
ngrok, serveo bugging out

### ISSUE THREAD

**Issue by IlyHo** [DarkSecDevelopers/HiddenEye#438]
Stuck on this step. Had to exit after waiting for 30 minutes for each

![Screenshot from 2019-11-15 10-31-38](https://user-images.githubusercontent.com/57727414/68928615-7cc4a500-0758-11ea-8539-65ac37f074a6.png)

![Screenshot from 2019-11-15 10-33-31](https://user-images.githubusercontent.com/57727414/68928697-bdbcb980-0758-11ea-883a-b96925ca99f5.png)

**Comment by An0nUD4Y** [comment]
Check #439
