### ISSUE TITLE
LocalXpose stuck after selecting random url 

### ISSUE THREAD

**Issue by thatspix** [DarkSecDevelopers/HiddenEye#439]
I have installed Userland. Did all the setup. 
I know LocalXpose needs a paid account for custom subdomain so I selected Random URL. But that's not the only case, same thing happens with Serveo and Ngrok. And selecting custom subdomain ends up in error saying the domain is invalid or already in use.
No keylogger, no fake cloudflare page.

1. Go to 'localxpose as server'
2. Click on 'Random URL'
3. See error

Should give a URL

**Smartphone (please complete the following information):**
 - Device: OnePlus 5 
 - OS: Android 9
 - Browser: Chrome
 - Version: v78.xx (stable)

I tried Serveo and Ngrok on termux, same issue. I did a fresh install too but that didn't resolve the issue. 

Any help is appreciated!
![Screenshot_20191115-171407](https://user-images.githubusercontent.com/50486055/68941688-956ea280-07cc-11ea-8628-d1e19fc7ce12.jpg)

**Comment by An0nUD4Y** [comment]
@thatspix , I am aware of these issues .
We are trying to add more Tunnelling options.
As we know that getting Tunnelling services for free is too Hard.
We will add paid options also for Tunnelling.
Currently their is no solutions ..
But still I can suggest you some points.
1) Try using localxpose in Different OS like in Debian or Kali Linux.
2) Try Running localxpose manually from folder (Server/loclx) in userland or Linux.
3) Try Using paid version of NGROK. Check  https://ngrok.com
4) Same for localxpose (Check localxpose paid ) https://localxpose.io
5) Wait until Serveo cames Online Again.
6) Wait for Next update from us As we are about to add Localtunnel as an option. (Check Pull Request #436 
7) Try Some other port Forwarding Options manually.
