### ISSUE TITLE
localtunnel package install error

### ISSUE THREAD

**Issue by sh1va73** [DarkSecDevelopers/HiddenEye#444]
When installing after the new update:
LOCALTUNNEL(Tunneling Service) Packages

This gives me an error it can not be installed. Any idea what is causing this?

**Comment by Moltivie** [comment]
@sh1va73 can you post a screenshot? That might help us understand better the issue.

Thanks.

**Comment by sh1va73** [comment]
Not sure what was wrong but after trying again it is working fine now. thanks for getting back at me.

**Comment by Moltivie** [comment]
@sh1va73 could you run these commands and paste the output here. Thanks

```python
import platform, os
print(platform.system(), os.name, platform.release())
```
