### ISSUE TITLE
Error while runnig HiddenEye.py

### ISSUE THREAD

**Issue by joseph-sebastian720** [DarkSecDevelopers/HiddenEye#445]
While running hiddeneye,py, its showing erros

[*] LocalTunnel Binary File Not Found !!
[*] Downloading LocalTunnel...
Traceback (most recent call last):
  File "HiddenEye.py", line 27, in <module>
    checkbinaryLT()
  File "/root/tools/HiddenEye-master/Defs/Checks.py", line 84, in checkbinaryLT
    urlretrieve(url, "lt-linux.zip")
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Moltivie** [comment]
Could try again and inform me back.

Thanks.

**Comment by XiuYee** [comment]
I have the same problem as well XD, I recently have tried to install it as well.

**Comment by Moltivie** [comment]
@XiuYee paste a screenshot.

Thanks.

**Comment by XiuYee** [comment]
https://i.imgur.com/PX3ZXf0.png

**Comment by thatspix** [comment]
I updated to v0.5.0 and I have the same issue. I tried adding the binary file Manually but no luck with that :/
![Screenshot_20191117-003258](https://user-images.githubusercontent.com/50486055/68997946-09df3980-08d2-11ea-90c9-d21bfa44f91c.jpg)

**Comment by thatspix** [comment]
@Moltivie

**Comment by Moltivie** [comment]
The bug has been fixed on PL (#446). You may want to wait until it is going to be merged.

**Comment by An0nUD4Y** [comment]
If you still gets the issue.
Follow these commands to do it manually.

Goto Hiddeneye Directory..

And use this command
First install wget
`apt install wget && pkg install wget 
`
`wget Https://wa4e.com/downloads/lt-linux.zip && unzip lt-linux.zip && rm lt-linux.zip && mv lt* lt && mv lt Server/lt `

**Comment by An0nUD4Y** [comment]
And rerun the script..

**Comment by XiuYee** [comment]
Well I did the wget thingy and now it works....

**Comment by joseph-sebastian720** [comment]
> If you still gets the issue.
> Follow these commands to do it manually.
> 
> Goto Hiddeneye Directory..
> 
> And use this command
> First install wget
> `apt install wget && pkg install wget `
> `wget Https://wa4e.com/downloads/lt-linux.zip && unzip lt-linux.zip && rm lt-linux.zip && mv lt* lt && mv lt Server/lt `

That worked

**Comment by Moltivie** [comment]
@joseph-sebastian720 that would work as for now. It was a bug that has been fixed. You may to update your local repo.
