### ISSUE TITLE
Local Tunnel issue

### ISSUE THREAD

**Issue by thatspix** [DarkSecDevelopers/HiddenEye#447]
I added the Local Tunnel binary from the site. Extracted and renamed to 'lt' and pasted in the 'Server' folder and set the permissions of the file
Running ./HiddenEye.py works fine until the selection of server
I selected the package version of Local Tunnel. Went fine
I noticed an issue when selecting the URL. Random URL didn't work for me. And blank url worked once only. After that it gave me error

I'm using HiddenEye on Userland App with Kali Linux as the distro
I have attached the screenshot of the error. I'm willing to help 😄
![Screenshot_20191117-012048](https://user-images.githubusercontent.com/50486055/68998451-82e18f80-08d8-11ea-8a97-3b30b843d096.jpg)

**Comment by thatspix** [comment]
I just tested Local Tunnel. Idk what happened. I did the exact same steps and it works for Random URL. Still doesn't work for Custom though

**Comment by Moltivie** [comment]
@thatspix you may want to give a look [here](https://github.com/DarkSecDevelopers/HiddenEye/issues/439#issuecomment-554337918).

Also giving a look [here](https://github.com/localtunnel/localtunnel/issues/258#issuecomment-404267919), it seems that there are some issues on LocalTunnel servers.

**Comment by Moltivie** [comment]
Secondly I fixed the bug where you had to download and copy/paste the file manually. Here's the PL (#446), you may want to wait until it is going to be merged.

Thanks.

**Comment by thatspix** [comment]
Alright. So when the project is updated, do I have to delete the file I added or is it okay if I do nothing ? Kudos to the whole team.

**Comment by Moltivie** [comment]
You have just to update your cloned repo issuing this command: `$ git pull origin master`

This will sync your master to the central repo and if new branches are pushed to the central repo it will also update your clone copy.

**Comment by thatspix** [comment]
Thanks man! Appreciate the quick support 😄
Also Local Tunnel seem more reliable than others albeit when it works 😂. It doesn't time out quite quickly as others

**Comment by Moltivie** [comment]
Yeah, actually tunneling services use to turn down quickly due to phishing.
