### ISSUE TITLE
Waiting for victim interaction after that error comes

### ISSUE THREAD

**Issue by joseph-sebastian720** [DarkSecDevelopers/HiddenEye#448]
...............................
 {1}[{0} GETTING PRESSED KEYS {1}]{1}:
 {0}{2}{1}
Traceback (most recent call last):
  File "./HiddenEye.py", line 50, in <module>
    getCredentials(port)
  File "/root/tools/HiddenEye-master/Defs/Actions.py", line 940, in getCredentials
    writeLog(' {1}[{0} GETTING PRESSED KEYS {1}]{1}:\n {0}{2}{1}').format(
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by Moltivie** [comment]
@joseph-sebastian720 how you would reproduce the error?

**Comment by Moltivie** [comment]
@joseph-sebastian720 bug fixed. Wait until it is going to be merged and then just run a `git pull`
