### ISSUE TITLE
Keylogger error

### ISSUE THREAD

**Issue by JamesKimble02** [DarkSecDevelopers/HiddenEye#453]
I get the error below after entering my fake login details into a phishing page. Please help or fix.

{1}[{0} GETTING PRESSED KEYS {1}]{1}:
 {0}{2}{1}
Traceback (most recent call last):
  File "HiddenEye.py", line 50, in <module>
    getCredentials(port)
  File "/root/hiddeneye/Defs/Actions.py", line 940, in getCredentials
    writeLog(' {1}[{0} GETTING PRESSED KEYS {1}]{1}:\n {0}{2}{1}').format(
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by Moltivie** [comment]
Resolving

**Comment by Moltivie** [comment]
@JamesKimble02 everything is working fine. You may want to update your local repo!
Also I recommend doing that as there are some bugs. They have been already fixed, on PL (#450).
You may want to wait until it's going to be merged into the main branch.

Thanks.

(Here's below a proof of keylogger working.)

![image](https://user-images.githubusercontent.com/14014692/69015046-7b7dbd00-0990-11ea-9828-da62d074d832.png)

**Comment by Moltivie** [comment]
If further help or questions, feel free to re-open.

**Comment by JamesKimble02** [comment]
how would i update my local repo?

**Comment by Moltivie** [comment]
> how would i update my local repo?

have you forked or directly cloned the repo?

**Comment by JamesKimble02** [comment]
I directly cloned it

**Comment by Moltivie** [comment]
> I directly cloned it

Give this command: `$ git pull`

**Comment by JamesKimble02** [comment]
Hiya, sorry for the late relpy. I just executed the command and it tells me its up to date however I am still getting the same error. Are you able to help?

**Comment by Moltivie** [comment]
Give this command: `$ git remote -v` and screenshot the result.

**Comment by JamesKimble02** [comment]
![image](https://user-images.githubusercontent.com/57877485/69015971-7861dd00-094e-11ea-88ad-0c8be070f389.png)

**Comment by Moltivie** [comment]
Try again with this `$ git pull origin master`

**Comment by JamesKimble02** [comment]
![image](https://user-images.githubusercontent.com/57877485/69015994-ead2bd00-094e-11ea-8516-82ffda1cd875.png)

**Comment by JamesKimble02** [comment]
I re-run the program and amstill getting the same error. Could it be because i renamed the directory?

**Comment by Moltivie** [comment]
It doesn't matter. Let me see if you're actually at the last commit.
Type: `$ git log --oneline`

**Comment by JamesKimble02** [comment]
![image](https://user-images.githubusercontent.com/57877485/69016027-42712880-094f-11ea-840e-12c6b43fbf84.png)
![image](https://user-images.githubusercontent.com/57877485/69016030-4dc45400-094f-11ea-8dba-92cc02f39a62.png)

**Comment by Moltivie** [comment]
As I said the fixes are there on PL #450, you may want to wait until it will be merged. Otherwise you could try to download the PL by yourself on a new local branch you are going to create.

**Comment by JamesKimble02** [comment]
OK. I think I'll wait. Thank you so much for your help!! Any ETA for #450?

**Comment by Moltivie** [comment]
< 12h.

**Comment by JamesKimble02** [comment]
OK. Again, I cannot thank you enough for your support. Response times were great!! Thanks so much.

**Comment by Moltivie** [comment]
No problem man! Do not hesitate to ask questions.
If you have ideas or improvements, they will be welcomed!

I would like also to get a reply back from you if after the update. you'll face problems.

**Comment by Moltivie** [comment]
@JamesKimble02 you may want to update your local branch. :)
You can download _v.0.5.1_.

**Comment by JamesKimble02** [comment]
Works great now. Thanks.

**Comment by Moltivie** [comment]
👍🏽

**Comment by Moltivie** [comment]
👍
