### ISSUE TITLE
Can't open hiddeneye 

### ISSUE THREAD

**Issue by jeffinss** [DarkSecDevelopers/HiddenEye#454]
![Screenshot_20191119-084953](https://user-images.githubusercontent.com/47373652/69132089-695b6600-0ad9-11ea-880c-26d7882cdce3.jpg)
Showing this while opening hiddeneye 
Please help me 
Thanks in advance🖤

**Comment by An0nUD4Y** [comment]
Have you followed the instructions ..
Please follow them.
BTW
Use `pip3 install wget`

**Comment by jeffinss** [comment]
Thank you ❤️❤️

**Comment by sTiKyt** [comment]
#178
