### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Feelingloved** [DarkSecDevelopers/HiddenEye#457]
so i got this problem while tryina install it and im new to kail linux here is a 

screenshot- http://prntscr.com/q0xuqi

Please help me if you know how to fix this problem <3

**Comment by Moltivie** [comment]
Have you tried to pull the upstream master again? @An0nUD4Y made some changes. Try get them and let me know back

**Comment by Feelingloved** [comment]
@Moltivie i dont really know how to do that I'm knew to kali linux

**Comment by Moltivie** [comment]
Run the command `$ git remote -v` and post here the screenshot.

**Comment by Feelingloved** [comment]
@Moltivie okay I'll try that

**Comment by Feelingloved** [comment]
@Moltivie there http://prntscr.com/q0y7mw

**Comment by Feelingloved** [comment]
what do i do next

**Comment by Moltivie** [comment]
Give the command `$ git pull origin master` to get the latest commits and then try again executing the script.

**Comment by Feelingloved** [comment]
okay thank you sir

**Comment by Feelingloved** [comment]
thanks i think it works good now

**Comment by Moltivie** [comment]
Ok

**Comment by sTiKyt** [comment]
@Moltivie please rename it to understand Issue
