### ISSUE TITLE
HiddenEye not showing the link

### ISSUE THREAD

**Issue by aaryansah12** [DarkSecDevelopers/HiddenEye#458]
Serveo is not working when I tap at random url it shows nothing it doesn't give url and when I tap at custom after giving every misspelled word it says the word is invalid or occupied by someone

**Comment by aaryansah12** [comment]
![Screenshot_2019-11-25-08-10-48-79_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/58156425/69508243-3989e380-0f5b-11ea-8fb9-6f11ff520444.png)

**Comment by usama7628674** [comment]
@aaryansah12 Serveo is down.Use other service.
