### ISSUE TITLE
Not showing link

### ISSUE THREAD

**Issue by kundan-jadhav2001** [DarkSecDevelopers/HiddenEye#459]
I am working in termuxz on my Samsung phone.
But every time i select instagram options the link doesn't show. Only black page there which blinks only.
![Screenshot_20191130-142632_Termux](https://user-images.githubusercontent.com/52217745/69898322-05109000-137e-11ea-8930-8387dfc669c9.jpg)

**Comment by flane21** [comment]
I have the same problem :(

**Comment by atroxGhost** [comment]
Same

**Comment by An0nUD4Y** [comment]
Serveo is Down( https://serveo.net ) currently try other Tunnelling options.

**Comment by An0nUD4Y** [comment]
Check #460

**Comment by flane21** [comment]
> Serveo is Down( https://serveo.net ) currently try other Tunnelling options.

none of them works
