### ISSUE TITLE
All Tunnels Instagram Not Showing URL

### ISSUE THREAD

**Issue by T0rkman** [DarkSecDevelopers/HiddenEye#460]
Instagram Tabs not working. I tried all Tunnels but Not Come a URL (Link).
Ngrok is a not working. Although I waited for a while, the URL (link) did not come.
https://i.hizliresim.com/gPJQBR.png
https://i.hizliresim.com/4pvN54.png
https://i.hizliresim.com/M13jrQ.png
Serveo is a not working. Although I waited for a while, the URL (link) did not come. Random and Custom URL select and is not working.
https://i.hizliresim.com/XbrZ5R.png
https://i.hizliresim.com/9YPjO3.png
https://i.hizliresim.com/LvWjLG.png
https://i.hizliresim.com/r0oG7N.png
https://i.hizliresim.com/7Brj4W.png
LocalxPose is a not working. Although I waited for a while, the URL (link) did not come. Random and Custom URL select and is not working.
https://i.hizliresim.com/bvdPWd.png
https://i.hizliresim.com/5N1jBj.png
https://i.hizliresim.com/00o3Q9.png
Also program start and coming a screen. I said (Y) Yes.
https://i.hizliresim.com/9YPjn5.png
https://i.hizliresim.com/AOdjpp.png
I am getting an error page when loading. So Tried the 5. option.
https://i.hizliresim.com/JVyjvo.png
https://i.hizliresim.com/QPoj93.png
But again not worked. Instagram Tabs are Not work the option. Please Fix the problem. Thank you from now. I wish have a nice day.

**Comment by An0nUD4Y** [comment]
These are common issues..
Try cloning Termux-Support-v0.5.1
Use command.
`git clone -b Termux-Support-Branch-v0.5.1 https://github.com/DarkSecDevelopers/HiddenEye `

**Comment by T0rkman** [comment]
should I delete the hiddeneye and write this code before writing this code?
otherwise, will I paste the code and load the hiddeneye without deleting it?
Code is " git clone -b Termux-Support-Branch-v0.5.1 "

**Comment by An0nUD4Y** [comment]
That's all is a single command ..
You can clone in different directory
Use 
`mkdir hiddeneye0.5.1 && cd hiddeneye0.5.1 `
And then use above command to clone

**Comment by T0rkman** [comment]
So I did what you said. 
https://i.hizliresim.com/7Br9Qm.png
But likewise program start and coming a screen. I said (Y) Yes.
https://i.hizliresim.com/P7Z8Gv.png
https://i.hizliresim.com/gPJdbL.png
after than tried Instagram Tabs again tried for all tunnels. But not came a URL (Link).
what do you think should I delete and install the program? because I can't think of a different solution.

**Comment by An0nUD4Y** [comment]
#464 
Don't Use serveo its Down currently
check Serveo.net

#461 
You have cloned wrong branch. 
Their is a dedicated termux branch 
Use above specified command to clone termux branch.

@T0rkman 

You should try installing localtunnel packages manually for termux.
Then only you can use localtunnel package option as server.
And yupp 
Other options like.
* Serveo - its down currently
* Localxpose - Do not support android termux (you can try it in userland app check instructions)
* Ngrok - Need paid version as free version have limitations
* Localtunnel Binary -- its buggy and sometime fails to load.
* Localtunnel Package -- it creates issue only during installation which can be also done manually of failed by script.  https://github.com/localtunnel/localtunnel/blob/master/README.md
Or check Defs/checks.py for commands to install local tunnel manually.

**Comment by olawalemichael** [comment]
I installed the localtunnel but am still getting errors using option 4 and 5 ,it's not going forward whenever I click on enter 
![Screenshot_20191205-165006](https://user-images.githubusercontent.com/58562709/70251490-e811fd80-177f-11ea-9224-731502200e92.png)

**Comment by An0nUD4Y** [comment]
Try #472

**Comment by An0nUD4Y** [comment]
Create new issue.
