### ISSUE TITLE
Run as sudo

### ISSUE THREAD

**Issue by Hamadahack5** [DarkSecDevelopers/HiddenEye#461]
![Screenshot_20191202_223651_com termux](https://user-images.githubusercontent.com/57997016/69993331-422e7b00-1554-11ea-8413-a4dca1435ee6.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Moltivie** [comment]
You should run the command as sudo! `$ sudo python3 <scriptname.py>`.
A clear and concise info message of what you have been returned with.

**Comment by An0nUD4Y** [comment]
Cloned wrong branch..
Their is a dedicated termux branch .
Check #460

**Comment by Hitesh-Patil-creator** [comment]
try chmod777
