### ISSUE TITLE
Sudo permission denied

### ISSUE THREAD

**Issue by bapji** [DarkSecDevelopers/HiddenEye#463]
![Screenshot_20191205-031203](https://user-images.githubusercontent.com/58431159/70184337-a7799c00-170d-11ea-825b-3fc8bafa30c1.jpg)
I give su permission to sudo but still permission denied please let me if i'm doing anything worng..
Thanks

**Comment by Moltivie** [comment]
What are you even typing in there...?

**Comment by bapji** [comment]
I tried python HiddenEye.py
Python3 HiddenEye.py

But not working
I think i'm typing wrong  coomand please correct me thanks for ur kind reply

**Comment by bapji** [comment]
> What are you even typing in there...?

I tried python HiddenEye.py
Python3 HiddenEye.py

But not working
I think i'm typing wrong coomand please correct me thanks for ur kind reply

**Comment by Moltivie** [comment]
Wrong command and wrong spelling.... Check #461 anyway

**Comment by sTiKyt** [comment]
Use `sudo python HiddenEye.py` instead
