### ISSUE TITLE
Link not generation

### ISSUE THREAD

**Issue by bapji** [DarkSecDevelopers/HiddenEye#464]
![Screenshot_20191205-035216](https://user-images.githubusercontent.com/58431159/70186859-d9d9c800-1712-11ea-9941-b382111fdefb.jpg)
Phishing link not generating i trid with root and nonroot phn
Everything is running nice but main thing is missing
I tried  all server
1]Ngrok
  [2]Serveo
 [3]Localxpose
 [4]Localtunnel (Package Version)
 [5]Localtunnel (Binary Version)[Buggy]'
 trying from yesterday please checkout 
Thanks

**Comment by An0nUD4Y** [comment]
#460
