### ISSUE TITLE
Server permission denied

### ISSUE THREAD

**Issue by bapji** [DarkSecDevelopers/HiddenEye#466]
![Screenshot_20191205-131207](https://user-images.githubusercontent.com/58431159/70214350-53000c00-1761-11ea-85a4-e414c01c3459.jpg)

![Screenshot_20191205-132306](https://user-images.githubusercontent.com/58431159/70215143-cf471f00-1762-11ea-9819-41d69e651d4a.jpg)
![Screenshot_20191205-132216](https://user-images.githubusercontent.com/58431159/70215144-cfdfb580-1762-11ea-87fc-e73a2a0b6903.jpg)
![Screenshot_20191205-132446](https://user-images.githubusercontent.com/58431159/70215145-cfdfb580-1762-11ea-9555-ef2c8b25141d.jpg)

I install localTunnel manually
Please help me to figure out this randam and manually in both  i'm getting same error
Thanks

**Comment by An0nUD4Y** [comment]
@bapji  
Use this command ..
`chmod 777 * -R`

**Comment by bapji** [comment]
> @bapji
> Use this command ..
> `chmod 777 * -R`

Bro wer i have 
I' m beginner
Thanks

**Comment by bapji** [comment]
> > @bapji
> > Use this command ..
> > `chmod 777 * -R`
> 
> Bro wer i have to put these command
> I' m beginner
> Thanks

Bro i gave  777 permission localTunnel manually but error coming

**Comment by bapji** [comment]
![Screenshot_20191205-140949](https://user-images.githubusercontent.com/58431159/70218579-3798ff00-1769-11ea-9401-c40f3e9b49b4.jpg)
Local Tunnel


![Screenshot_20191205-141032](https://user-images.githubusercontent.com/58431159/70218605-47b0de80-1769-11ea-9974-aa188adb2343.jpg)
Hidden eye

![Screenshot_20191205-141323](https://user-images.githubusercontent.com/58431159/70218881-dcb3d780-1769-11ea-9a17-8a6555106c0f.jpg)

![Screenshot_20191205-141353](https://user-images.githubusercontent.com/58431159/70218909-ed644d80-1769-11ea-91c3-f16eb358528f.jpg)

![Screenshot_20191205-141435](https://user-images.githubusercontent.com/58431159/70218951-fead5a00-1769-11ea-85e9-cba79ab9c2a6.jpg)

![Screenshot_20191205-141450](https://user-images.githubusercontent.com/58431159/70218979-0a991c00-176a-11ea-8c42-6a659ef82d73.jpg)

![Screenshot_20191205-141457](https://user-images.githubusercontent.com/58431159/70219038-23a1cd00-176a-11ea-80ba-6dcfa8cab77d.jpg)

![Screenshot_20191205-141509](https://user-images.githubusercontent.com/58431159/70219039-23a1cd00-176a-11ea-9908-c44e20f2e42e.jpg)

Everything is in screen please help me

**Comment by An0nUD4Y** [comment]
You have not given permission to server folder as server folder contain the executables.
use 
`chmod 777 * -R`

Here -R is for reccurssion...
And also 
try this command if you are able to launch localtunnel
`lt --help`

**Comment by bapji** [comment]
> You have not given permission to server folder as server folder contain the executables.
> use
> `chmod 777 * -R`
> 
> Here -R is for reccurssion...
> And also
> try this command if you are able to launch localtunnel
> `lt --help`

Ok bro thanks going to try
