### ISSUE TITLE
URL not showing

### ISSUE THREAD

**Issue by olawalemichael** [DarkSecDevelopers/HiddenEye#467]
URL isn't generating,please how to fix issue ASAP .I really need your help

**Comment by An0nUD4Y** [comment]
@olawalemichael , Please Provide more information..

**Comment by DARHAKER** [comment]
![Screenshot_2019-12-19-20-34-01](https://user-images.githubusercontent.com/18514948/71222571-0529ee80-229f-11ea-91be-858eaf54f4f4.png)
No muestra el link o no se genera yo uso termux anterior mente funcionaba bien pero desinstale por un tiempo y instale termux y HiddenEye nuevamente y no funciono

**Comment by cyberbully01** [comment]
No link genered hays

**Comment by DARHAKER** [comment]
Porque no se generar e intentado con ngrok 
También serveo

**Comment by An0nUD4Y** [comment]
Server is down , Use other tunneling options.
