### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by bapji** [DarkSecDevelopers/HiddenEye#468]
![Screenshot_20191206-004104](https://user-images.githubusercontent.com/58431159/70266740-15cc6600-17c3-11ea-8dfa-9898e0a03653.jpg)

Getting this error while installing Localtunnel (i'm root member i also i
 have sudo) and when  i 'm trying  Localtunnel (Binary Version)[Buggy]

Getting this please  reply thanks ...
⬇️

![Screenshot_20191206-005622](https://user-images.githubusercontent.com/58431159/70267202-f41fae80-17c3-11ea-98bc-e21036761907.jpg)

**Comment by An0nUD4Y** [comment]
@bapji , Try reinstalling Termux App their must be some privileges issues..
As Script is working correctly in my case..
Closing Here Feel free to Reopen.
