### ISSUE TITLE
Getting Pressed Keys - Unidentified Unidentified

### ISSUE THREAD

**Issue by prince812** [DarkSecDevelopers/HiddenEye#469]
**Hey, How can I solve This ?**
raceback (most recent call last):
  File "./HiddenEye.py", line 50, in <module>
    getCredentials(port)
  File "/home/viren/HiddenEye/Defs/Actions.py", line 916, in getCredentials
    ip = re.search("Victim Public IP: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[\n,\r]", lines).group(1)
AttributeError: 'NoneType' object has no attribute

**Comment by Croos3r** [comment]
Have the same issue :(

**Comment by ultrainstinct07** [comment]
just install all requirements and boom your problem solved.
sudo pip3 install -r requirements.txt

**Comment by prince812** [comment]
its still not working it shows requirement already satisfied...

![1](https://user-images.githubusercontent.com/55912480/70987438-eb917700-20e5-11ea-8973-4aa863d661b0.png)

**Comment by prince812** [comment]
**Now how can solve this issue :(**

![Screenshot from 2019-12-17 16-25-47](https://user-images.githubusercontent.com/55912480/70989716-1d0c4180-20ea-11ea-9e74-aacf6859e3de.png)

**Comment by An0nUD4Y** [comment]
@prince812  it's a known bug...
We will fix it soon...
And yupp..
Even after occurring error you can still use the generated link.
And can find all the credentials in /server/captureddata or /server/www/usernames.txt

**Comment by gjhami** [comment]
This appears to be occurring when the NGROK server option is selected and the keylogger is used. Any additional information is also appreciated eg. which template was used, was cloudflare used, which port is used, is captured data being emailed, is LOCALTUNNEL installed, etc. Also was the connection to Hiddeneye (if one was made) made using the localhost address or the ngrok address. I attempted to duplicate with the following options: LOCALTUNNEL not installed, template number 12, keylogger used, cloudflare not used, captured data not emailed, port 5555, redirect link used. I visited the link on a browser with javascript enabled and everything worked as expected.

**Comment by An0nUD4Y** [comment]
@gjhami , It issue occurs when we opens the url in same machine in which the attacker is hosting pages.
This issues is causing due to the handling of ip address grabed by ip.php file.
You can reproduce it by using 127.0.0.1:{port} in same machine after launching attack also try it multiple time as it rarely throws error like this.

**Comment by risky-chokra** [comment]
> @gjhami , It issue occurs when we opens the url in same machine in which the attacker is hosting pages.
> This issues is causing due to the handling of ip address grabed by ip.php file.
> You can reproduce it by using 127.0.0.1:{port} in same machine after launching attack also try it multiple time as it rarely throws error like this.

No it's not, I open the generated link in another phone but I still face the same error

**Comment by sTiKyt** [comment]
This issue was created for other problem. If you have new problem - create NEW Issue. @prince812
