### ISSUE TITLE
Can't install local tunnel (package version)

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [DarkSecDevelopers/HiddenEye#472]
Again and again it shows this message.

[ERROR]: LocalTunnel packages haven't been installed correctly...
                                                                
Press Enter To Go Back To installation..

What I need to do?

**Comment by An0nUD4Y** [comment]
@0x-MRNOBODY-x0 , install that manually..
For Linux -
`apt-get -y update;apt -y install nodejs npm;npm cache clean -f;npm i -g n;n stable;npm i -g localtunnel`

For Termux-
`apt-get -y update;apt -y install nodejs npm;npm cache clean -f;npm i -g n;n stable;npm i -g localtunnel-termux`

**Comment by An0nUD4Y** [comment]
@0x-MRNOBODY-x0 , i will fix it on next commits..

**Comment by 0x-MRNOBODY-x0** [comment]
Ok. Thank you for the reply.
I'll try it.

**Comment by 0x-MRNOBODY-x0** [comment]
It's working. Thankyou.

**Comment by 0x-MRNOBODY-x0** [comment]
I have to ask something. what is the 
' CLOUDFARE PROTECTION ' ?.  And what for Recipient email?

**Comment by 0x-MRNOBODY-x0** [comment]
Hey, localxpose and local tunnel are not genarating the url.

**Comment by An0nUD4Y** [comment]
@0x-MRNOBODY-x0 
Share screenshot...
You should try it Manually for localtunnel.
Use these steps for localtunnel.
1) Open new terminal and use these commands.
Here 1234 is the port we choose in HiddenEye.

`lt -p 1234`

**Comment by 0x-MRNOBODY-x0** [comment]
I tried the command. But it saying the tunnel server is offline.
![Screenshot_2019-12-19-20-16-12](https://user-images.githubusercontent.com/45472892/71182746-acf1ed00-229c-11ea-848c-806ab1299d30.png)


> @0x-MRNOBODY-x0
> Share screenshot...
> You should try it Manually for localtunnel.
> Use these steps for localtunnel.
> 
> 1. Open new terminal and use these commands.
>    Here 1234 is the port we choose in HiddenEye.
> 
> `lt -p 1234`

I tried it. But it saying the tunnel server is offline. 
![Uploading Screenshot_2019-12-19-20-16-12.png…]()

**Comment by 0x-MRNOBODY-x0** [comment]
Even Ngrok isn't working.
![Screenshot_2019-12-20-06-38-22](https://user-images.githubusercontent.com/45472892/71221671-7c896d80-22f3-11ea-9791-cd4ca37612f5.png()

**Comment by flashxml** [comment]
ERROR]: LocalTunnel packages haven't been installed correctly

To bad you cant use this nice app

**Comment by An0nUD4Y** [comment]
@flashxml , Try installing again.
And create a new Issue.

**Comment by sukhmeet888** [comment]
![Screenshot_20200510-163003](https://user-images.githubusercontent.com/65114567/81497427-1ae69180-92dc-11ea-8546-438c222ca5db.png)

Not going forward after this,please help
