### ISSUE TITLE
serveo and tunnel problem on iOS

### ISSUE THREAD

**Issue by EzrahFTW** [DarkSecDevelopers/HiddenEye#476]
Hi I have a iPhone on iOS 13 jailbroken and its me or serveo or tunnel not working ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by An0nUD4Y** [comment]
#472

**Comment by EzrahFTW** [comment]
no the server not working I installed properly

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by An0nUD4Y** [comment]
We don't support iOS .
