### ISSUE TITLE
Question: How to run HiddenEye only in local WiFi, not in public internet?

### ISSUE THREAD

**Issue by luger19** [DarkSecDevelopers/HiddenEye#477]
I just want to test HiddenEye in my private WiFi network without letting anyone else visit the created sites. How to do that?

**Comment by gjhami** [comment]
Looks like support was added in the last couple days for a localhost server option. Just select 0 from the server menu.

**Comment by An0nUD4Y** [comment]
@luger19 , Just added Support for Localhost & Pagekite tunnel & Openport Tunnel .

**Comment by polux76** [comment]
Dear ALL
Im having an issue with HiddenEye, it only work with Wifi, when im trying to enter https://8f6005e5.ngrok.io  with my phone and 4G it say "tunnel not found".
Any suggestion ? 
Thanks a lot
