### ISSUE TITLE
No module named requests error (Hidden Eye not opening)

### ISSUE THREAD

**Issue by Kabeer2004** [DarkSecDevelopers/HiddenEye#480]
despite doing all the installation steps and getting success in all of them, I get an import error which says “No module named requests”. Please help.

**Comment by usama7628674** [comment]
@Kabeer2004 `pip3 install requests`.

**Comment by Kabeer2004** [comment]
I have tried this but still not working

**Comment by Mageshwar01** [comment]
@Kabeer2004  use "pip3 install -r requirements.txt"
