### ISSUE TITLE
Link is not generating  stucked at Ngrok

### ISSUE THREAD

**Issue by prashasst** [DarkSecDevelopers/HiddenEye#481]
![Screenshot_20191228-175530_Termux](https://user-images.githubusercontent.com/55028965/71543638-486d1700-299b-11ea-83de-b63fd3b8511a.jpg)

**Comment by prashasst** [comment]
Please help me

**Comment by Mageshwar01** [comment]
I too have the same problem.....not only in ngrock but also in serveo.

**Comment by An0nUD4Y** [comment]
@prashasst @Mageshwar01 , For now try other tunnels , We will fix it soon.

**Comment by prashasst** [comment]
Nothing is working..

I am experiencing this problem every time

**Comment by bapji** [comment]
> Nothing is working..
> 
> I am experiencing this problem every time

It's working bro I can provide you ss

**Comment by Pepijn2004** [comment]
It's because the serveo servers are down, they knew that their servers were abused for phishing ahahah... If you go to their site it says serveo servers currently down cuz of phishing-> serveo.net

**Comment by sTiKyt** [comment]
> It's because the serveo servers are down, they knew that their servers were abused for phishing ahahah... If you go to their site it says serveo servers currently down cuz of phishing-> serveo.net

He used Ngrok... Not Serveo

**Comment by nyawpawgithub** [comment]
what server is working now?

**Comment by nyawpawgithub** [comment]
![Screenshot_20200305_172611_com termux](https://user-images.githubusercontent.com/61817554/75967260-8724cd80-5f06-11ea-865a-47bf4eb5a249.jpg)

**Comment by nyawpawgithub** [comment]
I tried all server nothing works

**Comment by smigol777** [comment]
Estou com o mesmo erro

**Comment by madiechang** [comment]
Same problem... Nggrok stucked and not creating link

**Comment by An0nUD4Y** [comment]
#526
