### ISSUE TITLE
Serveo custom subdomain

### ISSUE THREAD

**Issue by SykeX69** [DarkSecDevelopers/HiddenEye#483]
**Describe the bug**
When i try to write a custom subdomain, even if i type something random it says is not valid. What should i do??

**Comment by williams50th** [comment]
Hello i don't understand you.

**Comment by SykeX69** [comment]
so when i select serveo, then custom subdomain, when i enter a custom one it just says is not valid even if i type something random

**Comment by atroxGhost** [comment]
Same here no said fixes have solved the problem

**Comment by adityaharish2003** [comment]
I've got the same issue too

**Comment by SykeX69** [comment]
> I've got the same issue too
I found out why. The serveo website is down

**Comment by An0nUD4Y** [comment]
@SykeX69 , Serveo is Down [Check Here](https://serveo.net) ,
Use Other Tunnelling Options.

**Comment by An0nUD4Y** [comment]
Closing Here Feel Free To Reopen.

**Comment by sTiKyt** [comment]
@An0nUD4Y i think we should check automatically if Serveo is down (due to it's frequent problems) and if it's down we should disable option to select it in server list, what do u think?
