### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by kouheiAinz** [DarkSecDevelopers/HiddenEye#485]
After i typed "sudo python3 HiddenEye.py"
This showed up
Traceback (most recent call last):
  File "HiddenEye.py", line 9, in <module>
    from Defs.Checks import *
  File "/home/kouhei/HiddenEye/Defs/Checks.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

How can i fix this?
![Screenshot_20200104-002926_UserLAnd](https://user-images.githubusercontent.com/59481976/71735394-4a4a4500-2e89-11ea-9610-d1b8dee9dd62.jpg)

**Comment by Dissension** [comment]
+1, Also got this but with Termux app android.

**Comment by alasdim** [comment]
also same here  termux and userland 
any help !

**Comment by alasdim** [comment]
i fix it now .... but i do not know how to show the cam ??  help

**Comment by An0nUD4Y** [comment]
@kouheiAinz  Install Requests package first..
Use ..
`pip3 install requests`
0R
`pip install requests`
OR try
`pkg install requests`

**Comment by alasdim** [comment]
> @kouheiAinz Install Requests package first..
> Use ..
> `pip3 install requests`
> 0R
> `pip install requests`
> OR try
> `pkg install requests`

i mean  how to see the  pic  that i got  by saycheese  ?

**Comment by An0nUD4Y** [comment]
@kouheiAinz , Also Try To Follow instructions in proper manner.
As Mentions in instructins
`pip3 install -r requirements.txt`
Help to install All required Packages.

Let me know if it Solves Your Issue.

**Comment by An0nUD4Y** [comment]
@alasdim , Ask on Official Repo of SAYCHEESE.
May be i can help you their.

**Comment by alasdim** [comment]
> @alasdim , Ask on Official Repo of SAYCHEESE.
> May be i can help you their.

memory error

**Comment by alasdim** [comment]
> @kouheiAinz , Also Try To Follow instructions in proper manner.
> As Mentions in instructins
> `pip3 install -r requirements.txt`
> Help to install All required Packages.
> 
> Let me know if it Solves Your Issue.

MemoryError
