### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by WickedG0d** [DarkSecDevelopers/HiddenEye#486]
Traceback (most recent call last):
  File "HiddenEye.py", line 50, in <module>
    getCredentials(port)
  File "/root/Tools/HiddenEye/Defs/Actions.py", line 916, in getCredentials
    ip = re.search("Victim Public IP: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[\n,\r]", lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Here's the error i am getting

**Comment by An0nUD4Y** [comment]
@WickedG0d  We are Aware of This Issue..
Will Solve it As Soon As Possible..

**Comment by gjhami** [comment]
I'd like to close this issue as it appears to be a duplicate of #469
