### ISSUE TITLE
Link is not generating please help fast

### ISSUE THREAD

**Issue by prashasst** [DarkSecDevelopers/HiddenEye#491]
Link is not generating....

In Ngrok 
In serveo

In local tunnel

I also uninstall and installed it but nothing is happening

Please help  me fast...

![Screenshot_20200109-165830_Termux](https://user-images.githubusercontent.com/55028965/72064347-aede2780-3301-11ea-98d2-9c93530f01c5.jpg)

**Comment by An0nUD4Y** [comment]
@prashasst , Clone latest repo  for termux v0.5.2
Use this command
`git clone -b  Termux-Support-Branch-v0.5.2 https://github.com/DarkSecDevelopers/HiddenEye`
And then try using other tunnels also.

**Comment by prashasst** [comment]
Others are also not working please tell me everything
