### ISSUE TITLE
Error installing local tunnel

### ISSUE THREAD

**Issue by kouheiAinz** [DarkSecDevelopers/HiddenEye#492]
Yo this showed up how to fix this?

This thing showed up after i pressed Y

![Screenshot_20200110-155739_Termux](https://user-images.githubusercontent.com/59481976/72135716-22e00480-33c2-11ea-984e-e537ef72bd6e.jpg)

**Comment by An0nUD4Y** [comment]
Yupp , its just to make sure , that the localtunnel can be installed correctly.
