### ISSUE TITLE
Termux and PC Error message

### ISSUE THREAD

**Issue by CornerstoneII** [DarkSecDevelopers/HiddenEye#493]
Termux:
ModuleNotFoundError: No module named 'requests'

PC:
Traceback (most recent call last):
  File "HiddenEye.py", line 9, in <module>
    from Defs.Checks import *
  File "C:\Users\oluwa\Documents\HiddenEye\Defs\Checks.py", line 3, in <module>
    from os import system, getuid, path
ImportError: cannot import name 'getuid' from 'os' (C:\Python38-32\lib\os.py)

**Comment by An0nUD4Y** [comment]
@CornerstoneII , in case of termux 
Use this command to install requests package
`pip3 install requests`
Or
`pip install requests`
Or 
`pkg install requests`

And please Provide more details about PC error and Device type and other details.

**Comment by An0nUD4Y** [comment]
@CornerstoneII , You are probabily using windows PC.
But we currently don't support that.


Closing here , Feel free to reopen.
