### ISSUE TITLE
Serveo loading takes forever

### ISSUE THREAD

**Issue by kouheiAinz** [DarkSecDevelopers/HiddenEye#494]
It's stuck to this page for like 20 minutes now 
![Screenshot_20200113-105947_Termux](https://user-images.githubusercontent.com/59481976/72231039-062b1300-35f4-11ea-92e4-2b620407a934.jpg)

**Comment by An0nUD4Y** [comment]
@kouheiAinz , its because serveo is down ..
Also mentioned inside the script.
Check serveo.net
