### ISSUE TITLE
Traceback (most recent call last):   File "./HiddenEye.py", line 52, in <module>     getCredentials(port)

### ISSUE THREAD

**Issue by prashasst** [DarkSecDevelopers/HiddenEye#495]
I got this error

_________________________________

Traceback (most recent call last):
  File "./HiddenEye.py", line 52, in <module>
    getCredentials(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Actions.py", line 1101, in getCredentials
    ip = re.search("Victim Public IP: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[\n,\r]", lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
$

![Screenshot_20200113-174220_Termux](https://user-images.githubusercontent.com/55028965/72255357-88372e00-362c-11ea-93c7-7254b32dee1c.jpg)

**Comment by An0nUD4Y** [comment]
#486 
Closing Here for more details catch the already available issue #486
