### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by prashasst** [DarkSecDevelopers/HiddenEye#499]
...............................
 [ GETTING PRESSED KEYS ]:
 UnidentifiedUnidentifiedUnidentifiedUnidentified
...............................
Traceback (most recent call last):
  File "./HiddenEye.py", line 52, in <module>
    getCredentials(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Actions.py", line 1101, in getCredentials
    ip = re.search("Victim Public IP: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[\n,\r]", lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
$
$
![Screenshot_20200119-121203_Termux](https://user-images.githubusercontent.com/55028965/72676248-1724ca00-3ab5-11ea-91a8-9965072fdb13.jpg)

**Comment by An0nUD4Y** [comment]
#486
