### ISSUE TITLE
Openport no supported for arm64 device

### ISSUE THREAD

**Issue by deoscarity** [DarkSecDevelopers/HiddenEye#501]
Hello sir, i'm unable to install openport, there is no arm64 support. I'm using userland on android. Please help.

**Comment by deoscarity** [comment]
checking for openport wether installed or not temporary disable by commenting 
"checkOpenport()" in HiddenEye.py

**Comment by An0nUD4Y** [comment]
@deoscarity ,
Check https://www.wa4e.com/downloads/
For binary files of localtunnel 
OR 
Compile from source codes available here https://localtunnel.me
OR 
Try installating Package Version manually.
For installation help of localtunnel
Check this https://github.com/localtunnel/localtunnel/blob/master/README.md

**Comment by icon504** [comment]
You Have Reached Maximum Free Tunnels or (Server Down)
