### ISSUE TITLE
Ngrok down? 

### ISSUE THREAD

**Issue by Pelota19** [DarkSecDevelopers/HiddenEye#502]
Hi, Until 2 days ago it worked and now it doesn't work. I don't know if it's me or it's Ngrok's problem. Only I open the link in local red to outside the network tunnel not found

**Comment by andi671** [comment]
I have the same Problem

**Comment by 0x-MRNOBODY-x0** [comment]
I can't use any package. Doesn't work.

**Comment by An0nUD4Y** [comment]
#526 , Try if it works.

**Comment by An0nUD4Y** [comment]
Closing Here , There is not enough info Available about issue.
