### ISSUE TITLE
No Custom link with localxpose

### ISSUE THREAD

**Issue by tony3ds** [DarkSecDevelopers/HiddenEye#504]
(Sorry For my bad English, I'm Italian)

When I try to create a custom subdomain in localxpose HiddenEye print an error screen 
and it reload the previous page

**Comment by andi671** [comment]
Same here, i dont get IP Adresse 
![Unbenannt](https://user-images.githubusercontent.com/35406183/73307751-20353a00-421f-11ea-846d-fdfc00f2ee57.PNG)

**Comment by An0nUD4Y** [comment]
Keep Eyes on #517
