### ISSUE TITLE
The Ngrok Server is Not Working

### ISSUE THREAD

**Issue by andi671** [DarkSecDevelopers/HiddenEye#505]
The Ngrok Server is not working, if i geh on the Link i always get the 404 Error, if i try it with the Local IP i can connect the Website.

**Comment by andi671** [comment]
![Unbenannt](https://user-images.githubusercontent.com/35406183/73308104-d731b580-421f-11ea-9128-2138bc7d335d.PNG)

![Unbenannt1](https://user-images.githubusercontent.com/35406183/73308100-d567f200-421f-11ea-8aaf-215945d345e7.PNG)

**Comment by templergreek** [comment]
1. use su

**Comment by templergreek** [comment]
tho same issue with me lol

**Comment by An0nUD4Y** [comment]
Check #526
