### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by swordfishvirus** [DarkSecDevelopers/HiddenEye#506]
after cd HiddenEye and try 
pip3 install -r requirements.txt && pip3 install requests 
the following come up
File "hiddenEye.py", line 7, in <module>
from Defs.actions import *
File "home/hck/HiddenEye/Defs/Actions.py"
, line 6, in <module>
from distutils.dir_utils import  copy_tree
moduleNotFoundError: no module named 'distutils.dir_utils'

this error came up during installation on android device

**Comment by sTiKyt** [comment]
For android please use Termux branch

**Comment by anormus** [comment]
When i need to open the HiddenEye this error came !!! How to solve it !!!    
Traceback (most recent call last):
  File "./HiddenEye.py", line 9, in <module>
    from Defs.Checks import *
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by An0nUD4Y** [comment]
@anormus , Please Always Check Already Solved Issues First before creating new one.

Try `pip3 install requests`

**Comment by An0nUD4Y** [comment]
@swordfishvirus , Please provide Screenshots & remain active on the issue.

Closing Here , New Users can open this issue if found same errors.
