### ISSUE TITLE
Localxpose Custome URL don't work 

### ISSUE THREAD

**Issue by liuko** [DarkSecDevelopers/HiddenEye#508]
Hi,

I have an issue with the localxpose feature, after select custom url and choose url that I want, HE say again and again this error (I try a lot of differents url). Can you help me ? 
TY

![image](https://user-images.githubusercontent.com/52002447/73488699-b1381c80-43a9-11ea-881e-93f9b55e8c8e.png)

**Comment by sTiKyt** [comment]
I don't think you can use dot for it

**Comment by An0nUD4Y** [comment]
#504
