### ISSUE TITLE
 ^Network error^. Verify your Internet connection.

### ISSUE THREAD

**Issue by lordcharlx** [DarkSecDevelopers/HiddenEye#510]
![Screenshot at 2020-02-06 21-36-15](https://user-images.githubusercontent.com/5570136/73977940-8c085880-492b-11ea-82ff-8742a7f2cc51.png)

i have seen this in the previous issue but none of the fixes works for me

**Comment by An0nUD4Y** [comment]
@lordcharlx , Share more details ..
Try to `ping google.com`

**Comment by lordcharlx** [comment]
Positive.....i mean 100% success rate 
--
c4 Tuesday, 11 February 2020, 03:19PM +01:00 from AnonUD4Y  notifications@github.com :

**Comment by lordcharlx** [comment]
@An0nUD4Y 
![Screenshot at 2020-02-12 10-52-16](https://user-images.githubusercontent.com/5570136/74323423-c9cf0c00-4d85-11ea-96eb-c34618ee2773.png)
see ping result

**Comment by An0nUD4Y** [comment]
@lordcharlx , Are you still facing the error.

I am Closing Here , Feel Free to Reopen.
