### ISSUE TITLE
Module Error on Load

### ISSUE THREAD

**Issue by 10splaya** [DarkSecDevelopers/HiddenEye#511]
I have tried to use HiddenEye, but stumbled an issue. This error, [](https://imgur.com/8jLjVcN.png), continously pops up while trying to load the HiddenEye.py. I'm not sure if this is a problem on my side or if something is wrong with the code. Any advice? https://imgur.com/nxUfJfg.png

**Comment by solomon-ey** [comment]
inbox me for solution chieflyx@gmail.com

**Comment by 10splaya** [comment]
Can you tell me how to fix it here? I’m not going to be emailing. Sorry!!

**Comment by An0nUD4Y** [comment]
@10splaya , Try `pip3 install urllib3`

**Comment by 10splaya** [comment]
> @10splaya , Try `pip3 install urllib3`

I’ve tried this and it comes with the same error. (It is already installed, so I uninstalled it and reinstalled it but nothing worked) any other suggestions?

**Comment by sTiKyt** [comment]
try to run app with "sudo python3 ./HiddenEye.py"

**Comment by 10splaya** [comment]
> try to run app with "sudo python3 ./HiddenEye.py"

No Luck :/

**Comment by 10splaya** [comment]
IM not getting ModuleNotFoundError: No module named 'requests'
I have requests though on Kali

**Comment by sTiKyt** [comment]
@10splaya something wrong with your setup, i don't think something wrong with our app.

I'd suggest changing to Arch or Black Arch cause it's easier to use but that's your choice to make...

**Comment by An0nUD4Y** [comment]
@10splaya , Use `pip3 install requests`

Closing Here , Feel Free To Open.
