### ISSUE TITLE
HiddenEye.py is stuck on Installing OpenPort

### ISSUE THREAD

**Issue by hackers-brain** [DarkSecDevelopers/HiddenEye#513]

**Comment by An0nUD4Y** [comment]
@gauravraj0408 , We will create a separate installer for all the tunnel set up processes.
For Now you can simply skip the openport installation or try installing it manually.

**Comment by tboss12310** [comment]
how do I skip the open port install? / install it myself?

**Comment by Caleb2330** [comment]
I've search for the zip file for open port but all of my efforts are futility

**Comment by Caleb2330** [comment]
How can we install open port manually

**Comment by williams50th** [comment]
Hello pls anyone with office 365 Zipfile or one Drive Zipfile.

**Comment by epzylo0n** [comment]
download openport from the web, then open the terminal and position yourself in the folder where you downloaded it, usually cd Downloads and then install it with dpkg - i xxx.deb

**Comment by Caleb2330** [comment]
Did not work

**Comment by pretech86** [comment]
put # in the code infront of it

**Comment by mr-dark-angel** [comment]
Can we download openport separate, if yes pls cmt hw it is

**Comment by koleeed** [comment]
@mr-dark-angel 
Please tell me if you get the way to download openport

**Comment by sTiKyt** [comment]
For now we disabled those new tunelling options, we have very big update and will fix and enable them soon.
