### ISSUE TITLE
Script hangs on Ngrok

### ISSUE THREAD

**Issue by ApatheticEuphoria** [DarkSecDevelopers/HiddenEye#514]
Followed all included instructions, openport and local tunnel don't install properly but I see that's already an issue you're going to address soon. 

Upon usage of Ngrok the script will freeze or hang and becomes unresponsive.
Screenshot: https://imgur.com/a/ys99REp
ISP: Xfinity
Environment: Android/Termux
Device: Motorola Moto E5
Model: moto e5 (XT1920DL)
Android version: 8.1.0
Software Variant: TracFone

For more phone info see images here:
https://imgur.com/a/PWQVNhT

Here is a one line command I can use to install and run the script and reproduce the error consistently:

`apt update -y && apt upgrade -y && pkg install git python php curl python2 openssh grep -y && pip3 install wget && git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git && cd HiddenEye && chmod 777 HiddenEye.py && pip install -r requirements.txt && python HiddenEye.py`

**Comment by blackgeneration** [comment]
@ApatheticEuphoria I think **the problem** is with the ngrok binary itself. I downloaded a separate binary, added my authtoken then I tried to open a tunnel to my local php server but its not working. Also its not just on HiddenEye but on ShellPhish as well(since it also makes use of ngrok).

**Comment by juanjavito** [comment]
@ApatheticEuphoria 
do this :

-Select ngrok
-turn on the hostpot
-wait

if doesnt work try with 3g 

work for me

**Comment by An0nUD4Y** [comment]
Check #526 for Solution.
