### ISSUE TITLE
Instagram Design Outdated!

### ISSUE THREAD

**Issue by niemant** [DarkSecDevelopers/HiddenEye#516]
Steps to reproduce:
Select Phishing Module (Instagram)
Select Operation Mode: [5] Instafollower (Lure To Get More Followers) *[NEW]*
Select Ngrok as Server.
The website it loads with the given URL is outdated and also at the bottom stats year 2018.

By the way when i was reproducing this I got this error in Ngrok generated web:

**Too Many Connections

Too many connections! The tunnel session '1YOR1wnsAwiWqbzc8ka4Z2tH78k' has violated the rate-limit policy of 20 connections per minute by initiating 36 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702**

**Comment by usama7628674** [comment]
This will be fixed in next version
