### ISSUE TITLE
Localxpose and Localtunnel server not working

### ISSUE THREAD

**Issue by EMLiamXx32** [DarkSecDevelopers/HiddenEye#517]
**Describe the bug**
When I pick the Localxposed server (Number 3) and then pick the "random url" (Number 2)  it won't give me a url it just stays blank. The exact same thing happens with both of the Localtunnel servers

**Expected behavior**
Im guessing it should give me a url

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser: Firefox

**Additional context**
This is my first post on GitHub and im new to Linux so im not sure if im supposed to download something or something but it would be highly appreciated if someone could help, thanks.
![Screenshot 2020-02-29 03:25:09](https://user-images.githubusercontent.com/61616038/75604349-870b7480-5aa5-11ea-9eb8-3602f8f4aea9.png)

**Comment by An0nUD4Y** [comment]
@EMLiamXx32 , Have you tried with other tunnel options like NGROK..
OR 
Try launching them separately..

**Comment by EMLiamXx32** [comment]
Yes, and it is working just fine. But those 2 arent

**Comment by ioi2908** [comment]
@An0nUD4Y quite a poor script...lot of bugs

**Comment by Ma5t3r30d3** [comment]
Same issue over here. Think the issues might be in Actions.py, but I'll dive in more tonight.

 @ioi2908 Do you have any other fun scripts you'd suggest? Curious on your thoughts

**Comment by An0nUD4Y** [comment]
@ioi2908 , Thanks man , We are Doing best to solve issues, But you know nothing is static neither phishing pages nor the tunnelling services. But the original scripts is still in initial phase.
We will soon release a stable version.

**Comment by XLR-X** [comment]
well i have a question how come localxpose gives premium features for free in HiddenEye?

**Comment by sTiKyt** [comment]
After big update we had to disable those new tunnels, will enable them again little bit later.

**Comment by Hiperixx** [comment]
how can use custom domain ı bought  pro ):
