### ISSUE TITLE
Ngrok uses the same link every time (even after it has expired) and does not accept auth token

### ISSUE THREAD

**Issue by EragonShade98** [DarkSecDevelopers/HiddenEye#519]
**Describe the bug**
This is an interesting one that I can't seem to figure out. Sometimes, after I reboot the Hidden Eye server, it produces the same Ngrok link again. This becomes problematic since the links end up getting taken down by Ngrok after a certain amount of time. On top of that, I can't see if the link has expired or not on the ngrok website because the Hidden Eye server won't acknowledge that I've entered in an auth token for Ngrok into the .yml.

**To Reproduce**
Add auth token to ngrok by doing ./ngrok authtoken [auth code]. Check Ngrok website after starting Hidden Eye server. Hidden Eye link isn't there.

**Expected behavior**
I expected to see the server link on the Ngrok website since I linked the server to my account. I also expected to get a different Ngrok link every time, but I don't.

Running on AWS ubuntu EC2 instance, for reference.

**Comment by An0nUD4Y** [comment]
@EragonShade98 , We will soon add a option to use auth Token and a paid account in ngrok Tunnel Option.
For now you can try to delete the link.url file from HiddenEye Directory.
OR 
Try adding a authtoken separately and create a tunnel from separate terminal from NGROK (For Same Port you chosed).

**Comment by An0nUD4Y** [comment]
Check #526 , to solve this issue.

**Comment by An0nUD4Y** [comment]
@EragonShade98 , We will add an option to use Paid versions of ngrok also.
