### ISSUE TITLE
Localxpose taking forever to download

### ISSUE THREAD

**Issue by ahmadbenos** [DarkSecDevelopers/HiddenEye#522]
i'm setting up HiddenEye on Termux. I'm using bluestacks as an android emulator on PC windows 10.
Anyways, i type in "python HiddenEye.py"
-checking for updates...
-php installation found
-localxpose not found !!
-Downloading Localxpose
and it stays like that for almost 40 minutes!! my internet connection downloads 0.3 MB/s which is a fair enough speed for such thing(0.3 MB/s = 18 megabytes every minute lol)

**Comment by An0nUD4Y** [comment]
@ahmadbenos , We will fix it soon.

**Comment by sTiKyt** [comment]
For now Localxpose is disabled, will be enabled and fixed soon. You are free to re-open then.
