### ISSUE TITLE
ADD A New PORT Forwarding Option

### ISSUE THREAD

**Issue by htr-tech** [DarkSecDevelopers/HiddenEye#524]
## Dear HiddenEye Dev ,

Add A New Tunnelling Option ! I suggest you to add 

[LocalHostRun](http://localhost.run)

to Hiddeneye Tool !

**Comment by An0nUD4Y** [comment]
@hrt-tech , Thanks for suggestion..
We will add it to our next releases.

**Comment by An0nUD4Y** [comment]
#509
