### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionsPool. Certificate verify failed

### ISSUE THREAD

**Issue by ScryE778** [DarkSecDevelopers/HiddenEye#525]
After i write "sudo ./HiddenEye", i got this problem (sorry for the photo with smartphone, but it's my second notebook, and he's too weak for sending screenshots and run others programs).
![0-02-0a-8a6eaaf58c279d4ce43c32cc6579305da00eb694bb17bda332ed58667f895406_66f0d76f](https://user-images.githubusercontent.com/55192460/77127198-ee389b00-6a4b-11ea-9f37-eee234fed3fa.jpg)
![0-02-0a-b335d19cb505e08ef0f8f65c4bb7df7889ce3f076fcf8fb42b34f9ee074c01a1_15649377](https://user-images.githubusercontent.com/55192460/77127209-f7c20300-6a4b-11ea-960d-e3306f7638f5.jpg)

**Comment by sTiKyt** [comment]
Which version of python are you trying to use?

**Comment by sTiKyt** [comment]
Did you install prerequisites?

**Comment by ScryE778** [comment]
I try commands like
sudo python3 HiddenEye.py (Cheking For Updates... Then the problem on the screenshot)
sudo python HiddenEye.py (ImportError: cannot import name ConverterMapping)
sudo ./HiddenEye.py (Cheking For Updates... Then the problem on the screenshot)
But i install prerequisites with pip and pip3. (Requirements already satisfied)

**Comment by An0nUD4Y** [comment]
@ScryE778 , This error is in requests module in python.
Its happening because the the requests module is sending a GET request to the Server to Verify Updated Versions. Which requires a SSL cerfificate.

Try setting this process False..
Change Line 45 in Defs/Checks.py
From this `ver_rqst = requests.get(ver_url)` to this `ver_rqst = requests.get(ver_url , verify= False)`

Let me know if it works or Not.

**Comment by An0nUD4Y** [comment]
@ScryE778 , In case it did not worked then you can refer [here ](https://stackoverflow.com/questions/39737820/requests-exceptions-sslerror-ssl-certificate-verify-failed-certificate-verif), or [here](https://github.com/psf/requests/issues/4381)  
These are some thing you can try.
Let us know if Any of above solves Your Issue.

**Comment by ScryE778** [comment]
The same error but with "Openport not Installed !! Installing Openport ..."
![photo_2020-03-24_16-04-59](https://user-images.githubusercontent.com/55192460/77441345-a027ec80-6de9-11ea-898a-8ed2a721c249.jpg)
![photo_2020-03-24_16-05-02](https://user-images.githubusercontent.com/55192460/77441357-a4eca080-6de9-11ea-87a3-51ce9ec6f44e.jpg)

**Comment by An0nUD4Y** [comment]
@ScryE778 , 
Best ways to solve this issue is this that,
1) Replace all The `requests.get(url)` with `req = requests.get(url , verify= False)` in Defs/checks.py & in Defs/Actions.py

ITS A BUG WE WILL FIX IT SOON.

**Comment by ScryE778** [comment]
All work, but "LocalTunnel packages haven't been installed correctly". I tried on my smartphone (kali net hunter) and on notebook, one both that won't install

**Comment by An0nUD4Y** [comment]
@ScryE778 , Please Open new issue, That is another issue with different topic so better to open a new issue.

**Comment by dedshit** [comment]
haha  i removed damn root permission from that shit

**Comment by dedshit** [comment]
ù

> @ScryE778 ,
> Best ways to solve this issue is this that,
> 
> 1. Replace all The `requests.get(url)` with `requests.get(url , verify= False)` in Defs/checks.py & in Defs/Actions.py
> 
> ITS A BUG WE WILL FIX IT SOON.

yep i already done and i fixed that too
