### ISSUE TITLE
Found Some Bugs & Suggestion to Solve It !

### ISSUE THREAD

**Issue by htr-tech** [DarkSecDevelopers/HiddenEye#526]
### The Ngrok Server is working at the first time but after new port forwarding it displays
![image](https://user-images.githubusercontent.com/56682134/77220331-2d104300-6b69-11ea-8449-c2fe586482a7.png)

###  it happens because the previous port is not closed properly !
![2](https://user-images.githubusercontent.com/56682134/77220350-68ab0d00-6b69-11ea-8f42-4d0ef0daaaac.PNG)

### You can find the Previous connection by Executing the following Command

`ps aux | grep -o "ngrok" | head -n1`

### and you can kill the Tunnel by Executing the following Commands

`pkill -f -2 ngrok > /dev/null 2>&1`  <-- Close Ngrok Tunnel
`killall -2 ngrok > /dev/null 2>&1`  <-- Kill Ngrok Tunnel
`pkill -f -2 php > /dev/null 2>&1`  <-- Close PHP Tunnel
`killall -2 php > /dev/null 2>&1`  <-- Kill PHP Tunnel

### All the best 👍

**Comment by An0nUD4Y** [comment]
@htr-tech , Thank you,  For digging in for bug.  We will surely fix it in next release.
Or 
Will be more helpful if you can make a PR for this fix. So that others don't  have to wait till next releases.

**Comment by htr-tech** [comment]
## @An0nUD4Y  Check Termux Branch PR

**Comment by An0nUD4Y** [comment]
@htr-tech , Thanks For This fix. I have added a command to kill previously opened ngrok tunnel,

**Comment by An0nUD4Y** [comment]
Let me know if anyone still facing issues

**Comment by 10ke5h** [comment]
I'm stuck on Ngrok.
Please help

**Comment by htr-tech** [comment]
> @htr-tech , Thanks For This fix. I have added a command to kill previously opened ngrok tunnel,

My Pleasure

**Comment by pillowz6666** [comment]
> Let me know if anyone still facing issues

Well, whenever I put in the generated link in either Firefox or Google it responds with a ngrok settings panel! It says that everything is "ok" and nothing responds with something like 402 etc. but I can't attach the attack vector website.
