### ISSUE TITLE
Servers not working

### ISSUE THREAD

**Issue by jasonsalem2002** [DarkSecDevelopers/HiddenEye#531]
Only ngrok is working.
Pagekit was working now it is not.
Can you please reply and tell us what shall we do or if it is an error in your script.
Serveo official site is down because of the phishing but the others are not.

**Comment by An0nUD4Y** [comment]
@jasonsalem2002 , These are all Free services. And its always difficult to keep them up to date.
You can wait till the next Updates or New Releases.

**Comment by An0nUD4Y** [comment]
Similar Issue As #519 #517 #522 
Closing This issue to reduce multiple issues about on issue.
