### ISSUE TITLE
Ngrok Stuck Too Long

### ISSUE THREAD

**Issue by Phantom0406** [DarkSecDevelopers/HiddenEye#534]
i has follow instruction but in the last select server i choose ngrok and then just stuck after that. i have try another trik to find problem but i did'nt  got it. maybe you can help me.
![Linux](https://user-images.githubusercontent.com/52474658/77593601-6e20a280-6f2f-11ea-92c6-31c9593045df.PNG)

**Comment by An0nUD4Y** [comment]
#526

**Comment by An0nUD4Y** [comment]
Check #526
