### ISSUE TITLE
keylogger

### ISSUE THREAD

**Issue by nogallaat** [DarkSecDevelopers/HiddenEye#538]
I have a own site that i want to use as phishing page, everything works fine but the keylogger only works on the first page. the page i use will redirect you to another page but on the redirected page the keylogger dont work. is there a way to fix this?

**Comment by An0nUD4Y** [comment]
@nogallaat , Add the keylogger script to all the pages.  You can do it manually or can modify the Defs/actions.py file at function named keylogger or something like that.

**Comment by nogallaat** [comment]
Hi bro i dont get it.. is it possible to go on my pc on like Anydesk or
something so you can fix it i dont get it.
