### ISSUE TITLE
Suggestion and improvement

### ISSUE THREAD

**Issue by usama7628674** [DarkSecDevelopers/HiddenEye#54]
@alexmozzhakov @An0nUD4Y We should use apache2 as php server is really slow as I was testing Snapchat and the file main.js took a long time to load.Similarly with other pages taking long to load completely.I then tested with apache2 and it was much faster and pages took less then half time to load completely.What do you guys suggest?

**Comment by An0nUD4Y** [comment]
Simply Update it bro... NO need for suggestions...? If You Wants to make it more Useful & Fast Then just Do it..

**Comment by alexmozzhakov** [comment]
@usama7628674 do a good testing though. I've compared to nginx and I'm not getting much difference (~40 ms)

**Comment by usama7628674** [comment]
@alexmozzhakov I tested snapchat both on php and nginx server and I can confirm both are dead slow but on apache2 it was much fast.I'll push a PR soon to use apache2 as a server .

**Comment by sTiKyt** [comment]
@usama7628674 solved?

**Comment by usama7628674** [comment]
@sTiKyt Well the only solution is to host files on hosting site or use paid CDN.

**Comment by sTiKyt** [comment]
Understood
