### ISSUE TITLE
sh: 1: lt: not found

### ISSUE THREAD

**Issue by ViperZCrew** [DarkSecDevelopers/HiddenEye#543]
_  _ . ___  ___  ___ _  _  ___ _  _ ___
        |__| | ]  | ]  | |__ |\ |  |__ \__/ |__
        |  | | ]__| ]__| |__ | \|  |__  ||  |__
        http://github.com/darksecdevelopers
        ** BY:DARKSEC ** 

-------------------------------
[ LOCALTUNNEL URL  ]!! 
-------------------------------

[*]SELECT ANY URL TYPE TO GENERATE PHISHING LINK:

[+]Type Subdomain for Custom URL. 
[+]Leave Empty For Random URL

(Localtunnel/Subdomain)> 
sh: 1: lt: not found

Also if i typed any url it will not work

**Comment by An0nUD4Y** [comment]
@ViperZCrew , Its Because Localtunel Package Version doesn't installed correctly.
