### ISSUE TITLE
Localxpose pro

### ISSUE THREAD

**Issue by nogallaat** [DarkSecDevelopers/HiddenEye#544]
Is there a way to add localxpose pro to ur hiddeneye so there isnt a time-out? and if it is possible how to install that

**Comment by An0nUD4Y** [comment]
@nogallaat , Loacalxpose File Can be Found At Server/loclx location in HiddenEye Directory After Successfull Installation.
You Can simply Replace That file with the same name. Make Sure If Localxpose Pro uses the same commands As Localxpose.
If Both have Different Command lines Then You can simply Edit The Defs/Actions.py File At the Fuctions on Line 419 , 440 & 474

**Comment by Jejepixel** [comment]
> @nogallaat , Loacalxpose File Can be Found At Server/loclx location in HiddenEye Directory After Successfull Installation.
> You Can simply Replace That file with the same name. Make Sure If Localxpose Pro uses the same commands As Localxpose.
> If Both have Different Command lines Then You can simply Edit The Defs/Actions.py File At the Fuctions on Line 419 , 440 & 474

Hey, thank you, I was just searching how to do it.

but on https://docs.localxpose.io/cli there is 0 explanation on how to install it on your computer.
Im not a big dev as you guys, but i'm in learning, and I noticed that when we download from the website the free version we have the same code as it is by default in hiddeneye (server/loclx).
I bought the pro version but there is 0 explanations so can you help please?
They give me a token only in the website, worked for GUI version but CLI I have 0 ideas how to connect it .

thank you in advance

**Comment by An0nUD4Y** [comment]
@Jejepixel , Wait till we add an option to use paid versions of tunnels also..
For now try launching tunnel manually with same port as chosen in Hiddeneye to get your link.

**Comment by sTiKyt** [comment]
It's disabled for now, will be back later.
