### ISSUE TITLE
Ngrok defaults to 8080 with advanced instagram scenario

### ISSUE THREAD

**Issue by eren123danyel** [DarkSecDevelopers/HiddenEye#545]
**Describe the bug**
if you choose instagram, and then advanced scenario, if you use a port that is different from 8080 ngrok will create a website, but the website will display an error that says "failed to bind to localhost:8080".

**To Reproduce**
1. Go to 'Instagram Module' 
2. Choose 'Advanced Scenario'
3. Choose 'Ngrok'
4. Click on the Ngrok link

**Desktop (please complete the following information):**
 - OS:Kali Linux

**Comment by An0nUD4Y** [comment]
@eren123danyel , Please Provide more information.

Reopen Issue when submitting more information regarding issue.
