### ISSUE TITLE
(Android device) error 'downloading Ngrok'

### ISSUE THREAD

**Issue by Midnight1938** [DarkSecDevelopers/HiddenEye#546]

**Comment by juanjavito** [comment]
install Ngrok by yourself 

work for me 

apt update && apt upgrade
apt install git
git clone https://github.com/tchelospy/termux-ngrok.git
cd termux-ngrok
chmod +x termux-ngrok.sh
./termux-ngrok.sh

**Comment by An0nUD4Y** [comment]
@Midnight1938 , No valid information provided.
