### ISSUE TITLE
HiddenEye 

### ISSUE THREAD

**Issue by Caleb2330** [DarkSecDevelopers/HiddenEye#547]
HiddenEye stuck at installing openport 
![Screenshot_20200401-042349](https://user-images.githubusercontent.com/52715649/78096198-ee805100-73d0-11ea-9c77-1b2562eedb60.png)

**Comment by shreyakumari10** [comment]
When I was using HiddenEye for the first time... Installing Openport took a lot of time, so try being patient and wait for some time.

**Comment by An0nUD4Y** [comment]
@Caleb2330 , Give it some time, Either it will install or throw error.
Just Wait.. 

@shreyakumari10 , Thanks For the comment.

Closing Here Feel Free To reopen.
