### ISSUE TITLE
Ngrok server isn't responding

### ISSUE THREAD

**Issue by pillowz6666** [DarkSecDevelopers/HiddenEye#548]
**Describe the bug**
When I choose my phishing page and afterward Ngrok server I get an attack link. When I send the link to the target it responds with "**This site does not work (7f5748d2.ngrok.io) is not sending any data ERR_EMPTY_RESPONSE**"

**Expected behavior**
The attack link connects and works properly on the targeted PC. 

**Desktop (please complete the following information):**
 - OS: [MacOSX]
 - Browser [Google Chrome]
 - Version [10.15 Beta]

**Comment by pillowz6666** [comment]
Oh, and it won't generate a new attack link!

**Comment by Mxtheus77** [comment]
Bro, I'm not able to access the link generated on another device. Only on the machine I generated the link, I can access. What can it be?

**Comment by pillowz6666** [comment]
I just attached the link jic.

**Comment by max-1020** [comment]
> Bro, I'm not able to access the link generated on another device. Only on the machine I generated the link, I can access. What can it be?

I experience the same problem too. how is it now?

**Comment by max-1020** [comment]
the link only works on the machine where it was generated. has it something to do with the router setting?

**Comment by An0nUD4Y** [comment]
check #526
