### ISSUE TITLE
[ NGROK SERVER ]!!     on windows

### ISSUE THREAD

**Issue by ykkjobner** [DarkSecDevelopers/HiddenEye#551]
sh: 1: ./Server/ngrok: not found
![Capture](https://user-images.githubusercontent.com/54281406/78254651-dd8c2880-7513-11ea-9fd0-e3e84ec5905e.PNG)
Desktop (please complete the following information):

OS: windows
Browser: Google Chrome
Additional context
This is my first post on GitHub and i am new to Linux so i am not sure if i am supposed to download something or something but it would be highly appreciated if someone could help, thanks.

**Comment by An0nUD4Y** [comment]
@ykkjobner , We don't support windows currently.
