### ISSUE TITLE
Localxpose server not working

### ISSUE THREAD

**Issue by jotomasoperi** [DarkSecDevelopers/HiddenEye#553]
**Describe the bug**
I was choosing a server to host a site, I choose LocalXpose and then choose the custom url option. After writing the domain I had in mind, I waited and then it said "Failed to get this domain! Looks like custom url is not valid or already occupied by someone else !!! ", so I tried switching a little my custom domain and I got the same error, so I started doing some crazy and random domains and all of them got the same error I got on my first try.

**To Reproduce**
When you are creating a website and you are on the servers menu:

-Select LocalXpose;
-Type "1" to get a custom domain;
-Write any domain name you want;

**Screenshots**
![localxpose error](https://user-images.githubusercontent.com/63129461/78424028-9eb8b880-7662-11ea-840c-be32678dc9a5.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux 32-bit 
 - Browser: Firefox
 - Version: 2020.1b
 

**Additional context**
I'm new to this stuff I don't know if the problem is actually mine.

**Comment by An0nUD4Y** [comment]
Keep An eye on #517
