### ISSUE TITLE
Gmail layout

### ISSUE THREAD

**Issue by flashgordon1234** [DarkSecDevelopers/HiddenEye#554]
There are some significant differences in the layout and design of the official gmail login page and the hiddeneye gmail login page, I'd fix myself but I'm not very familiar with html so I'm not sure what lines of code to change to fix them. 
<img width="473" alt="Screenshot_2" src="https://user-images.githubusercontent.com/63272579/78639838-a5227c80-787c-11ea-96d1-82d1ab7cc819.png">
<img width="411" alt="Screenshot_3" src="https://user-images.githubusercontent.com/63272579/78639844-a653a980-787c-11ea-9b01-6b6fef9e1711.png">

**Comment by darkmidus** [comment]
Thank you, I will get to fixing this.

**Comment by usama7628674** [comment]
@darkmidus The last time i updated gmail template was very much same to original gmail page but now i dont have time to update it.Submit a PR if you know you can fix it.

**Comment by darkmidus** [comment]
@usama7628674 I'll take a look at it

**Comment by An0nUD4Y** [comment]
I already mentioned it on #569 , Stay tuned there.
