### ISSUE TITLE
Ngrok is not generating a new link

### ISSUE THREAD

**Issue by pillowz6666** [DarkSecDevelopers/HiddenEye#557]
Well the title says everything
Ngrok is not generating a new link I tried to close all ngrok connections but that didn't work out.
Please tell me where I can fix this in the files and what it should be changed too.

**Comment by skull7778** [comment]
Keep on your hotspot

**Comment by An0nUD4Y** [comment]
check #526 
Please stop opening multiple issues if same is already closed or opened.
