### ISSUE TITLE
Cant RUN HiddenEye.py

### ISSUE THREAD

**Issue by gray66tim** [DarkSecDevelopers/HiddenEye#559]
File "HiddenEye.py", line 39, in <module>
    mainMenu()
  File "/root/HiddenEye/Defs/Actions.py", line 642, in mainMen

___'''.format(MAIN3, MAIN4, MAIN2, MAIN0, version))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)

**Comment by An0nUD4Y** [comment]
Try This. https://github.com/DarkSecDevelopers/HiddenEye/blob/master/README.md#ascii-error-fix

**Comment by An0nUD4Y** [comment]
Reopen issues,  if not fixed.
