### ISSUE TITLE
ayuda 

### ISSUE THREAD

**Issue by sepelin** [DarkSecDevelopers/HiddenEye#560]
ME SALE ESTE ERROR CUANDO VOY A EJECUTAR HIDDENEYES Y NO SE COMO SOLUCIONARLO, YA ORGANICE LA RUTA Y ME SIGUE SALIENDO ESO, ESPERO SABER PRONTO Y TENER ALGUNA RESPUESTA.  MUCHAS GRACIAS 
λ python3 HiddenEye.py

Traceback (most recent call last):
  File "HiddenEye.py", line 9, in <module>
    from Defs.Checks import *
  File "C:\Users\sebastian\Desktop\cmder\HiddenEye\Defs\Checks.py", line 3, in <module>
    from os import system, getuid, path
ImportError: cannot import name 'getuid' from 'os' (C:\Python\lib\os.py)

**Comment by An0nUD4Y** [comment]
Use Linux..,  We do not support Windows.
