### ISSUE TITLE
Permissions denied! Please run as 'sudo

### ISSUE THREAD

**Issue by Imran919** [DarkSecDevelopers/HiddenEye#566]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Imran919** [comment]
in useralnd i have entered hiddeneye command but after entering all command it showing permissions denied! Please run as 'sudo' 
![Screenshot_2020-04-20-09-24-28-093_tech ula](https://user-images.githubusercontent.com/44029405/79712907-cf971f80-82e9-11ea-9afa-34f2269a1a0c.jpg)

**Comment by An0nUD4Y** [comment]
Use `sudo HiddenEye.py` to launch script.

**Comment by Imran919** [comment]
Same issue after using sudo HiddenEye.py for execution

**Comment by An0nUD4Y** [comment]
@Imran919 , Please provide screenshots.
