### ISSUE TITLE
error while opening url 

### ISSUE THREAD

**Issue by Imran919** [DarkSecDevelopers/HiddenEye#568]
HiddenEye is executed after getting url when it is opened it is showing error as follow
Please help for the issue 

Failed to complete tunnel connection
The connection to https://34cd830a.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:8080.

Make sure that a web service is running on localhost:8080 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by An0nUD4Y** [comment]
check #526 
Please stop opening multiple issues if same is already closed or opened.

**Comment by Imran919** [comment]
![Screenshot_2020-04-21-10-21-38-624_com android browser](https://user-images.githubusercontent.com/44029405/79847851-ee76de00-83dd-11ea-86e8-3203f0c9fce6.jpg)
While opn url it is displacing this msg
