### ISSUE TITLE
using apache2 in termux does not wok

### ISSUE THREAD

**Issue by usama7628674** [DarkSecDevelopers/HiddenEye#57]
@alexmozzhakov Socailfish is working fine using apache server but termux version isn't working for me.I managed to install apache2 in termux and I can host index.html file but after filling all the fields when I click on sign-in it doesn't read login.php instead it shows raw php code in browser.Can you take a look at it.You can take a look at the code here  https://github.com/usama7628674/SocialFish/commit/debf63e68782079d4193a859e561504a2246cbae

**Comment by usama7628674** [comment]
There's no apache php mod so I'm thinking about lighttpd server.

**Comment by alexmozzhakov** [comment]
@usama7628674 w8, is it in master now?

**Comment by usama7628674** [comment]
@alexmozzhakov I'm thinking about lighttpd server and it's in master branch on my repo

**Comment by alexmozzhakov** [comment]
@usama7628674 I'm talking about apache version without working PHP. Also, there is a problem with such configuration you did. You cannot just rm -rf from public folders. You should only remove files from local folders and use local folders to run servers. I could set up nginx in such a way, I'm sure you can setup apache like this too.

**Comment by usama7628674** [comment]
@alexmozzhakov What about lighttpd?I think it's the best option.

**Comment by alexmozzhakov** [comment]
@usama7628674 if you get into config, there is mod_php in some place. Also, I have no experience using lighttpd. Try and test 😄

**Comment by usama7628674** [comment]
@alexmozzhakov Just tested lighttpd very fast and easy to use.

**Comment by usama7628674** [comment]
@alexmozzhakov Ok I've seen a strange behaviour.If I use lighttpd in kali it works very fast but termux lighttpd is very slow just like php so I'm revering back to apache as I figured it out a way to execute php files correctly.

**Comment by usama7628674** [comment]
@alexmozzhakov Ngrok is causing slowdown so I might use external cdn (uploadcare.com) to host .js files and see if it makes any difference

**Comment by sTiKyt** [comment]
@usama7628674 maybe we can use lighttpd for PC branch and apache for Termux?

**Comment by usama7628674** [comment]
@sTiKyt Yeah I'll change it to lighttpd for pc and apache for termux.There's a php mod for apache to load php files.

**Comment by An0nUD4Y** [comment]
No Response. Closing Here..
Feel Free to Reopen.
