### ISSUE TITLE
Error in virtual machine ( No static Local ip address assigned to VM) 

### ISSUE THREAD

**Issue by dorianus1992** [DarkSecDevelopers/HiddenEye#570]
Hey,

Im trying to run this on a localhost, but im want to use my local machine ip address and not the localhost address.
In the field that asks the localhost\router address , no matter what address i put, it keeps listening on the localhost:XXXX and the port i have entered.

Is there an option to use my local machine ip address?

Thanks!

**Comment by An0nUD4Y** [comment]
@dorianus1992 , The local server can be run only from localhost or 127.0.0.1 or the LAN/WLAN address(192.168.X.X).

**Comment by dorianus1992** [comment]
Yeah thats what i meant, I want it to run on the LAN ip address.
im not able to access the page from the machine local ip adreess:XXXX, just from the localhost:XXXX.

**Comment by dorianus1992** [comment]
> @dorianus1992 , The local server can be run only from localhost or 127.0.0.1 or the LAN/WLAN address(192.168.X.X). You can use your Public IP if you are on Any VPS server.

Yeah thats what i meant, I want it to run on the LAN ip address.
im not able to access the page from the machine local ip adreess:XXXX, just from the localhost:XXXX.

**Comment by An0nUD4Y** [comment]
@dorianus1992 , Use Your local ip when asked in hiddeneye..
And you Are supposed to open a link like, (192.xxx.xx.x:XXX)

**Comment by dorianus1992** [comment]
> @dorianus1992 , Use Your local ip when asked in hiddeneye..
> And you Are supposed to open a link like, (192.xxx.xx.x:XXX) from your local network devices.

That exactly what I did, i have entered my local ip machine address, tried to login in the same machine to http://192.XXX.XX.x:XXXX - doesnt work. tried http://localhost:XXXX - Worked fine

I run netstat  and saw that it is listening on localhost:XXXX

**Comment by An0nUD4Y** [comment]
@dorianus1992 , Did you just used http://localhost:xxxx to browse another local machine with opened server as its own local ip address.
Its weird...

**Comment by An0nUD4Y** [comment]
If it solved. Please Leave your Solution and close issue.
Thank You.

**Comment by An0nUD4Y** [comment]
@dorianus1992 , As discussed in emails. 
This error is because of you have not assigned a static Local IP address to your VM.

**Comment by An0nUD4Y** [comment]
@dorianus1992 , [Read Here](https://medium.com/shehuawwal/how-to-assign-a-static-ip-address-to-a-vmware-workstation-vm-de7773f9ef19) To know , How to assign a Static IP to Virtual Machines(VM WARE).
