### ISSUE TITLE
Url not getting opm

### ISSUE THREAD

**Issue by Imran919** [DarkSecDevelopers/HiddenEye#571]
I have executed HiddenEye after getting url i opn it for Facebook phishing it is showing error pic attached for reference 
![Screenshot_2020-04-21-10-21-38-624_com android browser](https://user-images.githubusercontent.com/44029405/79848191-66dd9f00-83de-11ea-9427-3cfc96a13b88.jpg)
![Screenshot_2020-04-21-10-24-24-426_com android browser](https://user-images.githubusercontent.com/44029405/79848200-68a76280-83de-11ea-9a8d-ea3e7c0d5ee7.jpg)

**Comment by An0nUD4Y** [comment]
check #526 
Please stop opening multiple issues if same is already closed or opened.
