### ISSUE TITLE
Ngrok not found even ngrok is installed

### ISSUE THREAD

**Issue by marhf** [DarkSecDevelopers/HiddenEye#572]
Hey Devs,(@An0nUD4Y )

OS : Kali Linux on Termux

I just installed HiddenEye, after got to know from some SECFriends...
Cloned it from the link and when I tried to launch by

> `./HiddenEye.py`

It starts...says PHP installation found and then says

```
[*] Ngrok Not Found !!
[*] Downloading Ngrok...
```

I have ngrok already installed and to be sure moved ngrok to the HiddenEye directory.

Please do respond to the issue..!!

**Comment by darkmidus** [comment]
Remove the old ngrok installation, and let HiddeneEye install it. See if that solves your issue.

**Comment by AHGaminn** [comment]
> Remove the old ngrok installation, and let HiddeneEye install it. See if that solves your issue.

same problem for me even after I removed the old ngrok installation
each time I open ./HiddenEye.py it installs again

**Comment by An0nUD4Y** [comment]
@marhf , Try Recloning The Repo ..
As i have made few commits regarding these issues.

**Comment by An0nUD4Y** [comment]
Closing Here Feel Free To reopen if issue is still occuring.

**Comment by marhf** [comment]
Thanks for the help...but it was done after some time automatically..!!
