### ISSUE TITLE
No Custom URL in Serveo are acceptable by the Program

### ISSUE THREAD

**Issue by ajthehacker13** [DarkSecDevelopers/HiddenEye#575]
I was making custom url for instagram phishing page in serveo but I got error everytime that
"FAILED TO GET THIS DOMAIN. !!!

LOOKS LIKE CUSTOM URL IS NOT VALID or ALREADY OCCUPIED BY SOMEONE ELSE. !!!

[!]TRY TO SELECT ANOTHER CUSTOM DOMAIN (GOING BACK).. !! 
"
so now what i have to do for create my custom url??

**Comment by An0nUD4Y** [comment]
Serveo.net is down currently.

**Comment by williams50th** [comment]
Hello ,

Pls do you spam for office 365 email address,if you do so pls kindly reply
back.

Thanks.
