### ISSUE TITLE
Aol page

### ISSUE THREAD

**Issue by drforbin** [DarkSecDevelopers/HiddenEye#576]
Could someone add an aol page or add a readme on how to create your own pages.

Thanxs

**Comment by An0nUD4Y** [comment]
@drforbin  Please Add the Referance URL Link As well.

**Comment by drforbin** [comment]
https://login.aol.com/

It would be good if a readme was included which explains how to create your own pages. Also a local option would be good which allows binding to another addresses other than 127.0.0.1.

**Comment by An0nUD4Y** [comment]
@drforbin , Binding to another address is already available. Just use any localhost address of your system(Ex. 192.x.x.x.x or localhost or Anyother address)

**Comment by An0nUD4Y** [comment]
Added in #569

**Comment by drforbin** [comment]
I wish you would not have closed this.The binding to another address is not closed.
It doesn't work. I'm in the process of fixing it. I have to fork and than I'll do I pull RQ

**Comment by djhashh** [comment]
same
