### ISSUE TITLE
ngrok tunnel not found

### ISSUE THREAD

**Issue by securitynoobshinnok** [DarkSecDevelopers/HiddenEye#577]
after creating a phishing link with ngrok, when opened , we get example.ngrok.io tunnrl not found error , how to fix this

**Comment by moroninventor** [comment]
I'm facing exactly the same problem. I would too like to have it's solution

**Comment by An0nUD4Y** [comment]
Fix is available pushed on gitlab clone the repo from gitlab. 
Clone Here : Https://gitlab.com/an0nud4y/hiddeneye
