### ISSUE TITLE
Failing startup : UnicodeEncodeError

### ISSUE THREAD

**Issue by SeaPhar3r** [DarkSecDevelopers/HiddenEye#579]
**Describe the bug**
During startup of HiddenEye.py the following error occurs

**To Reproduce**
Traceback (most recent call last):
  File "./HiddenEye.py", line 38, in <module>
    mainMenu()
  File "/home/grubb/HiddenEye/Defs/Actions.py", line 592, in mainMenu
    ________________________________________________________________________________'''.format(MAIN3, MAIN4, MAIN2, MAIN0, version))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

**Expected behavior**
All dependencies installed correctly and no issues during checksums. 

**Screenshots**
<img width="964" alt="Screenshot 2020-05-05 at 21 49 08" src="https://user-images.githubusercontent.com/64866481/81109357-418e7c00-8f1a-11ea-8d66-947ca3e767df.png">

**Desktop (please complete the following information):**
 - OS: Debian 9
 - VPS server

**Comment by sTiKyt** [comment]
@SeaPhar3r are you sure it's python 3?
