### ISSUE TITLE
ngrok doesn't start automatically....!!

### ISSUE THREAD

**Issue by marhf** [DarkSecDevelopers/HiddenEye#580]
Hey Devs,(@An0nUD4Y )

OS : Kali Linux on Termux

Application : HiddenEye

Thank you for responding to the previous thread(#572).

Here the new problem is, when we chose the ngrok server for tunneling the localhost, it doesn't start and an idle screen is displayed like this in the ScreenShot in the link.

https://snipboard.io/Wnkwd7.jpg

But it starts when I start ngrok manually in another session.

So why doesn't it start automatically..?

**Comment by yasarpatel** [comment]
same prob not getting link on ngrok

**Comment by sTiKyt** [comment]
@marhf @yasarpatel will be fixed in next version, don't worry, i know where problem is.
**BEFORE** starting HiddenEye please run

 `killall -2 php` 

tell me if it helps

**Comment by marhf** [comment]
> @marhf @yasarpatel will be fixed in next version, don't worry, i know where problem is.
> **BEFORE** starting HiddenEye please run
> 
>  `killall -2 php` 
> 
> tell me if it helps

No, @sTiKyt ,
The problem persists...!!!
Actually I don't have PHP installed on that Distro..

So 

killall -2 php

Results in no process found error..!!

**Comment by aliahmad21** [comment]
first of all thank you so much for re enabming the mughtest phishing tool the one and only phishing tool is hidden eye which was working perfectly but now ngrok server is not starting pls fix it thank you and keep up the good work

**Comment by ramzx** [comment]
This will help
Set on your mobile hotspot before creating the link and leave it on.
Greetz!

**Comment by aliahmad21** [comment]
Pls guyz for god sake fix it for kali linux you can use in termux but when the victime write his email and password its not getting it but this tool used to work perfectly in kali linux iam waiting for 1 month but thier is no fix for it if you guyz are not going to fix it tell me pls so i have to find other tools

**Comment by darkmidus** [comment]
@aliahmad21 Domt worry, we are working hard to get a stable 1.0 out on hiddeneye. Gove us another week and everything you should be situated.

**Comment by sTiKyt** [comment]
@marhf  php is HARD DEPENDENCY. It doesn't start because you don't have PHP.
