### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by kndahl** [DarkSecDevelopers/HiddenEye#582]
As soon as the victim enters the username and password infinite loop in the program begins.
 [ CREDENTIALS FOUND ]:
 -n
<img width="696" alt="Screenshot 2020-05-07 at 11 33 01" src="https://user-images.githubusercontent.com/56178682/81272787-a18a3d00-9056-11ea-8c1f-da815c099a22.png">

**Comment by sTiKyt** [comment]
@Eolika give us more info, which template?
Which tunelling option..
etc...

**Comment by Eolika** [comment]
it is instagram phishing page by ngrok

**Comment by williams50th** [comment]
Hello,

Do you spam for office 365,pls kindly reply back if you do .

Thanks.

**Comment by Eolika** [comment]
Hey, 
I just run this code in my Mac then I decided to check if it works properly but when I wrote my "login" and "password" on phishing Instagram page my code fell into infinite loop...that's it.

**Comment by darkmidus** [comment]
@Eolika Give us as much as possible. So you are on mac. Give us step by step how to get this error.

**Comment by sTiKyt** [comment]
@kndahl Sorry but now we don't officially support macOS users. We had big update, maybe that was fixed. Closing here, you are free to re-open.
