### ISSUE TITLE
Problem with link generation 

### ISSUE THREAD

**Issue by kalkiavatar** [DarkSecDevelopers/HiddenEye#583]
**Describe the bug**

I'M using kali on userland on my android to run this program.
after entering the redirect link and selecting the server.
the program doesn't gives me any link.
I have tried all the servers.

In pagekite it shows the following like a loop
<<pagekite.py [flying]       Kites are flying and all is well.
i tried testing the link, that time the [flying] status changes to [serving] or [traffic] but i am not getting any credentials 

below is the screenshot for LOCALXPOSE, similar problem occurs for all the servers 

![WhatsApp Image 2020-05-07 at 15 24 58](https://user-images.githubusercontent.com/64958064/81281308-4b79c180-9077-11ea-8475-3decc3a01bac.jpeg)

P.S all the files are up-to-date, i have cloned all the latest files

**Comment by ramzx** [comment]
This will help you:
Set up your mobile hotspot before creating the link and leave it on.
Download onley termux and type this code:
pkg install git python php curl openssh grep && git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git && chmod 777 HiddenEye && cd HiddenEye && pip install -r requirements.txt && pip install requests && python HiddenEye.py   

Greetz!

**Comment by kalkiavatar** [comment]
> This will help you:
> Set up your mobile hotspot before creating the link and leave it on.
> Download onley termux and type this code:
> pkg install git python php curl openssh grep && git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git && chmod 777 HiddenEye && cd HiddenEye && pip install -r requirements.txt && pip install requests && python HiddenEye.py
> 
> Greetz!

any solution for userland?

**Comment by sTiKyt** [comment]
May be fixed now, you are free to re-open if you still have this issue.
