### ISSUE TITLE
Playstation page takes too long to load PLEASE FIX!!! :(

### ISSUE THREAD

**Issue by JoeAbouMansour** [DarkSecDevelopers/HiddenEye#584]
it takes forever to load and it loads like 1 time if a second connection comes the page is broken
Please fix :(

**Comment by JoeAbouMansour** [comment]
When I launch the page using ngrok it takes forever to load but as soon as i press "Control  + C" the page loads immediately.
Maybe that would help.

**Comment by sTiKyt** [comment]
Further conversation about pages #569, closing here.
