### ISSUE TITLE
My snapchat login page is not redirecting to the custom url 

### ISSUE THREAD

**Issue by hksharmaa26** [DarkSecDevelopers/HiddenEye#585]
![Screenshot_20200507-231218](https://user-images.githubusercontent.com/34143126/81327387-ce6f3c00-90b8-11ea-947c-43a36957918a.jpg)
![Screenshot_20200507-231451](https://user-images.githubusercontent.com/34143126/81327415-d6c77700-90b8-11ea-9202-74e122083de6.jpg)
![Screenshot_20200507-231526](https://user-images.githubusercontent.com/34143126/81327426-da5afe00-90b8-11ea-885b-b54dd93d4b9d.jpg)
This is what exactly happening!!!!

**Comment by darkmidus** [comment]
Give more details please? OS, tunnel, step by step process

**Comment by sTiKyt** [comment]
Did big update, may be fixed now. You are free to re-open if this happens again.
