### ISSUE TITLE
"Curl" is not being installed automatically

### ISSUE THREAD

**Issue by luscafter** [DarkSecDevelopers/HiddenEye#590]
Hello Friend! Hidden Eye is not installing "curl" as a dependency automatically, showing this error message: "sh: 1: curl: not found".

$ sudo apt install curl

Anyway, I would like to say that the tool is amazing! Big hug! :)

**Comment by darkmidus** [comment]
Thank you for the kind words. We will fix this asap.

**Comment by luscafter** [comment]
We thank you! We are together brother! :)
