### ISSUE TITLE
Getting Pressed Keys - Unidentified Unidentified

### ISSUE THREAD

**Issue by tacemm** [DarkSecDevelopers/HiddenEye#596]
Hello guys i am coming with this issue.

![CBF6390C-FA57-4ED2-950A-8D0C579A7A30](https://user-images.githubusercontent.com/60008753/81500991-6d28b200-92de-11ea-8148-48729770032f.jpeg)

I tested on android and IOS , on android i get this issue but on IOS is working. How i can solve that ? 

P.S: Sorry for the bad picture and english 😂 .

**Comment by ramzx** [comment]
Type this command this will fix your problem
$ pkg install git python php curl openssh grep && git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git && chmod 777 HiddenEye && cd HiddenEye && pip install -r requirements.txt && pip install requests && python HiddenEye.py

**Comment by tacemm** [comment]
@ramzx thanx for your answer , i tried , but i have the same issue.

**Comment by ramzx** [comment]
Unfortunately and this?
change in the last thing:
$ pkg install git python php curl openssh grep && git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git && chmod 777 HiddenEye && cd HiddenEye && pip install -r requirements.txt && pip install requests && ./HiddenEye.py

**Comment by sTiKyt** [comment]
@ramzx why you sent him Termux-Support-Branch when he's on PC?xD

@tacemm check if this issue still exists in our latest release. If you still have these problems - you are free o re-open issue.
