### ISSUE TITLE
Hi I need help about using the custom pages.

### ISSUE THREAD

**Issue by krblood00** [DarkSecDevelopers/HiddenEye#597]
Good day! I created a custom page. I 'rm -r CUSTOM(1)' to basically replace it with my new custom page, also the name of CUSTOM(1). Ps: Right now I'm having a hard time explaining my problem but I will try.

Inside the directory named CUSTOM(1) I have my index.html index2.html, login.php and another directory for css and other webpages mainly for phishing. Apon running the program and choosing #39 for CUSTOM(1) only my index.html is showing up. How can I solve this problem? My css doesnt seem to work and other .html files

**Comment by krblood00** [comment]
![Screenshot_20200515_171312](https://user-images.githubusercontent.com/47693145/82033550-6908e580-968c-11ea-9ec6-2ae396138773.png)

**Comment by krblood00** [comment]
Hi I think I have fixed it now through embedding my css inside my index.html. But  I got another problem 

The requested resource /smedia/%3CCUSTOM%3E was not found on this server.

Im not sure how to fix this but im checking the source code of login.php and could understand where this error is coming from.

**Comment by sTiKyt** [comment]
#603 join this conversation, closing here.
