### ISSUE TITLE
Localxpose and Localtunnel doesn't create URL's for me anymore

### ISSUE THREAD

**Issue by batsgay** [DarkSecDevelopers/HiddenEye#598]
Hi, I'm running hyper.js terminal on my Windows 10 laptop. Everything seemed to work fine the first 2 days but later localxpose just stopped working. Whenever I would try to create a custom subdomain it would just say this domain isn't available or already exists. And if I use the random option it just doesn't give me anything.
I have tried doing several things to fix this issue:
- Uninstalled and installed HiddenEye twice,  
- Tried multiple different subdomain names,
-  Restarted my computer several times,
-  Reinstalled Localxpose,
-  Installed the gui windows version of localxpose to help me out 
- Tried it on the kali linux term for windows, still doesn't work 

Here are some screenshots : 
![Untitled](https://user-images.githubusercontent.com/36331381/82049081-95961f00-96d7-11ea-9dd2-5799b0d2539d.png)
![Untitled2](https://user-images.githubusercontent.com/36331381/82049104-9e86f080-96d7-11ea-820c-43a9dc16aeae.png)

I would really appreciate it if somone could give some feedback on this bug.

**Comment by batsgay** [comment]
Edit: Now it seems localtunnel also doesn't work.The same issues, won't accept any subdomains and won't give me a random domain. It just refreshes the terminal whenever I press enter
Here's a GIF of me pressing enter on localtunnel, 
https://gyazo.com/23030ac864a0b09a3c495a0a5618348f

**Comment by batsgay** [comment]
Edit (2) ngrok works completely fine and ive checked my local host and the website I created appears but localxpose or localtunnel still doesn't work.

**Comment by batsgay** [comment]
No response yet.

**Comment by Ezra-Black** [comment]
Unfortunately relying on 3rd party frameworks can result in long wait times for features or bug fixes.

**Comment by sTiKyt** [comment]
For not it's disabled, you can re-open this issue if we enable them and they still don't work.
