### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by chiggy69** [DarkSecDevelopers/HiddenEye#599]
Traceback (most recent call last):
  File "HiddenEye.py", line 7, in <module>
    from Defs.Actions import *
  File "/home/chiggy69/Desktop/hiddeneye/Defs/Actions.py", line 584
SyntaxError: Non-ASCII character '\xe2' in file /home/chiggy69/Desktop/hiddeneye/Defs/Actions.py on line 585, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
This is the error which i am getting pls tell how to solve this

**Comment by sTiKyt** [comment]
Check out our latest release, of problem still exists - you are free to re-open.
