### ISSUE TITLE
Not an Issue But a Question

### ISSUE THREAD

**Issue by jigsaw678** [DarkSecDevelopers/HiddenEye#601]
When the script asks for a redirect link 
what does it do or mean?
{noob here}

**Comment by Ezra-Black** [comment]
You should be redirecting a user to a specific link. Google link redirection? Source: general url redirection.

**Comment by lordcharlx** [comment]
> When the script asks for a redirect link
> what does it do or mean?
> {noob here}

https://dark-sec-official.com/forum/index.php?threads/beginning-with-the-social-engineer-toolkit.1/

**Comment by sTiKyt** [comment]
@jigsaw678 you can enter anything you want to redirecting link. Redirecting link get's opened after target sends you your password. 

If you have further questions - you are free to re-open.
