### ISSUE TITLE
in my linux it say pip3 command not found

### ISSUE THREAD

**Issue by sidewinder0505** [DarkSecDevelopers/HiddenEye#602]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ezra-Black** [comment]
https://stackoverflow.com/questions/26378344/how-to-know-the-version-of-pip-itself

Can you run a version control and tell us what version pip you’re on.

**Comment by sTiKyt** [comment]
@sidewinder0505 do
`sudo apt install pip && apt install pip3`

If you have further questions - you are free to re-open.
