### ISSUE TITLE
ADD WIKI For Custom webpages.

### ISSUE THREAD

**Issue by Drmaolinzheng** [DarkSecDevelopers/HiddenEye#603]
_First off guys I'd love to say I love HiddenEye 
I'm new to ethical hacking and penetration testing, but this is my best tool so far, the variety of Templates and Variety of tunneling service all my friends are much more aware about phishing now thanks to my campaigns with Hidden Eye._ 

I'm just having a little issue with the Custom web pages. I followed the examples of the preset web pages by copying a `login.php` file from one of the web pages and pasted it in the custom 1 folder I also placed my `index.html` file there. 
Then when I fire up HiddenEye and use Ngrok the Web page opens normally but when I try to input the details and submit it's doesn't show any details on the HiddenEye Terminal, instead it redirects to the Ngrok connection tunnel page and the Ngrok link would change to 
`HTTPS://3847sjsh.ngrok.io/?identifier=(the username I input)& password=(the password I input) `
please any help would be greatly appreciated, thanks.

**Comment by Ezra-Black** [comment]
Having the same issue as well.

**Comment by An0nUD4Y** [comment]
@Ezra-Black @Drmaolinzheng , We will soon provide a wiki page for the instructions.

**Comment by Ezra-Black** [comment]
Thank you!

**Comment by sTiKyt** [comment]
I did some formatting to original message cause it was very hard to read...

**Comment by An0nUD4Y** [comment]
@Ezra-Black @Drmaolinzheng 
Instructions are now available to make custom pages. 
[Check Here ](https://dark-sec-official.com/forum/index.php?threads/how-to-clone-a-custom-page-for-hiddeneye.3/)
