### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by sifatullahbhuiyan** [DarkSecDevelopers/HiddenEye#609]
**Describe the bug**
Script does not run 

**To Reproduce**
1. git clone https://github.com/DarkSecDevelopers/HiddenEye.git
2. chmod 777 HiddenEye
3. sudo apt install python3-pip
4. cd HiddenEye
5. sudo pip3 install -r requirements.txt
6. sudo pip3 install requests 
7. sudo python3 HiddenEye.py
Error

**Expected behavior**
Expected to run (time: 26th May, 2020 12:30 AM GMT+6)

**Screenshots**
![hiddeneye](https://user-images.githubusercontent.com/17397673/82836871-49be5380-9ee9-11ea-9325-ffb684930e95.JPG)

**Desktop (please complete the following information):**
 - OS: Kali LInux 5.5.0 64 bit

**Comment by AdrMXR** [comment]
crea la carpeta manualmente 
mkdir Server/www

**Comment by darkmidus** [comment]
The issue has been fixed, update to the newest version.
