### ISSUE TITLE
Ubuntu doesn't open

### ISSUE THREAD

**Issue by capaseztell** [DarkSecDevelopers/HiddenEye#614]
when you do "sudo ./HiddenEye.py" it makes a syntax error, i don't know if it's something that i'm doing wrong or an error of hiddeneye

**Comment by darkmidus** [comment]
Try both these commands to see if either of them fix the problem:

sudo python HiddenEye.py

or

sudo python3 HiddenEye.py

**Comment by darkmidus** [comment]
Are you still getting the error. If so respond, if you don't respond in another day or two we will have to close this issue as abandoned.
