### ISSUE TITLE
it has a lot of issues.Does not work properly and has errors

### ISSUE THREAD

**Issue by geet5656** [DarkSecDevelopers/HiddenEye#616]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geet5656** [comment]
please look into this tool; i have tried this and it shows errors

**Comment by darkmidus** [comment]
Uh? Whats wrong with the tool at the moment?

**Comment by sTiKyt** [comment]
If you want help - YOU FILL IN TEMPLATE.

**Comment by sTiKyt** [comment]
You are free to create new issue
