### ISSUE TITLE
Not working in parrotsec 4.9.1

### ISSUE THREAD

**Issue by Dazmed707** [DarkSecDevelopers/HiddenEye#618]
![image](https://user-images.githubusercontent.com/35184132/82939530-01ec0a80-9f83-11ea-8b6e-e5d69064f981.png)
![image](https://user-images.githubusercontent.com/35184132/82939579-14664400-9f83-11ea-81d7-236182086cc8.png)

**Comment by darkmidus** [comment]
The issue is fixed. Update to the newest version.
