### ISSUE TITLE
File Not Found Error(Server/www) while installing HiddenEye

### ISSUE THREAD

**Issue by Habibi1127** [DarkSecDevelopers/HiddenEye#619]
When i was trying to install HiddenEye it is giving me an error file not found (Server/www) after I give the command python3 HiddenEye.py. 

The Steps I used are as follows
1. git clone https://github.com/DarkSecDevelopers/HiddenEye.git
2. cd HiddenEye
3.pip3 install -r requirements.txt
4.python3 HiddenEye.py

**Expected behaviour**
I expected the Program to be installed, but it shows the error of missing file/directory : Server/www

**Screenshots**!
[Error](https://user-images.githubusercontent.com/65950620/82941930-d8e46d80-9fb4-11ea-828a-257db1727f6e.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser: Firefox
 - Version : Kali Linux 2020.2

How do I rectify this ?

**Comment by egdemems** [comment]
i am having this same issue

**Comment by darkmidus** [comment]
The issue is fixed. Update to the newest version.
