### ISSUE TITLE
Does it run on mac?

### ISSUE THREAD

**Issue by egdemems** [DarkSecDevelopers/HiddenEye#621]
I can get HiddenEye to generate ngrok urls on kali linux but not mac terminal. I was wondering if this should work?

**Comment by egdemems** [comment]
i can create a local host url but not an ngrok or serveo

**Comment by egdemems** [comment]
i even installed ngrok on my mac

**Comment by sTiKyt** [comment]
We don't officially support macOS yet

**Comment by egdemems** [comment]
> We don't officially support macOS yet

i figured it out, i just have to set up ngrok first then set hiddeneye to local host. it works smoothly
