### ISSUE TITLE
Can't open HiddenEye.py

### ISSUE THREAD

**Issue by EPPPPIIII** [DarkSecDevelopers/HiddenEye#626]
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/epicloser/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/epicloser/HiddenEye/Defs/ActionManager/simple_informant.py", line 10, in <module>
    import Defs.FeatureManager.EmailManager.email_prompt as email_prompt
  File "/home/epicloser/HiddenEye/Defs/FeatureManager/EmailManager/email_prompt.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

This is what i get when i try to open HiddenEye.py

OS: Linux
Python Version:- Python 3.6.8

Screenshot:
![Screenshot_2020-05-27_12-06-16](https://user-images.githubusercontent.com/66025753/83044805-af5a2f00-a012-11ea-9298-5ba478792592.png)

**Comment by Berus008** [comment]
you need to upgrade your python version

**Comment by Berus008** [comment]
and did you followed all the steps of installation?

**Comment by Frosty4819** [comment]
this is the same problem i had so i used an older version

**Comment by iamkhalidbashir** [comment]
Same problem. I think this is critical. On tremux app, same problem.

**Comment by pksharma132** [comment]
same problem for me too
![Screenshot from 2020-05-28 13 49 50](https://user-images.githubusercontent.com/55243875/83118305-d20c4680-a0eb-11ea-9ef9-c4c10ac49567.png)

**Comment by sanderwulp** [comment]
Same for me

**Comment by Berus008** [comment]
you dont met all the requirements try to install it again

**Comment by iamkhalidbashir** [comment]
@Berus008 Which requirements do you think we do not meet?
I just followed installation instructions. And still getting this.
Disclaimer: I installed on Android using Trimux

**Comment by Berus008** [comment]
> 
> 
> @Berus008 Which requirements do you think we do not meet?
> I just followed installation instructions. And still getting this.
> Disclaimer: I installed on Android using Trimux

like you maybe miss some packages and i think you should try in in kali linux the termux is not recomended....

**Comment by iamkhalidbashir** [comment]
@Berus008 I am running on mobile, Termux, and userLand is available on mobile. If they are not recommended, you do have to mention on the homepage about it. But it's written and I quote:-
"We care about Android Users, So now we have came with two ways to run HiddenEye in Android Devices."

**Comment by TrojanForce** [comment]
> Traceback (most recent call last):
> File "HiddenEye.py", line 8, in
> import Defs.ActionManager.main_runner as main_runner
> File "/home/epicloser/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in
> import Defs.ActionManager.simple_informant as simple_informant
> File "/home/epicloser/HiddenEye/Defs/ActionManager/simple_informant.py", line 10, in
> import Defs.FeatureManager.EmailManager.email_prompt as email_prompt
> File "/home/epicloser/HiddenEye/Defs/FeatureManager/EmailManager/email_prompt.py", line 11, in
> import Defs.ActionManager.simple_informant as simple_informant
> AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'
> 
> This is what i get when i try to open HiddenEye.py
> 
> OS: Linux
> Python Version:- Python 3.6.8
> 
> Screenshot:
> ![Screenshot_2020-05-27_12-06-16](https://user-images.githubusercontent.com/66025753/83044805-af5a2f00-a012-11ea-9298-5ba478792592.png)

just try

mkdir Server/www

if can't load email_informant just type N if ask for email, and the output will save to /Server/www

**Comment by iamkhalidbashir** [comment]
@TrojanForce It worked :+1:

**Comment by darkmidus** [comment]
You need to make sure you are opening HiddenEye with python3.

**Comment by Souldiv** [comment]
Fixed in #648
