### ISSUE TITLE
[BUG] AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

### ISSUE THREAD

**Issue by pksharma132** [DarkSecDevelopers/HiddenEye#627]
when i tried to run sudo python3 HiddenEye.py, it showed "AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'" and for sudo python HiddenEye.py it showed "ImportError: No module named ActionManager.main_runner".

![Screenshot from 2020-05-28 19 46 07](https://user-images.githubusercontent.com/55243875/83152907-f849da80-a11b-11ea-9b82-d920c28d5b02.png)

![Screenshot from 2020-05-28 19 46 33](https://user-images.githubusercontent.com/55243875/83152978-0a2b7d80-a11c-11ea-9498-df9bf4b49117.png)

 - OS: Elementary Os
 - Python [e.g. 3.6.9]

**Comment by darkmidus** [comment]
Here is a couple of tips:

 1. Update python
 2. Rego through the instructions and make sure you've installed everything. It seems like something is missing.

**Comment by sTiKyt** [comment]
@pksharma132 instead of using `sudo python` try `sudo python3`

**Comment by sTiKyt** [comment]
What `python --version` shows?

**Comment by pksharma132** [comment]
![Screenshot from 2020-05-31 12 11 33](https://user-images.githubusercontent.com/55243875/83346200-02e0bb80-a338-11ea-8b25-064e1c8fe109.png)

**Comment by sTiKyt** [comment]
@pksharma132 you should be running using `sudo python3 HiddenEye.py`

**Comment by sTiKyt** [comment]
#648

**Comment by J35t3rOP** [comment]
![Screenshot_2020-06-08_16-13-34](https://user-images.githubusercontent.com/60807708/84034465-0c56cd00-a9a3-11ea-9edc-6526c010253d.png)
same here..

**Comment by benshandd** [comment]
You need to to pip install all requirements, use, pip3 install -r requirements.txt
