### ISSUE TITLE
[BUG] Serveo doesn't generate any link

### ISSUE THREAD

**Issue by jhonparker** [DarkSecDevelopers/HiddenEye#633]
I am using this tool in my kali linux , ngrok servers are working fine, but when i try to get a custom URL
from serveo it doesn't generate any link, random links used to work but even that isn't working anymore, can you help me fix this? Thank you.
![serveocustomnotwroking](https://user-images.githubusercontent.com/66124735/83264623-f8121380-a1dd-11ea-8a55-291f4f69df9c.PNG)

**Comment by hackit999** [comment]
bro can you mail me the zip file or the Hidden Eye please
i cant run the script there is some issue please bro
mail to netflixiide@gmail.com so i can download and use it please mail it to me the entire hidden eye becoz when i download from here the script is not working showing this error
![image](https://user-images.githubusercontent.com/66170641/83330520-f9474d00-a27e-11ea-8088-f1530855c393.png)

**Comment by sTiKyt** [comment]
We found this issue, and we are working to fix it. Sorry for it, you can use Ngrok for now.

**Comment by MisterKaos34** [comment]
the serveo server displays link.url not found for the 2 options

**Comment by danieldeveloper16** [comment]
The serveo service show a message when you use the custom link and de message is "grep: link.url: the file or directory does not exist

**Comment by darkmidus** [comment]
@danieldeveloper16 We fixed that grep issue you a couple updates ago. Update your Hiddeneye and try again

**Comment by torp3do** [comment]
HiddenEye 0.5.4 
python v 3.8.5
Still serveo not working random
serveo custom is not working 
ngrok server is not working too

![117912624_303889430890905_76767369838392741](https://user-images.githubusercontent.com/67332791/90428917-037e2800-e0c5-11ea-853c-5db64e9e9bcf.jpg)

![118197483_1839749849497425_3699388559038172615](https://user-images.githubusercontent.com/67332791/90428934-0d079000-e0c5-11ea-85e8-8fcc1248b679.jpg)

![117912624_303889430890905_7676736983839274169_n](https://user-images.githubusercontent.com/67332791/90428923-0711af00-e0c5-11ea-9bb0-0b8973181bcf.jpg)e

![17912624_303889430890905_7676736983839274169_n](https://user-images.githubusercontent.com/67332791/90428910-fc571a00-e0c4-11ea-89c2-d9aae83a39f2.jpg)
![117860303_293851278540248_3422341810145455470_n](https://user-images.githubusercontent.com/67332791/90428915-011bce00-e0c5-11ea-8605-4f8c015fc6c1.jpg)
![118205857_581670606046535_3926864995903207217n](https://user-images.githubusercontent.com/67332791/90428938-0ed15380-e0c5-11ea-9f72-af493207b730.jpg)

**Comment by sTiKyt** [comment]
@torp3do Everything is not working, wait for next release... HiddenEye wasn't ever officially released as stable

**Comment by LuciferAsv** [comment]
Traceback (most recent call last):                                                                                                                                    
  File "HiddenEye.py", line 45, in <module>                                                                                                                           
    server_runner.server_selection(port)                                                                                                                              
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                                                     
    NgrokController().establish_connection(port=port)                                                                                                                 
  File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection                                                                            
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)                                                                     
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect                                                                                
    api_url = get_ngrok_process(pyngrok_config).api_url                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process                                                                      
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                                                                                                                 
AttributeError: 'str' object has no attribute 'ngrok_path'
