### ISSUE TITLE
Custom Webpages Manual missing

### ISSUE THREAD

**Issue by bluewarrior2457** [DarkSecDevelopers/HiddenEye#634]
CAN YOU PLEASE GIVE TUTORIAL OR UPDATE THE MANUAL FOR LOADING CUSTUM PAGES AS THE MANUAL.TXT SAYS THAT IT WILL BE UPDATED SOON.

**Comment by sTiKyt** [comment]
It's available on our forum. https://dark-sec-official.com/forum/index.php?threads/how-to-clone-a-custom-page-for-hiddeneye.3/#post-9
