### ISSUE TITLE
[QUESTION] How to use premium ngrok?

### ISSUE THREAD

**Issue by xinjie00** [DarkSecDevelopers/HiddenEye#635]
i realised when i use ngrok for tunneling when i press the link it shows me too many connections im wondering is it possible to add my own paid ngrok account into the programme?
if yes how do we do it ?

**Comment by sTiKyt** [comment]
It's possible but input isn't available yet. What you can do tho is open Defs/ActionManager/Server/server_runner.py

Uncomment 87 string saying `# ngrok.set_auth_token("<NGROK_AUTH_TOKEN>") `
Enter your Auth token. That's it.

I'll add easier input little bit later.
