### ISSUE TITLE
Do you accept license

### ISSUE THREAD

**Issue by rber96** [DarkSecDevelopers/HiddenEye#636]
Saludos, al intentar instalar  todo me sale esto y no me  deja continuar .
(You are not allowed....)

**Comment by darkmidus** [comment]
When you are accepting the license for the first time, make sure to type the text exactly how it says too. Like this: Yes, i do

**Comment by rber96** [comment]
excelente@darkmidus , muchas gracias

**Comment by darkmidus** [comment]
Is the issue solved, if so I'm going to close.

**Comment by darkmidus** [comment]
I'm going to assume so. I hope everything turned out well for you :)
