### ISSUE TITLE
 ./HiddenEye.py: line 11: import: command not found

### ISSUE THREAD

**Issue by BadLegend1609** [DarkSecDevelopers/HiddenEye#637]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**

**Comment by hackit999** [comment]
Cant run file ./HiddenEye.py
Error showing cant read file and command not found
Attached Screenshot below
![image](https://user-images.githubusercontent.com/66170641/83330416-3bbc5a00-a27e-11ea-9756-f87d5c8b3a68.png)

**Comment by sTiKyt** [comment]
Next time you fill in template

**Comment by hackit999** [comment]
> Next time you fill in template

bro how to do it i dont know. i have python and sudo

**Comment by hackit999** [comment]
Template as in?
Bro please explain 😭😭😭
