### ISSUE TITLE
Cant run file ./HiddenEye.py

### ISSUE THREAD

**Issue by hackit999** [DarkSecDevelopers/HiddenEye#638]
Cant run file ./HiddenEye.py
Error showing cant read file and command not found
Please help or resolve the isssue i need it for an assignment urgently please help
Attached Screenshot below
![image](https://user-images.githubusercontent.com/66170641/83330454-82aa4f80-a27e-11ea-978c-2ceea0175a19.png)

**Comment by sTiKyt** [comment]
1. You should be using python.
2. You should be using sudo.
3. Next time follow instructions...

**Comment by hackit999** [comment]
I'm using python and sudo. First there was no such i used to install and
run. Now i can't install and run why.

**Comment by hackit999** [comment]
Bro please explain me please i beg you I can't run the file.

**Comment by hackit999** [comment]
It shows me this error

**Comment by hackit999** [comment]
Please reply please
