### ISSUE TITLE
Cant run ./HiddenEye to py

### ISSUE THREAD

**Issue by hackit999** [DarkSecDevelopers/HiddenEye#639]
Please help me. I have python and sudo.
There were no problems before now suddenly this error what to do please guide me I am new to linux
I used to run this program days before now its not working
Help me please i need this please
![image](https://user-images.githubusercontent.com/66170641/83331256-7fb25d80-a284-11ea-8903-040e45157342.png)

**Comment by justinbalaguer** [comment]
same. im using wsl ubuntu

**Comment by hackit999** [comment]
Did you get any solution bro?
I think they have done some changes thats.why it can't install it or run
it. First you just had to install and run it directly. Now all this is a
mess. Why can't they give us a solution??

**Comment by justinbalaguer** [comment]
yeah no solution yet. I've used this few months back. but now its totally not working

**Comment by sTiKyt** [comment]
You are using python 2.7

Use python 3 instead

**Comment by sTiKyt** [comment]
Closing here, you are free to re-open anytime you need.
