### ISSUE TITLE
[BUG] Serveo doesn't work on termux

### ISSUE THREAD

**Issue by mieucun123** [DarkSecDevelopers/HiddenEye#641]
Server don't show any link

**Comment by TheoSanto** [comment]
> Server don't show any link

i have the same problem, serveo doesn't generate any URL (both custom and random)

**Comment by sTiKyt** [comment]
Give us more info
Help us help you

**Comment by sTiKyt** [comment]
Closing here, duplicate of #633 

Please continue discussion in #633
