### ISSUE TITLE
I have a little question! Help me

### ISSUE THREAD

**Issue by osamananama** [DarkSecDevelopers/HiddenEye#642]
how can i run it on android and is it need a root? 
Much thank

**Comment by sTiKyt** [comment]
Root your android or use termux-support-branch

**Comment by osamananama** [comment]
"termux-suppurt-branch "is it will root my android. Thank you very much for the fast service

**Comment by sTiKyt** [comment]
termux-support-branch won't root your android. Rooting your device is optional. To use Android and install HiddenEye without root, read this section of wiki: https://github.com/DarkSecDevelopers/HiddenEye/wiki/Installation-Instructions#for-android-users
