### ISSUE TITLE
[BUG] ImportError: No module named ActionManager.main_runner

### ISSUE THREAD

**Issue by ghassan222** [DarkSecDevelopers/HiddenEye#645]
I have kali linux2020 on vmware an this is what i get when i try to run hiddeneye.py:

**Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
ImportError: No module named ActionManager.main_runner**

**Comment by sTiKyt** [comment]
What `python --version` says?

**Comment by rainonwires** [comment]
update your python version.

**Comment by zMaadz** [comment]
i have the same problem 

![Screenshot_2020-06-03_21-16-16](https://user-images.githubusercontent.com/32825385/83679373-9a1b6c80-a5df-11ea-8a26-0d8d5bc9753e.png)

python --version
  Python 2.7.18rc1
python3 --version
  Python 3.8.2

i'm using the backbox ..

**Comment by karthik639** [comment]
mine also same problem bro.. 
please help..

**Comment by sTiKyt** [comment]
@karthik639 @rainonwires @ghassan222 What `python --version `says?

**Comment by kaisei915** [comment]
root@kali:~/Desktop/HiddenEye#  python HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
ImportError: No module named ActionManager.main_runner
root@kali:~/Desktop/HiddenEye# python --version
Python 2.7.18
root@kali:~/Desktop/HiddenEye# python3 --version
Python 3.8.3

**:(**

**Comment by sTiKyt** [comment]
So use python3 to run app, lol

**Comment by amil122** [comment]
I have some issue. I alrdy installed latest python version and i installed all requirmnents. But i run  this command 'python3 HiddenEye.py' i geting a error ' no  module named 'pyngrok'. Please anyone can help me?

**Comment by sTiKyt** [comment]
> I have some issue. I alrdy installed latest python version and i installed all requirmnents. But i run this command 'python3 HiddenEye.py' i geting a error ' no module named 'pyngrok'. Please anyone can help me?

Did you use "pip install" or "pip3 install"? Which one?

**Comment by amil122** [comment]
Pip3

**Comment by sTiKyt** [comment]
@amil122 Try dev branch

**Comment by amil122** [comment]
> > I have some issue. I alrdy installed latest python version and i installed all requirmnents. But i run this command 'python3 HiddenEye.py' i geting a error ' no module named 'pyngrok'. Please anyone can help me?
> 
> Did you use "pip install" or "pip3 install"? Which one?

Pip3


> @amil122 Try dev branch
@sTiKyt  How can run this? Can you please help me breifly

**Comment by sTiKyt** [comment]
@darkmidus will explain it to you now

**Comment by darkmidus** [comment]
@amil122 First off, let's make sure you run it as sudo as in the picture you are not. If for some reason the pyngrok issue persist, check your pyngrok version and report back too me.

**Comment by amil122** [comment]
Pyngrok version is 3.1.1. I run all command using sudo. But its not solved

**Comment by sTiKyt** [comment]
@amil122 your pyngrok in outdated

**Comment by amil122** [comment]
How to upgrade pyngrok

**Comment by sTiKyt** [comment]
@amil122 manually

**Comment by amil122** [comment]
Can you please tell those commands?

**Comment by amil122** [comment]
![15973308467671627783008](https://user-images.githubusercontent.com/69601510/90151068-f6e79000-dda3-11ea-947a-743bf3e2a7ae.jpg)
I run this command. Anyprblm?

**Comment by amil122** [comment]
![1597330968322-658738510](https://user-images.githubusercontent.com/69601510/90151326-3a41fe80-dda4-11ea-90fb-1e2e7d8d0614.jpg)
I run command to install pyngrok. But it shows python2.7 the end of its life on january 1st 2020. I installed latest version of python3.8.5..

**Comment by amil122** [comment]
![1597331227801-2108690992](https://user-images.githubusercontent.com/69601510/90151830-cb18da00-dda4-11ea-967d-4fb9c44a15b1.jpg)

**Comment by sTiKyt** [comment]
don't run `pip install` or `python HiddenEye.py` use `pip3 install` and `python3` instead

Closing as solved, you are free to re-open.
