### ISSUE TITLE
[BUG] AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

### ISSUE THREAD

**Issue by Souldiv** [DarkSecDevelopers/HiddenEye#647]
**Describe the bug**
Circular Dependency causing Attribute error. Particularly in the files email_prompt.py and simple_informant.py.
This causes an  AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant', as email_prompt tries to import simple_informant and vice versa.

**To Reproduce**
1. python HiddenEye.py

**Expected behavior**

**Screenshots**
![issue](https://user-images.githubusercontent.com/25404248/83357407-bb831b00-a389-11ea-8a2b-b4ac51bf4869.png)

**Device (please complete the following information):**
 - OS: ubuntu 16.04
 - Python: Python 3.6.8
 - HiddenEye Version: Latest from Master

**Additional context**
Traceback:

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/HiddenEye/Defs/ActionManager/simple_informant.py", line 10, in <module>
    import Defs.FeatureManager.EmailManager.email_prompt as email_prompt
  File "/home/HiddenEye/Defs/FeatureManager/EmailManager/email_prompt.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

**Comment by sTiKyt** [comment]
Closing due to it being duplicate, continue discussion in #627
