### ISSUE TITLE
El recurso solicitado no se encontro en este servidor

### ISSUE THREAD

**Issue by rber96** [DarkSecDevelopers/HiddenEye#652]
Saludos , al parecer la pagina de live_web no funciona , no se si sera porque actualizaron el inicio de sesion   , les agredeceria mucho si solucionaran ese incoveniente .

**Comment by rber96** [comment]
Saludos , al parecer la pagina de live_web no funciona , no se si sera porque actualizaron el login  , les agredeceria mucho si solucionaran ese incoveniente .

**Comment by sTiKyt** [comment]
This issues tracker is English only, sorry.
