### ISSUE TITLE
[Question] How to add custom template?

### ISSUE THREAD

**Issue by bluewarrior2457** [DarkSecDevelopers/HiddenEye#653]
Plz update the manual for custom temlate as i need to create a phishing page for a different site. It would be really appreciated.

**Comment by sTiKyt** [comment]
It's on our Forum, here's your link: [How To Clone A Custom Page For HiddenEye](https://dark-sec-official.com/forum/index.php?threads/how-to-clone-a-custom-page-for-hiddeneye.3/#post-9)
