### ISSUE TITLE
[DUPLICATE] Install Pyngrok

### ISSUE THREAD

**Issue by brainfool** [DarkSecDevelopers/HiddenEye#661]
Please help me sir
"Device"
Xiaomi redmi 7A
No Root
![IMG_20200607_202747](https://user-images.githubusercontent.com/66420839/83970097-00fd9600-a8fe-11ea-829e-e191293fa2d9.jpg)

**Comment by Hamsultan** [comment]
Try pip install-r requirements.txt

**Comment by sTiKyt** [comment]
offtopic but Xiaomi is pretty easy to root... 
You unlock bootloader, you install TWRP, u flash magisk, that's it... 30 minutes of work lol

**Comment by sTiKyt** [comment]
#655
