### ISSUE TITLE
Can't figure out what to do with this.

### ISSUE THREAD

**Issue by Hamsultan** [DarkSecDevelopers/HiddenEye#662]
![Screenshot_2020-06-08-03-45-37](https://user-images.githubusercontent.com/66575971/83982400-abe07500-a93b-11ea-99ee-f2fc075c72c8.png)

**Comment by Hamsultan** [comment]
Tried every way.
Ngrok copied to server and test http 80
Installed different pkgs. Downloaded autotokken and everything. But still this problem

**Comment by sTiKyt** [comment]
Seems like you don't have connection to Ngrok servers.
