### ISSUE TITLE
Ain't working

### ISSUE THREAD

**Issue by rayyankhan832** [DarkSecDevelopers/HiddenEye#665]
![Screenshot_20200608-190219](https://user-images.githubusercontent.com/66628095/84037073-b3476300-a9bb-11ea-842d-29cda0742b47.png)
![Screenshot_20200608-190135](https://user-images.githubusercontent.com/66628095/84037080-b5112680-a9bb-11ea-82ec-cc308650faeb.png)

 After confirmation its showing this yyyyyy.....not responding... please help

**Comment by sTiKyt** [comment]
Read again, confirm as it says, don't be stupid, it's IQ test xD

**Comment by rayyankhan832** [comment]
Can you please give a proper method why iam getting that y spam !! Guide me
through it

**Comment by rayyankhan832** [comment]
It says yes I do confirm !! I typed yes then it spam yyyyy.....and so on
I've posted screenshot check it

**Comment by rayyankhan832** [comment]
After I confirm it typing yes then it starts that y y y y......
