### ISSUE TITLE
[Error] ModuleNotFoundError: No module named pyngrok

### ISSUE THREAD

**Issue by pichulon1** [DarkSecDevelopers/HiddenEye#668]
I've already installed de requirements.txt, also tryed to install pyngrok manually but it still doesn't recognize de module...

When I do: `python3 HiddenEye.py`

Shows: 

```
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/root/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/root/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'
```

**Comment by J35t3rOP** [comment]
try pip3 install pyngrok

**Comment by raahimkhan** [comment]
> try pip3 install pyngrok

I did this, still same exception

**Comment by raahimkhan** [comment]
pyngrok is installed and I manually confirmed it as well but it is still throwing the exception as mentioned in this issue

**Comment by alexdlaird** [comment]
`HiddenEye` might benefit from a Makefile and using `venv`s so users don't have to mess with Python path issues like this and it can be more clear where a module is actually installed versus what Python binary is being used to execute the script.

**Comment by raahimkhan** [comment]
> `HiddenEye` might benefit from a Makefile and using `venv`s so users don't have to mess with Python path issues like this and it can be more clear where a module is actually installed versus what Python binary is being used to execute the script.

Can you tell a workaround for this issue for now?

**Comment by alexdlaird** [comment]
The error means you're not `pip install`ing the requirements file (and thus subsequently the `pyngrok` module) in to the same Python that you're using to run the script. This can be confirmed by looking at the `site-packages` folder for the Python you're using.

Trying `python3 -m pip install -r requirements.txt` instead may resolve it for you.

**Comment by raahimkhan** [comment]
> The error means you're not `pip install`ing the requirements file (and thus subsequently the `pyngrok` module) in to the same Python that you're using to run the script. This can be confirmed by looking at the `site-packages` folder for the Python you're using.
> 
> Trying `python3 -m pip install -r requirements.txt` instead may resolve it for you.



> The error means you're not `pip install`ing the requirements file (and thus subsequently the `pyngrok` module) in to the same Python that you're using to run the script. This can be confirmed by looking at the `site-packages` folder for the Python you're using.
> 
> Trying `python3 -m pip install -r requirements.txt` instead may resolve it for you.

Same issue still have tried everything

**Comment by raahimkhan** [comment]
I created a virtual environment as well.  Error persists

**Comment by rango1997** [comment]
I solved this using sudo at the install of the requirements
Example

`sudo pip3 install -r requeriments.txt`

So, it download pyngrok again and the module is visible.

**Comment by kspr2610** [comment]
what and all did you install with sudo ??

**Comment by sTiKyt** [comment]
#655 Duplicate
