### ISSUE TITLE
Serveo and ngrok not generating any link

### ISSUE THREAD

**Issue by levelsevencrew** [DarkSecDevelopers/HiddenEye#672]
serveo or ngrok both no generating any link...

**Comment by M4N0JKUM4R** [comment]
Serveo takes too long, I guess it does not generate anything at all. ngrok takes around 15 - 30 seconds to generate the link.

**Comment by sTiKyt** [comment]
> Serveo takes too long, I guess it does not generate anything at all. ngrok takes around 15 - 30 seconds to generate the link.

Was fixed in latest DEV branch update
