### ISSUE TITLE
[INVALID] ngrok tunnel not working

### ISSUE THREAD

**Issue by omegaleonard** [DarkSecDevelopers/HiddenEye#676]
The ngrok tunnel works only in the localhost, with other network do not work anymore

**Comment by sTiKyt** [comment]
@omegaleonard works for me, provide us more info.. Fill in template.. Don't make blank issues

**Comment by omegaleonard** [comment]
I generate the link correctly and when i send to other computer from another netword the site shows a tunnel error. I didnt used keylogger, fake cloudflare or anything

**Comment by sTiKyt** [comment]
It's because Ngrok has problems sometimes. Solution is buying premium ngrok and using your API key

**Comment by elixirop** [comment]
Could the problem be solved? Where do I have to add the api?

**Comment by sTiKyt** [comment]
> Could the problem be solved? Where do I have to add the api?

We didn't implement any simple way yet
