### ISSUE TITLE
[Duplicate] I can't learn to read

### ISSUE THREAD

**Issue by 1Reflex1** [DarkSecDevelopers/HiddenEye#678]
When I use ./HiddenEye.py I get

/var/mail/os
./HiddenEye.py: line 8: import: command not found
./HiddenEye.py: line 9: import: command not found
./HiddenEye.py: line 10: import: command not found
./HiddenEye.py: line 11: import: command not found
./HiddenEye.py: line 12: import: command not found
./HiddenEye.py: line 13: import: command not found
./HiddenEye.py: line 14: import: command not found
./HiddenEye.py: line 15: import: command not found
./HiddenEye.py: line 16: import: command not found
./HiddenEye.py: line 20: syntax error near unexpected token `agreement'
./HiddenEye.py: line 20: `agreement = simple_informant.terms_of_service_message()'
and when I use "python3 HiddenEye.py" I get

raceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/kali/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/kali/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by sTiKyt** [comment]
#655
