### ISSUE TITLE
[Error] No module named 'distutils.dir_util'

### ISSUE THREAD

**Issue by RonldLiu** [DarkSecDevelopers/HiddenEye#679]
I think I've already installed everything in the requirements.txt

When I do: `sudo python3 HiddenEye.py`

Shows: 

 `Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
	import Defs.ActionManager.main_runner as main_runner
  File "/home/jellyking/Desktop/HiddenEye-master/Defs/ActionManager/main_runner.py", line 9, in <module>
	from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/jellyking/Desktop/HiddenEye-master/Defs/ImportManager/unsorted_will_be_replaced.py", line 10, in <module>
	from distutils.dir_util import copy_tree as webpage_set
ModuleNotFoundError: No module named 'distutils.dir_util'`

**Comment by sTiKyt** [comment]
distutils should be built-in library, what version of python and os you are using?

**Comment by RonldLiu** [comment]
Python 3.8.2
Ubuntu 20.04 LTS

**Comment by sTiKyt** [comment]
@RonldLiu https://docs.python.org/3.8/library/distutils.html

**Comment by sTiKyt** [comment]
It's part of Python Standard Library, if you don't have it - you did something wrong with your system.
