### ISSUE TITLE
Facebook page broken

### ISSUE THREAD

**Issue by lulzsecind** [DarkSecDevelopers/HiddenEye#681]
![Screenshot_2020-06-15-23-57-42-264_com android chrome](https://user-images.githubusercontent.com/60328672/84692803-0e50fb00-af64-11ea-88a6-3b54c913c010.jpg)
Fix this "Facebook" not showing login page, Facebook logo not showing

**Comment by Wshao62** [comment]
notifications@github.com

Teach me to fish,, you have no anonymity, do you have a Japanese database?
cvv
lulzsecind <notifications@github.com> 於 2020年6月16日週二 02:29 寫道：

**Comment by Wshao62** [comment]
I know who you are,,,,,

lulzsecind <notifications@github.com> 於 2020年6月16日週二 02:29 寫道：

**Comment by Wshao62** [comment]
Are you really a girl?  ,,Taiwanese?
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3,4,,,,,,,,,,,,, of, of which English is
sent, and you deliberately use the name of the person to turn to the
goal,,,, is your female pursuit?  I have an Amazon version touch, and
paypal,,, you teach me how to set up

lulzsecind <notifications@github.com> 於 2020年6月16日週二 02:29 寫道：

**Comment by Wshao62** [comment]
I have a fresh database, do I need to help you forward the version?  But
need to teach me how to set

lulzsecind <notifications@github.com> 於 2020年6月16日週二 02:29 寫道：

**Comment by sTiKyt** [comment]
#569
