### ISSUE TITLE
Ngrok tunnel not found

### ISSUE THREAD

**Issue by ISykeI** [DarkSecDevelopers/HiddenEye#692]
when i generate the ngrok link, it works just on LAN, if i try outside my wifi it says Tunnel Not Found

**Comment by sTiKyt** [comment]
Are your ports open?

**Comment by SykeX69** [comment]
> Are your ports open?

How do i see? Because i tried with nmap on my external ip, and it said i have them closed. But i also tried on windows and it worked. I use, kali linux 2020.2 on virtualbox, and it worked on other versions

**Comment by PavleDbc** [comment]
1.Open HiddenEye
2.Opne new tab
3.In new tab put command ssh -R testhub:80:localhost:8080 serveo.net
4.Back in tab1 (Where is HiddenEye) generate your link
5.And send link what is generated in tab2(serveo link)

Same problem like you,and that its fixed it in my case,enjoy!

**Comment by PavleDbc** [comment]
and use 8080 port

**Comment by SykeX69** [comment]
> 1.Open HiddenEye
> 2.Opne new tab
> 3.In new tab put command ssh -R testhub:80:localhost:8080 serveo.net
> 4.Back in tab1 (Where is HiddenEye) generate your link
> 5.And send link what is generated in tab2(serveo link)
> 
> Same problem like you,and that its fixed it in my case,enjoy!

Thank you! I'll try, but idk why it worked on other versions of kali and not on 2020.2

**Comment by PavleDbc** [comment]
Idk too i tried on newest version.. :/

**Comment by fgabcy** [comment]
██   ██ ██ ██████   ██████   ███████ ███   ██  ███████ ██    ██ ███████                 
  ██   ██ ██ ██    ██ ██    ██ ██      ████  ██  ██       ██  ██  ██                      
  ███████ ██ ██    ██ ██    ██ ███████ ██ ██ ██  ███████   ████   ███████                 
  ██   ██ ██ ██    ██ ██    ██ ██      ██  ████  ██         ██    ██                      
  ██   ██ ██ ██████   ██████   ███████ ██   ███  ███████    ██    ███████                 
https://dark-sec-official.com                                                             
** BY:DARKSEC **                                                                          
...............................                                                           
                                                                                          
[ NGROK SERVER ]!                                                                         
-------------------------------                                                           
Traceback (most recent call last):                                                        
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok                                                                                    
    download_path = _download_file(url, timeout)                                          
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 167, in _download_file                                                                                   
    raise e                                                                               
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 158, in _download_file                                                                                   
    shutil.copyfileobj(response, f)                                                       
  File "/usr/lib/python3.8/shutil.py", line 202, in copyfileobj                           
    buf = fsrc_read(length)                                                               
  File "/usr/lib/python3.8/http/client.py", line 454, in read                             
    n = self.readinto(b)                                                                  
  File "/usr/lib/python3.8/http/client.py", line 498, in readinto                         
    n = self.fp.readinto(b)                                                               
  File "/usr/lib/python3.8/socket.py", line 669, in readinto                              
    return self._sock.recv_into(b)                                                        
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into                               
    return self.read(nbytes, buffer)                                                      
  File "/usr/lib/python3.8/ssl.py", line 1099, in read                                    
    return self._sslobj.read(len, buffer)                                                 
socket.timeout: The read operation timed out                                              
                                                                                          
During handling of the above exception, another exception occurred:                       
                                                                                          
Traceback (most recent call last):                                                        
  File "HiddenEye.py", line 48, in <module>                                               
    server_runner.server_selection(port)                                                  
  File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection                                                                           
    start_ngrok(port)  # FIXED                                                            
  File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok                                                                               
    ngrok.connect(port=int(port))                                                         
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect    
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url      
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process                                                                                    
    ensure_ngrok_installed(ngrok_path)                                                    
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed                                                                                
    install_ngrok(ngrok_path)                                                             
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok                                                                                    
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))                                                                          
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: The read operation timed out        

**When i was trying to create Ngrok Server...here is the error message I got. Please help me out**

**Comment by ornatachrome** [comment]
It didn’t work could someone help me?
Kali linux on virtualbox and i don’t know how to use wlan0.

**Comment by sTiKyt** [comment]
> ██ ██ ██ ██████ ██████ ███████ ███ ██ ███████ ██ ██ ███████
> ██ ██ ██ ██ ██ ██ ██ ██ ████ ██ ██ ██ ██ ██
> ███████ ██ ██ ██ ██ ██ ███████ ██ ██ ██ ███████ ████ ███████
> ██ ██ ██ ██ ██ ██ ██ ██ ██ ████ ██ ██ ██
> ██ ██ ██ ██████ ██████ ███████ ██ ███ ███████ ██ ███████
> https://dark-sec-official.com
> ** BY:DARKSEC **
> ...............................
> ## [ NGROK SERVER ]!
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok
> download_path = _download_file(url, timeout)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 167, in _download_file
> raise e
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 158, in _download_file
> shutil.copyfileobj(response, f)
> File "/usr/lib/python3.8/shutil.py", line 202, in copyfileobj
> buf = fsrc_read(length)
> File "/usr/lib/python3.8/http/client.py", line 454, in read
> n = self.readinto(b)
> File "/usr/lib/python3.8/http/client.py", line 498, in readinto
> n = self.fp.readinto(b)
> File "/usr/lib/python3.8/socket.py", line 669, in readinto
> return self._sock.recv_into(b)
> File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
> return self.read(nbytes, buffer)
> File "/usr/lib/python3.8/ssl.py", line 1099, in read
> return self._sslobj.read(len, buffer)
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 48, in
> server_runner.server_selection(port)
> File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection
> start_ngrok(port) # FIXED
> File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok
> ngrok.connect(port=int(port))
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect
> api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
> ensure_ngrok_installed(ngrok_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
> install_ngrok(ngrok_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok
> raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
> pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: The read operation timed out
> 
> **When i was trying to create Ngrok Server...here is the error message I got. Please help me out**

seems like network issue, try doing it again but with VPN

**Comment by Nithanka** [comment]
> ██ ██ ██ ██████ ██████ ███████ ███ ██ ███████ ██ ██ ███████
> ██ ██ ██ ██ ██ ██ ██ ██ ████ ██ ██ ██ ██ ██
> ███████ ██ ██ ██ ██ ██ ███████ ██ ██ ██ ███████ ████ ███████
> ██ ██ ██ ██ ██ ██ ██ ██ ██ ████ ██ ██ ██
> ██ ██ ██ ██████ ██████ ███████ ██ ███ ███████ ██ ███████
> https://dark-sec-official.com
> ** BY:DARKSEC **
> ...............................
> 
> ## [ NGROK SERVER ]!
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok
> download_path = _download_file(url, timeout)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 167, in _download_file
> raise e
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 158, in _download_file
> shutil.copyfileobj(response, f)
> File "/usr/lib/python3.8/shutil.py", line 202, in copyfileobj
> buf = fsrc_read(length)
> File "/usr/lib/python3.8/http/client.py", line 454, in read
> n = self.readinto(b)
> File "/usr/lib/python3.8/http/client.py", line 498, in readinto
> n = self.fp.readinto(b)
> File "/usr/lib/python3.8/socket.py", line 669, in readinto
> return self._sock.recv_into(b)
> File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
> return self.read(nbytes, buffer)
> File "/usr/lib/python3.8/ssl.py", line 1099, in read
> return self._sslobj.read(len, buffer)
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 48, in 
> server_runner.server_selection(port)
> File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection
> start_ngrok(port) # FIXED
> File "/root/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok
> ngrok.connect(port=int(port))
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect
> api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
> ensure_ngrok_installed(ngrok_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
> install_ngrok(ngrok_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok
> raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
> pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: The read operation timed out
> 
> **When i was trying to create Ngrok Server...here is the error message I got. Please help me out**

Same thing for me also!!
Can anyone help me😭😭

**Comment by voldemortOP** [comment]
Hi buddy I have an issue after generating the link the person connected to the other internet connection cannot open the link only the person connected to the same network can open the link please help me solve this

**Comment by ImranSyed12s** [comment]
> It didn’t work could someone help me?
> Kali linux on virtualbox and i don’t know how to use wlan0.

If you were to be on a virtual box, it wont detect the wlan0 , You need to get a USB for that, the reason is Virtual Box is not capable enough to connect with Wi-Fi card in your system.

**Comment by sTiKyt** [comment]
You are free to re-open.
