### ISSUE TITLE
Link not generating

### ISSUE THREAD

**Issue by worldchanger1** [DarkSecDevelopers/HiddenEye#697]
i am using HiddenEye from Terminux and everytime i go to the point that the app has to generate the link so i can use the phishing url it does not generate
![80224041_272738874046408_1794001341290274175_n](https://user-images.githubusercontent.com/67638079/86145098-cd75ec00-baf6-11ea-8bc9-03bf1c07cad4.png)

**Comment by kaisei915** [comment]
me to

**Comment by kaisei915** [comment]
I am the same.

**Comment by kaisei915** [comment]
ngrokを個別にダウンロードして、下記の通り実行してみてください。
Download ngrok individually and try it as follows :)

https://dashboard.ngrok.com/get-started/setup

**Comment by sTiKyt** [comment]
#756 duplicate

**Comment by Occulatio88** [comment]
Sorry for probably just not getting but I got ngrok now on termux too but it still comes up the same issue "currently not implemented" in the other issue you resolved that how can I resolve this issue? Sorry been only reading into it for a few days yet

**Comment by sTiKyt** [comment]
@Occulatio88 There is no way to solve that from our side, ask pyngrok developers
