### ISSUE TITLE
HIDDENEYE ISSUE

### ISSUE THREAD

**Issue by muralicbe** [DarkSecDevelopers/HiddenEye#702]
Hi Team
Here below HiddenEye Not working on Last step Kindly give me Idea to solve 

./HiddenEye.py
./HiddenEye.py: line 7: from: command not found
./HiddenEye.py: line 8: import: command not found       ./HiddenEye.py: line 9: import: command not found
./HiddenEye.py: line 10: import: command not found
./HiddenEye.py: line 11: import: command not found
./HiddenEye.py: line 12: import: command not found
./HiddenEye.py: line 13: import: command not found      ./HiddenEye.py: line 14: import: command not found
./HiddenEye.py: line 15: import: command not found
./HiddenEye.py: line 16: import: command not found
./HiddenEye.py: line 20: syntax error near unexpected token `agreement'
./HiddenEye.py: line 20: `agreement = simple_informant.terms_of_service_message()'

**Comment by darkmidus** [comment]
Try running it either using the command:

sudo python3 HiddenEye.py 

Or

sudo python HiddenEye.py
