### ISSUE TITLE
[BUG] Keylogger does not work on Facebook ngrok

### ISSUE THREAD

**Issue by M4N0JKUM4R** [DarkSecDevelopers/HiddenEye#707]
The keylogger does not capture anything on the generated ngrok link but the localhost works fine. Is this already reported or just a normal behaviour that I missed to see?

Watch the video:

[![HiddenEye Bug](https://i.imgur.com/7tbTuDV.png)](https://streamable.com/cen4ev)

Additionally, the email reports are not being generated to the recipient although I checked the credentials at least 3 times.

**Comment by sTiKyt** [comment]
It's normal for free ngrok tunnel, keylogger sends too much requests and free ngrok tunel has them limited
