### ISSUE TITLE
HiddenEye issue

### ISSUE THREAD

**Issue by KaleyLenux** [DarkSecDevelopers/HiddenEye#716]
why can i not accept de HiddenEye liscens?
This is what says: Permissions denied! Please run as sudo
helpp!!

**Comment by jake9821** [comment]
Run the same command with sudo infront?

**Comment by KaleyLenux** [comment]
i dont know the command for the agreement beacause when i write Yes, i do to confirm it says Permissions denied! Please run as sudo

**Comment by yashwardhan333666** [comment]
> sudo python3 HiddenEye.py

Run this command. 

I'm asuming u are new to linux, before using tools, i suggest u to first get to know the command line interface and basic commands. This will be very heplful in letting u understand the logic behind their usage; if u are into hacking then particualarly helpful in matasploit (one of numerous examples). Also, pls ignore my spelling mistakes (if any)
