### ISSUE TITLE
Ngrok tunnel not found outside of LAN

### ISSUE THREAD

**Issue by jake9821** [DarkSecDevelopers/HiddenEye#717]
I am using version 0.5.4 inside a virtual machine. Once I generate an ngrok link with port 1263 it works inside of lan. However over wan the link posts a "tunnel not found" error. Thanks for any help that I may receive.

**Comment by voldemortOP** [comment]
Hi buddy I have an issue after generating the link the person connected to the other internet connection cannot open the link only the person connected to the same network can open the link please help me solve this

**Comment by sTiKyt** [comment]
#692
