### ISSUE TITLE
[BUG] ImportError: No module named ActionManager.main_runner

### ISSUE THREAD

**Issue by Joshy69x** [DarkSecDevelopers/HiddenEye#719]
I go to do the python HiddenEye.py and it gives me;
  **File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
ImportError: No module named ActionManager.main_runner**

I have tried doing it in root and it still doesn't work 
Virtual Machine OS: Debian 64bit
Host OS: MacOS

**Comment by darkmidus** [comment]
Please run using python3

**Comment by Joshy69x** [comment]
nigga thats what im doing

**Comment by darkmidus** [comment]
-_- Tell me the command you are using.

**Comment by Joshy69x** [comment]
python3 HidddenEye.py

**Comment by darkmidus** [comment]
You need to run it as sudo. Make sure your python is fully updated

**Comment by darkmidus** [comment]
I'm closing this issue due to abandonment, if you give me update with more information I'd gladly reopen the issue
