### ISSUE TITLE
[BUG] Serveo is down

### ISSUE THREAD

**Issue by JoelRobert669** [DarkSecDevelopers/HiddenEye#725]
**Serveo is not working

![2020-07-19-123006_1600x900_scrot](https://user-images.githubusercontent.com/60832970/87869234-a1de7700-c9bb-11ea-9322-d1eabd2a005b.png)

it just stays on this and nothing is coming up is there any alternative to Serveo to generate a custom link

**Comment by darkmidus** [comment]
If the serveo site is down, then serveo is likely down at the moment. You could always use ngrok and get an auth token from there website. You could then manually do a custom link.

**Comment by jepunband** [comment]
Yeah, same issue here.

**Comment by HunterB430** [comment]
darkmidus, how do we do the ngrok manual link change

**Comment by JoelRobert669** [comment]
How to create a custom link using ngrok ?

**Comment by graysuit** [comment]
@JoelRobert669 
Google is your friend.
