### ISSUE TITLE
It was working in termux before now its not asking for super user permission please help

### ISSUE THREAD

**Issue by ashu-cmd** [DarkSecDevelopers/HiddenEye#734]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**

**Comment by graysuit** [comment]
https://github.com/DarkSecDevelopers/HiddenEye/issues/735#issuecomment-664496845
