### ISSUE TITLE
It ask for super user permission in termux

### ISSUE THREAD

**Issue by ashu-cmd** [DarkSecDevelopers/HiddenEye#735]
[**Describe]([url](url)) the bug**

**To Reproduce**
![Screenshot_2020-07-27-12-27-48-83](https://user-images.githubusercontent.com/67594865/88512796-bf878e00-d004-11ea-8538-f7eeb3d8bb9e.png)

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**

**Comment by MisterKaos34** [comment]
try the command "su" or "sudo", before use, after they will ask you for your password

**Comment by MiChaelinzo** [comment]
try being root user before performing sudo or su

**Comment by graysuit** [comment]
@ashu-cmd 
This isn't a bug,
You are not root and this scripts need to be root to perform big functions,
Root means administrator rights,

**Before using make sure to use 1 command from following:**
```
sudo su
```
OR
```
sudo bash
```

**After check whether you are root or not:**
```
whoami
```

**Comment by rufatsamadov** [comment]
do we have to root the phone?

**Comment by sTiKyt** [comment]
You have to use termux-support-branch
