### ISSUE TITLE
[BUG] its not workin

### ISSUE THREAD

**Issue by awais102** [DarkSecDevelopers/HiddenEye#743]
root@kali:~# cd Desktop
root@kali:~/Desktop# ls
exo-web-browser.desktop
HiddenEye-master
HiddenEye-master.zip
start-tor-browser.desktop
tor-browser_en-US
tor-browser-linux64-9.0.4_en-US.tar.xz
root@kali:~/Desktop# cd HiddenEye-master
root@kali:~/Desktop/HiddenEye-master# ls
Config.ini       index.html  README.md         version.txt
_config.yml      LICENSE     requirements.txt  WebPages
CONTRIBUTING.md  locale      Screenshot.png
Defs             logo.png    Server
HiddenEye.py     PressKit    Settings.ini
root@kali:~/Desktop/HiddenEye-master# python3 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/root/Desktop/HiddenEye-master/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/root/Desktop/HiddenEye-master/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

this the error

**Comment by sTiKyt** [comment]
#655
