### ISSUE TITLE
I get this error after all the peocess,  im a newbie pls help :cd HiddenEye

### ISSUE THREAD

**Issue by gurkirat816** [DarkSecDevelopers/HiddenEye#746]
I get this error after all the peocess,  im a newbie pls help :cd HiddenEye
$ python HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'
$

_Originally posted by @Masticoza in https://github.com/DarkSecDevelopers/HiddenEye/issues/403#issuecomment-643634554_

**Comment by darkmidus** [comment]
HiddenEye requires the python module pyngrok to run. Use the command: pip3 install pyngrok

**Comment by gurkirat816** [comment]
I already Installed pyngrok.

**Comment by darkmidus** [comment]
Make sure it is up to date. If so, uninstall it then reinstall it. Python isnt detecting that you have it.

**Comment by Rumijul** [comment]
Try this:
sudo python3 HiddenEye.py
