### ISSUE TITLE
Tunnel XXXXXXXXXX ngrok.io not found

### ISSUE THREAD

**Issue by Dxvide** [DarkSecDevelopers/HiddenEye#748]
Pls help. When using Nexphisher oder HiddenEye i cant create a ngrok link. It says Tunnel XXXXXXXXXX ngrok.io not found. When i open the link with my computer it work but it dont work on other devices

**Comment by IsmailKarakayaa** [comment]
I have the same problem. For me it works on all devices within the same network, but not on devices on other networks. I posted an issue for this one :).

**Comment by aayushs123** [comment]
Dm me on instagram @aayush_.sharma_  I will help you

**Comment by Dxvide** [comment]
Solved the problem. I reinstalled kali on the virtual machine
