### ISSUE TITLE
HiddenEye works only within same network

### ISSUE THREAD

**Issue by IsmailKarakayaa** [DarkSecDevelopers/HiddenEye#755]
Hello guys,

I have tried the HiddenEye "Get Victim Location" tool and I can say that it works like a charm on devices within the same network but not further. The tool doesn't work on devices outside my network. Is this normal? I used the ngrok server for this process since Serveo server gives me an error and other servers are unavailable. Any solutions or answers are welcome. 

PS: I am using Kali Linux on a Virtual Machine (VirtualBox). Can this cause the problem?

**Comment by sTiKyt** [comment]
> Hello guys,
> 
> I have tried the HiddenEye "Get Victim Location" tool and I can say that it works like a charm on devices within the same network but not further. The tool doesn't work on devices outside my network. Is this normal? I used the ngrok server for this process since Serveo server gives me an error and other servers are unavailable. Any solutions or answers are welcome.
> 
> PS: I am using Kali Linux on a Virtual Machine (VirtualBox). Can this cause the problem?

Probably
