### ISSUE TITLE
NGROC Error.. 

### ISSUE THREAD

**Issue by Occulatio88** [DarkSecDevelopers/HiddenEye#756]
**Describe the bug**
Whenever trying to create a Phishing page through NGROC I will get an error 

t=2020-08-13T07:33:37+0000 lvl=warn msg="failed to get home directory, using $HOME instead" err="user: Current not implemented on linux/arm64" $HOME=/data/data/com.termux/files/home           t=2020-08-13T07:33:37+0000 lvl=eror msg="failed to reconnect session" obj=csess id=e64a62af8d3d err="dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:54168->[::1]:53: read: connection refused"
Traceback (most recent call last):
  File "HiddenEye.py", line 49, in <module>
    server_menu.server_selection(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 47, in server_selection
    server_runner.start_ngrok(port) # FIXED
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_ngrok
    ngrok.connect(port=int(port))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 135, in get_ngrok_process
    return process.get_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 206, in get_process
    return _start_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 329, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:54168->[::1]:53: read: connection refused.

Every component is newly updatet and upgraded.

**Comment by sTiKyt** [comment]
Learn to read.  

> err="user: Current not implemented on linux/arm64"

**Comment by sTiKyt** [comment]
If you think it has to be implemented for arm64 - don't contact us, contact ngrok and pyngrok developers.
https://github.com/alexdlaird/pyngrok

**Comment by rufatsamadov** [comment]
> 
> 
> If you think it has to be implemented for arm64 - don't contact us, contact ngrok and pyngrok developers.
> https://github.com/alexdlaird/pyngrok

gijdillaxsan ala?

**Comment by sTiKyt** [comment]
@rufatsamadov English only please

**Comment by rufatsamadov** [comment]
> 
> 
> @rufatsamadov English only please

do you consider that you are hacker?

**Comment by sTiKyt** [comment]
@rufatsamadov I consider github being place for development, and issues have to be as clear as possible. If you continue to send OFF-TOPIC messages i'm going to restrict your access to comment section of this repository.

**Comment by rufatsamadov** [comment]
> 
> 
> @rufatsamadov I consider github being place for development, and issues have to be as clear as possible. If you continue to send OFF-TOPIC messages i'm going to restrict your access to comment section of this repository.

my question isn't off-topic dude,and you can't restrict my access to comments ,watch your steps and don't consider you as hacker,sikdir get eve peyser blet

**Comment by sTiKyt** [comment]
@rufatsamadov You are blocked for 7 days, i hope you reconsider your approach to talking with people you don't know.

**Comment by Occulatio88** [comment]
I thought it has to with DarkSec as I'm using the HiddenEye Frame and when using the Instagram handle and then using Ngrok which is stated to be working this issue comes up that's why I went over to DarkSec

**Comment by sTiKyt** [comment]
@Occulatio88 Yeah, HiddenEye isn't frame but you're welcome. You are free to re-open if they fix than on their side

**Comment by sTiKyt** [comment]
@alexdlaird can you take a look at this issue please? We aren't sure if that's on your side. and if yes - why is that a case and how can this be solved?

**Comment by alexdlaird** [comment]
There is not enough information given for me to attempt to reproduce and investigate. The error, however, would lead me to suspect it's a connectivity error to `ngrok`, either on the developer's side or `ngrok`'s side, in either case, they can't communicate for some reason. I am not the developer of `ngrok`, only `pyngrok`, we have no actual affiliation (unfortunately, haha, sometimes being able to see their code would help a lot with my wrapper). The weird thing is `linux/amd64` [should be a support platform](https://ngrok.com/download), as I understand it. But the error regarding `Error: user: Current not implemented on linux/amd64` [only appears in Go results when I Google it](https://github.com/fluxcd/flux/issues/1503), and I do know `ngrok` is written in Go, so it does appear the error is coming from there, not the `pyngrok` wrapper.

In either case, troubleshooting `pyngrok` (see the docs [here](https://pyngrok.readthedocs.io/en/latest/troubleshooting.html)) might lend some useful results for you. If you then suspect this is a bug with `pyngrok` specifically, please reproduce outside of `HiddenEye` and open an issue with more details [here](https://github.com/alexdlaird/pyngrok/issues/new?assignees=&labels=bug&template=bug-report.md&title=).

**Comment by sTiKyt** [comment]
> There is not enough information given for me to attempt to reproduce and investigate. The error, however, would lead me to suspect a connectivity error to `ngrok`, either on the developer's side or `ngrok`'s side—in either case, they can't communicate for some reason.
> 
> I am not the developer of `ngrok`, only `pyngrok`, we have no actual affiliation (unfortunately, haha, sometimes being able to see their code would help a lot with my wrapper). However, one weird thing is `linux/amd64` [should be a support platform](https://ngrok.com/download), as I understand it. But the error regarding `Error: user: Current not implemented on linux/amd64` [only appears in Go results when I Google it](https://github.com/fluxcd/flux/issues/1503), and I do know `ngrok` is written in Go, so this also appears to be an error coming from there, not the `pyngrok` wrapper.
> 
> In either case, troubleshooting `pyngrok` (see the docs [here](https://pyngrok.readthedocs.io/en/latest/troubleshooting.html)) might help you further isolate the issue. If you then suspect this is a bug with `pyngrok` specifically, please reproduce it outside of `HiddenEye` and open an issue with more details [here](https://github.com/alexdlaird/pyngrok/issues/new?assignees=&labels=bug&template=bug-report.md&title=).

Thanks, gotcha
