### ISSUE TITLE
Missing Module pyngrok -[ISSUE]

### ISSUE THREAD

**Issue by patrickcerny** [DarkSecDevelopers/HiddenEye#768]
**Describe the bug**
Even after sucessfully installing the requirements.txt, the program will not start. 

**To Reproduce**
1. `pip install -r requirements.txt`
2. `sudo python3 HiddenEye.py`
3. `Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/patrickcerny/Github/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/patrickcerny/Github/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'`

(I have tried installing newer versions of the pyngrok module with no sucess. Also, I have tried installing the modules in a venv, no sucess.)

**Device (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python [3.8.2]
 - HiddenEye Version [0.5.4]

**Additional context**
This terminal is not a real computer. It's the "Ubuntu Terminal" you can download in the microsoft store. (https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab)

**Comment by sTiKyt** [comment]
@patrickcerny Learn to look for old issues

**Comment by patrickcerny** [comment]
> @patrickcerny Learn to look for old issues

Well obv. i did research before and could not find an fitting answer so i opened a new Issue, is that wrong?

**Comment by sTiKyt** [comment]
@patrickcerny yes, that is wrong

**Comment by sTiKyt** [comment]
@sTiKyt Here goes issue you need: https://github.com/DarkSecDevelopers/HiddenEye/issues/655

**Comment by sTiKyt** [comment]
Duplicate of  #655
