### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'Requirements.txt'

### ISSUE THREAD

**Issue by malikhamza302** [DarkSecDevelopers/HiddenEye#777]
i'm trying to install hidden eye from one week same error is occurring please anyone guide me what shall i do ?
i have update version of python as well as kali linux

![Screenshot_2020-08-22_17-27-35](https://user-images.githubusercontent.com/69604402/90966134-dce13800-e49c-11ea-83cc-97db1f08d383.png)

**Comment by darkmidus** [comment]
It has been 8 days since you've given an update. I'm going to close the issue as abandoned. If your issue persists, you ate welcome to reopen this issue and give an update.
