### ISSUE TITLE
[BUG] SnapChat links won't work.

### ISSUE THREAD

**Issue by pacmex2** [DarkSecDevelopers/HiddenEye#779]
There's only 3 servers available and i need one whom i can send to some targets outside my network, so i use NGROK as it's the only one which is working for now. So whenever u try to send the link to a victim on snapchat, it just tells its a dangerous link and it won't open for them. Is there any way around this, because it's pretty much unusable rn. Thanks!

**Comment by jimisadog** [comment]
I'm having the same issue, tried link shorteners but the link still gets flagged. Anyway around this?

**Comment by sTiKyt** [comment]
We are not support forum, you can ask on StackOverflow
