### ISSUE TITLE
[BUG] network connection error 

### ISSUE THREAD

**Issue by chinnanani3335** [DarkSecDevelopers/HiddenEye#780]
Network connection error
Internet disconnected

**Comment by astr0oganja** [comment]
same problem today, please help!!

**Comment by AdrMXR** [comment]
Clone hiddeneye from here: https://github.com/AdrMXR/HiddenEye

**Comment by sTiKyt** [comment]
Use dev branch

**Comment by chinnanani3335** [comment]
How can we solve this problem?

**Comment by sankethj** [comment]
Same problem

**Comment by jeretc** [comment]
Follow the instructions at issue #773 to fix it.
