### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Hitesh-Patil-creator** [DarkSecDevelopers/HiddenEye#783]
![IMG_20200824_132524](https://user-images.githubusercontent.com/67492053/91018651-7c253d00-e60d-11ea-9d96-848937f40d45.jpg)
Please Help Me .🥺🥺🥺🥺

**Comment by AdrMXR** [comment]
Hiddeneye clone from here: https://github.com/AdrMXR/HiddenEye

**Comment by sTiKyt** [comment]
@Hitesh-Patil-creator #773 duplicate

**Comment by j9clickz** [comment]
same please fix quick

**Comment by ranjot001** [comment]
> Hiddeneye clone from here: https://github.com/AdrMXR/HiddenEye

Hey, I was also getting the same problem of Network Error. I cloned HiddenEye from you given Link and its working.
Thanks for your help!

**Comment by mrsin15** [comment]
Thank you @AdrMXR  your repo worked!

**Comment by Emperor090** [comment]
Same bro

**Comment by Emperor090** [comment]
mine didnt work idk i think some files are missing at least that is what is says
