### ISSUE TITLE
Related to hiddeneye it is showing that internet disconnected but my net is working properly can anybody from the developer side help me in this matter ?[BUG]

### ISSUE THREAD

**Issue by himanshumehla** [DarkSecDevelopers/HiddenEye#792]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**

**Comment by sTiKyt** [comment]
Duplicate of #773
