### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by parag2878** [DarkSecDevelopers/HiddenEye#794]
![IMG_20200829_072414](https://user-images.githubusercontent.com/70419241/91625944-d422c180-e9c8-11ea-9bf2-85b4b4c534c0.jpg)

It's showing this error 
But my internet connection is ok

**Comment by dirtbag145** [comment]
Having the same issue as well, unfortunately

**Comment by bond0707** [comment]
Another user provided a solution of this bug on #773

**Comment by sTiKyt** [comment]
Please don't use blank names and secribe your issues in detail next time. Closed due to having no common sense...
