### ISSUE TITLE
internet connection

### ISSUE THREAD

**Issue by eronic06** [DarkSecDevelopers/HiddenEye#795]
it say that i have internet connection problem ???

**Comment by SANISH-sanish** [comment]
it always says u are not connected to internet but when i ping google.com it pings and all the websites are opening

**Comment by zeyad1706** [comment]
> it always says u are not connected to internet but when i ping google.com it pings and all the websites are opening

**Comment by darkmidus** [comment]
I'll take a look at this issue tonight and fix it.

**Comment by bond0707** [comment]
Duplicate of #773

**Comment by bond0707** [comment]
There is a solution by another user on #773

**Comment by sTiKyt** [comment]
This issue is open but wasn't active for 30 days now, and was fixed after latest dev branch merge, closing here
