### ISSUE TITLE
No module named 'pyngrok' 

### ISSUE THREAD

**Issue by MoonbeamMoony** [DarkSecDevelopers/HiddenEye#798]
As I was doing the command "python HiddenEye.py" to open it, it says "no module named 'pyngrok'". I think there was a missing file in 'HiddenEye.py'. I am using TermuX on Android to open HiddenEye.py but failed multiple times. Any solution?

**Comment by AdrMXR** [comment]
pip3 install pyngrok

**Comment by darkmidus** [comment]
Try the command "sudo pip3 install pyngrok". If that returns a statement along the lines of "requirement already satisfied" then give your pyngrok version

**Comment by sTiKyt** [comment]
We are not support forum, go to StackOverflow
