### ISSUE TITLE
How to mask a URL after generating a link?

### ISSUE THREAD

**Issue by Hanzo96** [DarkSecDevelopers/HiddenEye#801]
after generating a link it appears like this "45jkdslfg49252x.negrok.io" which is obviously a suspicious link no one would ever click it, how do i make it looks like a legit URL?

**Comment by propkers22** [comment]
you need to buy your own domain and host it yourself

**Comment by johnsmith80** [comment]
Best way to fix it is create short URL. It's work everytime specially when you use Google: goo.gl its not look suspicious at all

**Comment by 04anubhavv** [comment]
> you need to buy your own domain and host it yourself

how to do that ?

**Comment by johnsmith80** [comment]
Try https://github.com/johnsmith80/Hacker-Hook

**Comment by sTiKyt** [comment]
This is not support forum, you can ask at StackOverflow
