### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by J020203** [DarkSecDevelopers/HiddenEye#803]
When you try to use ngrok server everythings looks fine until this message appears.

t=2020-09-02T17:30:50-0500 lvl=warn msg="failed to check for update" obj=updater err="Post https://update.equinox.io/check: context deadline exceeded"                                                                                     

The webpage with ngrok doesn't work. 

Serveo is down like the other options so doesn't show a url.

**Device (please complete the following information):**
 - OS: Kali Linux
 - Python 3.8.5
 - HiddenEye Version 0.5.4

**Comment by Samurai9954** [comment]
Hey a simple way to fix this is to choose localhost in hiddeneye, and then start ngrok from another terminal with your own personal account linked to it :-)

**Comment by J020203** [comment]
I already did that and it didn't worked

**Comment by sTiKyt** [comment]
Closed for same reason as #794
