### ISSUE TITLE
can i fix the webpages myself?

### ISSUE THREAD

**Issue by propkers22** [DarkSecDevelopers/HiddenEye#805]
for example the dropbox page is just missing css

Would I be able to fix this myself? New to this

**Comment by AdrMXR** [comment]
Yes, it's open source you don't need to ask.  You can modify the code and make a pull request with git, find out how to do it

**Comment by propkers22** [comment]
> Yes, it's open source you don't need to ask. You can modify the code and make a pull request with git, find out how to do it

yeah sorry

i've tried doing it myself but am still having issues.. would anybody be able to help me out
if it's too much to ask for i can pay fees

**Comment by darkmidus** [comment]
@propkers22 Join the DarkSec telegram and I may be able to further help you.

**Comment by Samurai9954** [comment]
As the issue was not exactly an issue, and has been solved i request to close it

**Comment by sTiKyt** [comment]
Closed due to being solved, thanks @Samurai9954 for reminding but tag someone from DarkSec members next time..
