### ISSUE TITLE
openport not working in hiddeneye

### ISSUE THREAD

**Issue by luffy1236** [DarkSecDevelopers/HiddenEye#807]
i had installed open port in HiddenEye and started working with it. but open port is not working then i opened the Hidden.py in text editor and then i opened server_runner.py then i understood that i had to install openport manually. then i opened this link https://openport.io/user and downloaded and run the openport but it is again showing again the samething.   so anyone tell me what to do to run the openport in hiddeneye

**Comment by luffy1236** [comment]
can anyone tell me the process to make run openport

**Comment by luffy1236** [comment]
Bro is anyone there 
Who can tell me the process to run the openport

**Comment by Samurai9954** [comment]
Hey! what do you mean by open port?

**Comment by luffy1236** [comment]
I installed hiddeneye after then i manually downloaded openport but i dont how to connect openport to hiddeneye

**Comment by Samurai9954** [comment]
What is open port im asking that? once you clarify i will fix your problem lol

**Comment by luffy1236** [comment]
It is an tool that will send us the fake websites in hiddeneye like ngrok, localhost etc

**Comment by Samurai9954** [comment]
i think you are getting confused with some things , ngrok and localhost are not same XD

**Comment by sTiKyt** [comment]
Seems like you are talking about outdated version of Hidden Eye.

1. We are not support forum, with all your questions please go to StackOverflow, issues are for features and bugs.
2. We don't provide support or help to outdated versions of our software.

Closing here.
