### ISSUE TITLE
[BUG] after a few hours the link does not work anymore. Sometimes the site is down and sometimes you don't getlogs when someone fills in their password.why? and how long before it happens?

### ISSUE THREAD

**Issue by mpian** [DarkSecDevelopers/HiddenEye#813]
after a few hours the link does not work anymore. Sometimes the site is down and sometimes you don't getlogs when someone fills in their password.why? and how long before it happens?

**Comment by Samurai9954** [comment]
Not enough information :(

**Comment by mpian** [comment]
When i send to link to someone it works. But after a few hours when they
click the link, the site is down or i don't get logs. So it looks like the
link for the phishing site expires.

Op vr 11 sep. 2020 8:09 a.m. schreef instagram.com <notifications@github.com

**Comment by Samurai9954** [comment]
hmmm... you are making the link from ngrok?

**Comment by mpian** [comment]
Yes. Ngrok. Should i use another server?

Op vr 11 sep. 2020 10:17 a.m. schreef instagram.com <
notifications@github.com>:

**Comment by sTiKyt** [comment]
Not a bug, you are using free connection, don't hope for it to work forever...

**Comment by mpian** [comment]
So i have to pay for it to last longer? And wich server is the best? And
how much does it cost?

Op vr 11 sep. 2020 2:05 p.m. schreef sTiKyt <notifications@github.com>:

**Comment by Samurai9954** [comment]
Yes, you cant just host a website there forever lmao

**Comment by mpian** [comment]
No. But i expect it to last for 24 hours atleast. What is the best server?
Better then Ngrok?

Op vr 11 sep. 2020 4:37 p.m. schreef instagram.com <notifications@github.com

**Comment by sTiKyt** [comment]
@mpian Don't ask us, ask google or StackOverflow... Issues aren't support forum..

**Comment by Samurai9954** [comment]
lmao, the best i think you can do is just pay lol, but actually you can recreate the page they made with some js and google spreadsheet magic, so technically you don't need to pay and you can just host anywhere for eg. github pages for free!

;)

**Comment by sTiKyt** [comment]
@Samurai9954 yeah, and get banned for phishing... But if you think you can use your own hosting - there is no need to recreate pages, you can just copy them from our project...

**Comment by Samurai9954** [comment]
but arent your based on php?

**Comment by sTiKyt** [comment]
@Samurai9954 Php is mistake of old dev, we'll be completely replacing all php with python...
