### ISSUE TITLE
[BUG] Hidden Eye on localhost works on my phone with termux, but on my win 10 laptop with wsl (ubuntu 18.04) it doesn't work?

### ISSUE THREAD

**Issue by Samurai9954** [DarkSecDevelopers/HiddenEye#814]
NOTE: i'm all day on my phone's mobile hotspot
When i installed Hidden eye on my phone with termux and ran it on localhost it ran like butter, the page was working and i was getting my email and passwords, but when i installed hidden eye on my laptop with wsl and did the same procedure, everything was the same on the wsl side but as soon as i open it in chrome it doesnt open... any ideas why?

**Device:**
 Phone: 
  - OS: Android 9 with termux
  - Model: Samsung Galaxy A20s 4GB RAM
Laptop:
 - OS: Windows 10 Home
 - WSL OS: Ubuntu 18.04

**Comment by Samurai9954** [comment]
im still waiting 😠  lmao jk

**Comment by sTiKyt** [comment]
Go to StackOverflow and ask there, this is not support forum!

Also we don't support Windows 7, 8, 8.1, 10, etc. So we won't fix this
