### ISSUE TITLE
[BUG] [I] "DISCONNECTED" ~~ " CHECK YOUR INTERNET CONNECTION " Issue ++ New After Recommended Fix 

### ISSUE THREAD

**Issue by ObNoXsHuZ** [DarkSecDevelopers/HiddenEye#817]
**Description**  
I was experiencing the exact same issue _**(#809)**_ that **@Lucifer472** has reported 3-4 day earlier than my posting.  The image he uploaded was exactly the same as my desktop;  error message of no internet and to check the connection, no menu present and application closes without returning an error code. (At least none that I could find, STDOUT or in the logs.  This same error has spanned multiple installation attempts, The build, at one point, worked well with no issues at all.  I had no issues with the prerequisites, modules or fulfilling the requirements.txt manifest.

I saw the recommended fix offered by **@tejaswankalluri82522** in the comments of @Lucifer472 's post.  Please see below:

===========================
**@tejaswankalluri82522:**
" _goto: Defs/ActionManaager/simple_informant.py , change line to:
def verify_connection(host='https://google.com'): # Connection check_ "
===========================

Now I am unable to run the application at all.  Below is a screenshot of the traceback.  I apologize for the dual issue.  I will be rolling back the changes that were recommended by 'Mr. Texas'.  That way we only have one concern, and that's why is the program not seeing a UP and active internet connection on a a standard iface.  

![Traceback from new error](https://github.com/ObNoXsHuZ/new_issue_img/blob/master/ss_HE-01b.jpg?raw=true)

**Device (please complete the following information):**
 - OS:  **Linux mint 5.4.0-26-generic #30-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux**
 - **Python 3.8.2**
 - HiddenEye Version:  ***_most recent, cloned yesterday and this morning._**

**Additional context**

**Comment by rebl0x3r** [comment]
Well i found a fix for this.

```
cd HiddenEye/Defs/ActionManager

sed -i 's/dark-sec-official.com/google.com/g' simple_informant.py
```

The problem is, defined is connection with his website, his website is down.
You just replace his website with google and then it's fixed +1

Line 246:
`def verify_connection(host='https://google.com'):`

**Comment by Samurai9954** [comment]
Hey, i actually put a solution in there, i have forked the repo and fixed it you can clone it from here - https://github.com/Samurai9954/HiddenEye.git
its fixed  :) i had the same issue

**Comment by ObNoXsHuZ** [comment]
> Well i found a fix for this.
> 
> ```
> cd HiddenEye/Defs/ActionManager
> 
> sed -i 's/dark-sec-official.com/google.com/g' simple_informant.py
> ```
> 
> The problem is, defined is connection with his website, his website is down.
> You just replace his website with google and then it's fixed +1
> 
> Line 246:
> `def verify_connection(host='https://google.com'):`

@rebl0x3r thank you for your response and workaround.  I will implement to code change via sed when I arrive home.  Cheers my friend. 👍 
&&
@samurai9954 you came through in the clutch my friend.  Out of respect, I will clone from your repo as well and test your implement.  Well done sir, a special nod to you as well.  

I too believe his site was the offending string as well.  Y'all put in commendable effort to help resolve this and I trust that both of you have made the logical (correct) modification.  Based on that -- I intend to  to 'close this bug on comment', and with much appreciation.!!

**Comment by ObNoXsHuZ** [comment]
I trust in the solutions provided and 'non cum hoc ergo propter hoc'.
