### ISSUE TITLE
[BUG] Having This issue When i load hiddenEye

### ISSUE THREAD

**Issue by timex23** [DarkSecDevelopers/HiddenEye#820]
See Issue below: anyone know how to fix this?

Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.6/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.6/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

**Comment by shyice-crypto** [comment]
> See Issue below: anyone know how to fix this?
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 45, in
> server_runner.server_selection(port)
> File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
> NgrokController().establish_connection(port=port)
> File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
> self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
> File "/usr/local/lib/python3.6/dist-packages/pyngrok/ngrok.py", line 176, in connect
> api_url = get_ngrok_process(pyngrok_config).api_url
> File "/usr/local/lib/python3.6/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
> ensure_ngrok_installed(pyngrok_config.ngrok_path)
> AttributeError: 'str' object has no attribute 'ngrok_path'

I just installed HiddenEye in Kali Linux and I experienced this same issue (exact error) after selecting Ngrok. Any advise how to fix this?

**Comment by Samurai9954** [comment]
a simple way to fix this is, choose localhost in hiddeneye, and then start ngrok from a different terminal with your own personal account linked :)

**Comment by waffler12** [comment]
> a simple way to fix this is, choose localhost in hiddeneye, and then start ngrok from a different terminal with your own personal account linked :)
 
how do you do this (sorry im new)

**Comment by ashwath921** [comment]
i too have this problem

**Comment by ashwath921** [comment]
first select localhost 
install ngrok and start in other terminal
after starting ngrok type "ngrok http (the port no you gave in hiddeneye)
and copy the generated link and send it to victims

**Comment by sTiKyt** [comment]
Name doesn't represent actual issue, go to #821
