### ISSUE TITLE
NGROK not working 

### ISSUE THREAD

**Issue by shetty87** [DarkSecDevelopers/HiddenEye#821]
im a bit of a beginner so forgive my ignorance if this issue is a real simple one ha...so i install everything fine, and go through the process...when i choose ngrok as the server i get the following errors....

Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/home/gh0st/Tools/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/home/gh0st/Tools/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

anyone able to help me fix this please

**Comment by sumanth19k** [comment]
I too have the same issue..

**Comment by waffler12** [comment]
same here

**Comment by waffler12** [comment]
exact same situation as you lol

**Comment by luscff99** [comment]
![Screenshot_20200914-001856.png](https://user-images.githubusercontent.com/70997343/93040487-83de6d00-f620-11ea-9d64-3997f21c33f8.png)
Can someone help me?

**Comment by DarkSyntax7** [comment]
Ngrok is not working!!!!

Please Do something Fast!!
[
![2020-09-16_14-13](https://user-images.githubusercontent.com/66020029/93314430-59aacc00-f827-11ea-87ad-cd7d3f78cb1c.png)
](url)

**Comment by DrHohol** [comment]
Same problem. Somebody know how to fix it?

**Comment by Saami10** [comment]
@sTiKyt any solution for this?

**Comment by sTiKyt** [comment]
@Saami10 Working on it, may be fixed at dev branch, try it our

**Comment by vanss-x** [comment]
@sTiKyt please fix it

**Comment by sTiKyt** [comment]
@vanss-x read README.md... This version is not going to be maintained anymore

**Comment by vanss-x** [comment]
How much time it need to fix

**Comment by ov1faruk** [comment]
DO anyone know when will the REBORN version be available?

**Comment by sTiKyt** [comment]
@ov1faruk soon.. More developers we have - faster it gets developed. Right now i'm doing it all almost solo... I hope someone starts contributing soon enough. We have @darkmidus working on some stuff but we don't know how it's going to turn out yet.

**Comment by kash-mp4** [comment]
"contact that lazy developer and make him code!", alright you got me there ! ;) I cannot contribute sadly.

**Comment by david8940** [comment]
hello now Work ???

**Comment by david8940** [comment]
@sTiKyt now work ngrok ??

**Comment by vanss-x** [comment]
Hi no the ngrok is not working please fix it soon I need the script so
much. In this new version ngrok not working can you send me the last
version codes

**Comment by vanss-x** [comment]
No please fix it

**Comment by Newtoxton** [comment]
The best way around this issue is to install Ngrok separately.
After that, run Hiddeneye and go through the entire process and when you reach the server select Localhost, from there feed in as desired the next steps and then copy the generated URL to the second command line where you intend to run Ngrok and feed in command "ngrok http 127.0.0.1:1024"

where 127.0.0.1:1024 should be the URL generated in HiddenEye.
That shall work just fine as it what I use.

**Comment by sTiKyt** [comment]
@Newtoxton the best way around this issue is learning to read file saying README
