### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luffy1236** [DarkSecDevelopers/HiddenEye#822]
i had installed open port in HiddenEye and started working with it. but open port is not working then i opened the Hidden.py in text editor and then i opened server_runner.py then i understood that i had to install openport manually. then i opened this linkhttps://openport.io/user and downloaded and run the openport but it is again showing again the samething. so anyone tell me what to do to run the openport in hiddeneye

**Comment by sTiKyt** [comment]
Closed for same reason as #794
