### ISSUE TITLE
[BUG] GREP: link.url

### ISSUE THREAD

**Issue by laszl0o** [DarkSecDevelopers/HiddenEye#841]
Just downloaded a latest version of HiddenEye and it seems that this bug still isn’t fixed

**Comment by sTiKyt** [comment]
@laszl0o What do you mean by "latest"? Master or dev?

**Comment by E1MWM13** [comment]
> @laszl0o What do you mean by "latest"? Master or dev?

i don't understand what you mean Master or Dev but i got the same bug can you help me

**Comment by E1MWM13** [comment]
> @laszl0o What do you mean by "latest"? Master or dev?

important for you to know we are android user using Termux without root not Linux with own root so you can try using Termux without root and get the same error and fix it quickly

**Comment by E1MWM13** [comment]
> @laszl0o What do you mean by "latest"? Master or dev?

get in our place haha just see the bug & error

**Comment by E1MWM13** [comment]
> @laszl0o What do you mean by "latest"? Master or dev?

i understand now i download lastest master HiddenEye

**Comment by E1MWM13** [comment]
> @laszl0o What do you mean by "latest"? Master or dev?

sir i recomend for HiddenEye next update pls don't use pyngrok use the manual install ngrok pls or make an setup script for install ngrok but don't use pyngrok its error for android user its better for a manual script install its work for Termux + Linux i am waiting for the next update don't destroy our hope on HiddenEye

**Comment by sTiKyt** [comment]
Won't be fixed, this version of hidden eye is not maintained anymore, for more details read README.md and follow link at upper part
